import Crates.AArithAbort
import FV.E2E.Binary
import FV.E2E.NonVacuityLink

/-! # Non-vacuity of the binary-level theorems on a real executable

The executable is `examples/survey`'s `a_arith` test binary built with `cargo fv test -p a_arith
--panic-abort --keep-temps` (its crate proof: `Crates.AArithAbort`, generated by `cargo fv
link-proof --crate a_arith --mode plain-abort`). The entry is the Lean-compiled
`core::num::<i32>::wrapping_add` of the executable, called by outside code with the arguments
`2` and `3`: every premise of `E2E.Binary.binary_correct_depth` holds for a concrete machine
state (`OutsideCall`, `ClifRun`, `BaseOk` with the closed base environment, `TrapsExplicit` from
the returning run), the program's CLIF run returns `5`, and the theorem gives the machine's return
to the caller with `5` in x0.
-/

namespace Crates.BinaryWitness

open E2E E2E.LinkCheck E2E.Binary Backend Backend.Proof

abbrev I : LinkInput := Crates.AArithAbort.input

/-- The entry's symbol. -/
def n : String := "__fv_fe6c5eba82df__RNvMs6_NtCsazjiGSRkgVH_4core3numm12wrapping_add"

/-- The entry (`core::num::<i32>::wrapping_add`). -/
def f : Clif.Function := Crates.AArithAbort.fn6.func

def bF : Clif.Block := f.entry?.getD default

def args : List Clif.Val := [⟨.i32, 2#32⟩, ⟨.i32, 3#32⟩]

/-- The depth (and CLIF fuel `M + 1`). -/
def M : Nat := 8

/-- The caller's stack pointer and return address (outside the program's code). -/
def sp0 : BitVec 64 := 0x10000000000
def ra0 : BitVec 64 := 0x20000000000

/-- The body's stack pointer of the entry. -/
def sb : BitVec 64 := sp0 - BitVec.ofNat 64 (frameDrop (artOf I.results f).af)

/-- The caller's CLIF memory: no live allocation, the CLIF image's symbols, the slot-placement
oracle at the entry's body `sp`. -/
def cm : Clif.Mem :=
  { symbols := fun n => I.syms.lookup n, place := some ⟨[sb], (sys I closedBase).frames⟩ }

/-- The reference CLIF entry state of `f` on `2, 3`. -/
def cs : Clif.State where
  frame := { func := f, regs := (Clif.Regs.empty.setMany (bF.params.map (·.1)) args).getD default,
             slots := [], body := bF.body, term := bF.term }
  callers := []
  mem := cm

/-- The program's CLIF run from `cs`. -/
def run : Clif.Outcome := Clif.runLoop closedBase.env (progOf I.results) (M + 1) cs

/-- The machine state of the call: pc at `f`'s address, x30 the caller's return address,
`sp0`, the arguments in x0 and x1. -/
def r : Arm.ArmState :=
  Arm.w .PC (artOf I.results f).base (Arm.w (.GPR 30#5) ra0 (Arm.w (.GPR 31#5) sp0
    (Arm.w (.GPR 0#5) 2#64 (Arm.w (.GPR 1#5) 3#64 Arm.ArmState.default))))

def locB : Bool :=
  match locsOf f.sig with
  | [.reg (.x 0), .reg (.x 1)] => true
  | _ => false

/-- The facts of the entry decided on the executable's data. -/
def factsB : Bool :=
  decide ((progOf I.results).func? n = some f) && decide (f.entry? = some bF) &&
  decide (args.map (·.ty) = f.sig.params.map (·.ty)) &&
  decide (bF.params.map (·.2) = args.map (·.ty)) &&
  (Clif.Regs.empty.setMany (bF.params.map (·.1)) args).isSome && decide (f.slots = []) &&
  locB &&
  LinkWitness.isRet run && decide (LinkWitness.retVals run = [⟨.i32, 5#32⟩]) &&
  (tabOf I.results).all (fun e => decide (e.2.base.toNat + 4 * e.2.fb.words.size + 4 ≤ 2 ^ 32)) &&
  decide (frameDrop (artOf I.results f).af + I.D * M ≤ 2 ^ 20)

theorem factsB_true : factsB = true := by native_decide

theorem facts :
    (progOf I.results).func? n = some f ∧ f.entry? = some bF ∧
    args.map (·.ty) = f.sig.params.map (·.ty) ∧ bF.params.map (·.2) = args.map (·.ty) ∧
    (Clif.Regs.empty.setMany (bF.params.map (·.1)) args).isSome = true ∧ f.slots = [] ∧
    locB = true ∧ LinkWitness.isRet run = true ∧ LinkWitness.retVals run = [⟨.i32, 5#32⟩] ∧
    (tabOf I.results).all (fun e => decide (e.2.base.toNat + 4 * e.2.fb.words.size + 4 ≤ 2 ^ 32))
      = true ∧
    frameDrop (artOf I.results f).af + I.D * M ≤ 2 ^ 20 := by
  have h := factsB_true
  simp only [factsB, Bool.and_eq_true, decide_eq_true_eq] at h
  obtain ⟨⟨⟨⟨⟨⟨⟨⟨⟨⟨h1, h2⟩, h3⟩, h4⟩, h5⟩, h6⟩, h7⟩, h8⟩, h9⟩, h10⟩, h11⟩ := h
  exact ⟨h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11⟩

/-- Every code address of the program is below `2^32`. -/
theorem img_lt {x : BitVec 64} (h : img I x) : x.toNat < 2 ^ 32 := by
  obtain ⟨e, he, p, hp, hx⟩ := h
  have hb := facts.2.2.2.2.2.2.2.2.2.1
  have hb' : e.2.base.toNat + 4 * e.2.fb.words.size + 4 ≤ 2 ^ 32 := by
    have := List.all_eq_true.mp hb e he
    simpa using this
  obtain ⟨j, hj, e'⟩ := LinkWitness.wordsAt_mem_inv (k := 0) hp
  simp only [Array.length_toList] at hj
  rw [e', BitVec.toNat_sub, BitVec.toNat_add, BitVec.toNat_ofNat] at hx
  have := e.2.base.isLt
  have := x.isLt
  rw [Nat.mod_eq_of_lt (by omega : 4 * (0 + j) < 2 ^ 64),
    Nat.mod_eq_of_lt (by omega : e.2.base.toNat + 4 * (0 + j) < 2 ^ 64)] at hx
  omega

theorem sp0_toNat : sp0.toNat = 2 ^ 40 := rfl

theorem pc_r : Arm.r .PC r = (artOf I.results f).base := Arm.r_of_w_same

theorem spv_r : spv r = sp0 := by
  simp only [spv, r]
  rw [Arm.r_of_w_different (by decide), Arm.r_of_w_different (by decide), Arm.r_of_w_same]

theorem x30_r : xreg 30 r = ra0 := by
  simp only [xreg, r]
  rw [Arm.r_of_w_different (by decide), Arm.r_of_w_same]

theorem err_r : Arm.r .ERR r = .None := by
  simp only [r]
  rw [Arm.r_of_w_different (by decide), Arm.r_of_w_different (by decide),
    Arm.r_of_w_different (by decide), Arm.r_of_w_different (by decide),
    Arm.r_of_w_different (by decide)]
  simp [Arm.r, Arm.read_base_error, Arm.ArmState.default]

theorem x0_r : Arm.r (.GPR (rnum 0)) r = 2#64 := by
  simp only [r, rnum]
  rw [Arm.r_of_w_different (by decide), Arm.r_of_w_different (by decide),
    Arm.r_of_w_different (by decide), Arm.r_of_w_same]

theorem x1_r : Arm.r (.GPR (rnum 1)) r = 3#64 := by
  simp only [r, rnum]
  rw [Arm.r_of_w_different (by decide), Arm.r_of_w_different (by decide),
    Arm.r_of_w_different (by decide), Arm.r_of_w_different (by decide), Arm.r_of_w_same]

theorem locs : locsOf f.sig = [.reg (.x 0), .reg (.x 1)] := by
  have h := facts.2.2.2.2.2.2.1
  unfold locB at h
  split at h
  · assumption
  · cases h

/-- The outside caller's contract holds in `r` (stack `frameDrop + D·M` bytes). -/
theorem outsideCall :
    OutsideCall I (fun _ => none) f (frameDrop (art I f).af + I.D * M) r args cs.mem where
  pc := pc_r
  err := err_r
  ra := fun h => by have := img_lt h; rw [x30_r] at this; simp [ra0] at this
  spAligned := by rw [spv_r]; decide
  stack := by rw [spv_r, sp0_toNat]; have := facts.2.2.2.2.2.2.2.2.2.2; simp only [art]; omega
  stackFree := fun a ha hb => by
    have := img_lt ha
    have := facts.2.2.2.2.2.2.2.2.2.2
    rw [spv_r] at hb
    obtain ⟨-, h2⟩ := hb
    rw [sp0_toNat] at h2
    simp only [art] at h2
    omega
  args := fun loc v hm => by
    rw [locs] at hm
    simp only [args, List.zip_cons_cons, List.zip_nil_right, List.mem_cons, Prod.mk.injEq,
      List.not_mem_nil, or_false] at hm
    rcases hm with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
    · simp only [VHolds, regVal, x0_r]; rfl
    · simp only [VHolds, regVal, x1_r]; rfl
  bytes := fun _ _ hv => by simp [cs, cm, Clif.Mem.valid] at hv
  image := fun _ _ _ hv => by simp [cs, cm, Clif.Mem.valid] at hv
  valid := fun _ _ hv => by simp [cs, cm, Clif.Mem.valid] at hv
  symbols := rfl

theorem clifEntry : ClifEntry f args cs := by
  obtain ⟨-, hb, hsig, hpar, hset, hsl, -⟩ := facts
  refine ⟨rfl, rfl, hsig, ⟨bF, hb, rfl, rfl, hpar, ?_⟩, by simp [cs, hsl]⟩
  show _ = some ((Clif.Regs.empty.setMany (bF.params.map (·.1)) args).getD default)
  revert hset
  cases Clif.Regs.empty.setMany (bF.params.map (·.1)) args <;> simp

/-- The reference CLIF run. -/
theorem clifRun : ClifRun I closedBase f r args cs where
  entry := clifEntry
  slots := fun _ _ h => by simp [cs] at h
  place := fun _ => ⟨[], by
    show some _ = some _
    rw [show spBody (art I f).af r = sb by simp only [spBody, spv_r, sb]]⟩

/-- The program's CLIF run returns `5`. -/
theorem run_eq : run = .returned [⟨.i32, 5#32⟩] (LinkWitness.retMem run) := by
  rw [← facts.2.2.2.2.2.2.2.2.1]
  exact LinkWitness.eq_returned facts.2.2.2.2.2.2.2.1

/-- **Non-vacuity of `binary_correct_depth`** on the `a_arith` executable (panic=abort): a
machine state `r` in which outside code calls the executable's Lean-compiled
`core::num::<i32>::wrapping_add` with `2` and `3` meets the boundary contract, the reference
CLIF run exists and returns `5`, and the theorem gives the machine's return to the caller's
return address with `5` in x0. -/
theorem binary_depth_witness :
    OutsideCall I (fun _ => none) f (frameDrop (art I f).af + I.D * M) r args cs.mem ∧
    ClifRun I closedBase f r args cs ∧
    Clif.runLoop closedBase.env (prog I) (M + 1) cs = .returned [⟨.i32, 5#32⟩] (LinkWitness.retMem run) ∧
    ∃ k, ArmRet ra0 (modelOf I f r) (runX ((sys I closedBase).mach M f) k (modelOf I f r)) ∧
      XHolds ⟨.i32, 5#32⟩ (xreg 0 (runX ((sys I closedBase).mach M f) k (modelOf I f r))) := by
  have hf := facts.1
  have hfm := (Clif.Program.func?_some hf).1
  have hL := okB_sound Crates.AArithAbort.okB_input (Crates.AArithAbort.base_closed (img I))
    (fun _ h => h)
  have htr := trapsExplicit_of_run hL hfm clifEntry rfl run_eq
  have h := binary_correct_depth Crates.AArithAbort.okB_input closedBase
    (Crates.AArithAbort.base_closed _) hf M outsideCall clifRun htr
  rw [show Clif.runLoop closedBase.env (prog I) (M + 1) cs = run from rfl, run_eq, x30_r] at h
  obtain ⟨k, hret, hx, -⟩ := h
  exact ⟨outsideCall, clifRun, run_eq, k, hret, hx 0 _ rfl⟩

end Crates.BinaryWitness
