import Crates.DeadCleanupGeneratedSplit.Slice0
import Crates.DeadCleanupGeneratedSplit.Slice1
import FV.E2E.DeadCleanupStackBound

/-! # Crate-level instance of `backend_correct_program` (generated)

Generated by `cargo fv link-proof` / `lake exe link-check` (docs/contracts/e2e.md,
"Crate-level instance") for the executable

  closed cleanup split witness

The program `P` is the 33 functions of `input` (the CLIF `lean-backend` compiled, with the
link's symbol names, and `lean-regalloc`'s output), loaded at their addresses in the
executable's link map (`addrs`). `okB_input` decides every premise of `LinkSys.Ok` about the
program and its layout by `native_decide` (`okBCleanup_of`: the program's checks, `globalB_input`, and
the per-function checks by slices of 32 functions, `sliceK_ok`, each in its own module), run as compiled
code (the package `crate-proofs` loads the shared library of `FV.E2E.DeadCleanupStackBound` and
`FV.E2E.DeadCleanupBinCheck`); `link_ok` is
`LinkSys.Ok` of the crate's linked system for every base environment satisfying the base
premises (`BaseOk`: the contracts of std, other crates' code and the runtime, which stay
premises), and the `correct_*` theorems are `backend_correct_program` for the entries;
`stack_ok` decides the stack bound (`FV/E2E/DeadCleanupStackBound.lean`: the call graph has no cycle), and
the `correct_stack_*` theorems are `backend_correct_program_stack` for the entries (at every
fuel).

**The executable** (docs/contracts/e2e.md, "Binary level (M9)"): `bin_ok` states `E2E.DeadCleanupBinCheck.BinOk input
dataObjs file` for every file whose bytes agree with the excerpts `exAll` of this executable
(its headers, the code of the functions and the GOT slots they load, the 0 data objects the
program reaches, its symbol entries): a static AArch64 executable whose loaded image holds every
function's compiled words with its relocations resolved (`ArtOk`), the data objects with theirs
(`DataOk`), and whose symbol table is the link map (`SymsOk`); by `native_decide` on the
excerpts (`hdr_bin`, `sliceK_bin`, `data_bin`, `syms_bin`).
-/

namespace Crates.DeadCleanupGeneratedSplit

open E2E E2E.LinkCheck E2E.BinCheck

/-- The checks of the program (`globalChks`). -/
theorem globalB_input : globalBCleanup input = true := by native_decide

/-- Every premise of `LinkSys.Ok` about the program and its layout. -/
theorem okB_input : okBCleanup input = true :=
  okBCleanup_of globalB_input (by
    show fnsBCleanup input (slice0 ++ slice1) = true
    simp only [fnsBCleanup_append, slice0_ok, slice1_ok, Bool.and_self])

/-- **`LinkSys.Ok` of the crate's linked system**, for every base environment satisfying the base
premises and every `F` containing the code. -/
theorem link_ok (B : BaseEnv) (F : BitVec 64 → Prop) (hB : BaseOk (LinkSys.ofInputCleanup input B F))
    (hF : ∀ a, (LinkSys.ofInputCleanup input B F).Img a → F a) : (LinkSys.ofInputCleanup input B F).Ok :=
  okBCleanup_sound okB_input hB hF

/-- No function has a `tls_value`. -/
theorem noTls : (progOf input.resultsCleanup).funcs.all (fun g => !Backend.hasTls g) = true := by
  native_decide

/-- **The base premises are satisfiable**: the closed base environment (`closedBase`: nothing
outside the program has a semantics) satisfies them, so `link_ok` and the `correct_*` theorems
are not vacuous in their base premises. -/
theorem base_closed (F : BitVec 64 → Prop) : BaseOk (LinkSys.ofInputCleanup input closedBase F) :=
  baseOk_closedCleanup fun g hg => by simpa using List.all_eq_true.1 noTls g hg

/-- The entries are functions of the program. -/
theorem entries_present :
    ["codeB", "okB", "crate_correct", "cleanup_split_0", "cleanup_split_1", "cleanup_split_2", "cleanup_split_3", "cleanup_split_4", "cleanup_split_5", "cleanup_split_6", "cleanup_split_7", "cleanup_split_8", "cleanup_split_9", "cleanup_split_10", "cleanup_split_11", "cleanup_split_12", "cleanup_split_13", "cleanup_split_14", "cleanup_split_15", "cleanup_split_16", "cleanup_split_17", "cleanup_split_18", "cleanup_split_19", "cleanup_split_20", "cleanup_split_21", "cleanup_split_22", "cleanup_split_23", "cleanup_split_24", "cleanup_split_25", "cleanup_split_26", "cleanup_split_27", "cleanup_split_28", "cleanup_split_29"].all
      (fun n => ((progOf input.resultsCleanup).func? n).isSome) = true := by native_decide

/-- The executable's headers: a static AArch64 executable. -/
theorem hdr_bin : hdrB exHdr = true := by native_decide

/-- The data objects in the executable (`DataOk`). -/
theorem data_bin : dataB input dataObjs (exHdr ++ exData) = true := by native_decide

/-- The link map is the executable's symbol table (`SymsOk`). -/
theorem syms_bin : symsB input (exHdr ++ exSyms) symCert = true := by native_decide

/-- The excerpts of the executable the binary checks read. -/
def exAll : Elf.Excerpt := exHdr ++ (ex0 ++ (ex1 ++ (exData ++ (exSyms))))

/-- **The executable is the crate's linked program**: every file whose bytes agree with the
excerpts is a static AArch64 executable holding the program's code with its relocations
resolved, the data objects, and the link map as its symbol table (`E2E.DeadCleanupBinCheck.BinOk`). -/
theorem bin_ok (file : ByteArray) (h : Elf.Agrees file exAll) : E2E.DeadCleanupBinCheck.BinOk input dataObjs file := by
  simp only [exAll, Elf.agrees_append] at h
  obtain ⟨hH, h0, h1, hD, hS⟩ := h
  exact E2E.DeadCleanupBinCheck.binOk_of (hdrB_sound hdr_bin hH)
    (E2E.DeadCleanupBinCheck.artsOk_append (E2E.DeadCleanupBinCheck.codeB_sound slice0_bin (Elf.agrees_append.2 ⟨hH, h0⟩))
      (E2E.DeadCleanupBinCheck.codeB_sound slice1_bin (Elf.agrees_append.2 ⟨hH, h1⟩)))
    (dataB_sound data_bin (Elf.agrees_append.2 ⟨hH, hD⟩))
    (symsB_sound syms_bin (Elf.agrees_append.2 ⟨hH, hS⟩))

/-- **`backend_correct_program` for `codeB`** -/
theorem correct_0 : CrateStmtCleanup input "codeB" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `okB`** -/
theorem correct_1 : CrateStmtCleanup input "okB" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `crate_correct`** -/
theorem correct_2 : CrateStmtCleanup input "crate_correct" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_0`** -/
theorem correct_3 : CrateStmtCleanup input "cleanup_split_0" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_1`** -/
theorem correct_4 : CrateStmtCleanup input "cleanup_split_1" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_2`** -/
theorem correct_5 : CrateStmtCleanup input "cleanup_split_2" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_3`** -/
theorem correct_6 : CrateStmtCleanup input "cleanup_split_3" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_4`** -/
theorem correct_7 : CrateStmtCleanup input "cleanup_split_4" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_5`** -/
theorem correct_8 : CrateStmtCleanup input "cleanup_split_5" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_6`** -/
theorem correct_9 : CrateStmtCleanup input "cleanup_split_6" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_7`** -/
theorem correct_10 : CrateStmtCleanup input "cleanup_split_7" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_8`** -/
theorem correct_11 : CrateStmtCleanup input "cleanup_split_8" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_9`** -/
theorem correct_12 : CrateStmtCleanup input "cleanup_split_9" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_10`** -/
theorem correct_13 : CrateStmtCleanup input "cleanup_split_10" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_11`** -/
theorem correct_14 : CrateStmtCleanup input "cleanup_split_11" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_12`** -/
theorem correct_15 : CrateStmtCleanup input "cleanup_split_12" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_13`** -/
theorem correct_16 : CrateStmtCleanup input "cleanup_split_13" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_14`** -/
theorem correct_17 : CrateStmtCleanup input "cleanup_split_14" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_15`** -/
theorem correct_18 : CrateStmtCleanup input "cleanup_split_15" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_16`** -/
theorem correct_19 : CrateStmtCleanup input "cleanup_split_16" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_17`** -/
theorem correct_20 : CrateStmtCleanup input "cleanup_split_17" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_18`** -/
theorem correct_21 : CrateStmtCleanup input "cleanup_split_18" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_19`** -/
theorem correct_22 : CrateStmtCleanup input "cleanup_split_19" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_20`** -/
theorem correct_23 : CrateStmtCleanup input "cleanup_split_20" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_21`** -/
theorem correct_24 : CrateStmtCleanup input "cleanup_split_21" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_22`** -/
theorem correct_25 : CrateStmtCleanup input "cleanup_split_22" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_23`** -/
theorem correct_26 : CrateStmtCleanup input "cleanup_split_23" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_24`** -/
theorem correct_27 : CrateStmtCleanup input "cleanup_split_24" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_25`** -/
theorem correct_28 : CrateStmtCleanup input "cleanup_split_25" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_26`** -/
theorem correct_29 : CrateStmtCleanup input "cleanup_split_26" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_27`** -/
theorem correct_30 : CrateStmtCleanup input "cleanup_split_27" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_28`** -/
theorem correct_31 : CrateStmtCleanup input "cleanup_split_28" :=
  crate_correct_cleanup okB_input _

/-- **`backend_correct_program` for `cleanup_split_29`** -/
theorem correct_32 : CrateStmtCleanup input "cleanup_split_29" :=
  crate_correct_cleanup okB_input _

/-- **The stack bound** (`FV/E2E/DeadCleanupStackBound.lean`): the program's call graph has no cycle, and an
activation of any of its functions uses at most 224 bytes of stack with its callees
(`DeadCleanupStackBound.stackFn_le`). -/
theorem stack_ok : DeadCleanupStackBound.stackB input = some 224 := by native_decide

/-- **`backend_correct_program_stack` for `codeB`**: at every fuel, with the stack bound. -/
theorem correct_stack_0 : DeadCleanupStackBound.StackStmt input "codeB" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `okB`**: at every fuel, with the stack bound. -/
theorem correct_stack_1 : DeadCleanupStackBound.StackStmt input "okB" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `crate_correct`**: at every fuel, with the stack bound. -/
theorem correct_stack_2 : DeadCleanupStackBound.StackStmt input "crate_correct" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_0`**: at every fuel, with the stack bound. -/
theorem correct_stack_3 : DeadCleanupStackBound.StackStmt input "cleanup_split_0" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_1`**: at every fuel, with the stack bound. -/
theorem correct_stack_4 : DeadCleanupStackBound.StackStmt input "cleanup_split_1" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_2`**: at every fuel, with the stack bound. -/
theorem correct_stack_5 : DeadCleanupStackBound.StackStmt input "cleanup_split_2" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_3`**: at every fuel, with the stack bound. -/
theorem correct_stack_6 : DeadCleanupStackBound.StackStmt input "cleanup_split_3" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_4`**: at every fuel, with the stack bound. -/
theorem correct_stack_7 : DeadCleanupStackBound.StackStmt input "cleanup_split_4" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_5`**: at every fuel, with the stack bound. -/
theorem correct_stack_8 : DeadCleanupStackBound.StackStmt input "cleanup_split_5" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_6`**: at every fuel, with the stack bound. -/
theorem correct_stack_9 : DeadCleanupStackBound.StackStmt input "cleanup_split_6" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_7`**: at every fuel, with the stack bound. -/
theorem correct_stack_10 : DeadCleanupStackBound.StackStmt input "cleanup_split_7" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_8`**: at every fuel, with the stack bound. -/
theorem correct_stack_11 : DeadCleanupStackBound.StackStmt input "cleanup_split_8" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_9`**: at every fuel, with the stack bound. -/
theorem correct_stack_12 : DeadCleanupStackBound.StackStmt input "cleanup_split_9" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_10`**: at every fuel, with the stack bound. -/
theorem correct_stack_13 : DeadCleanupStackBound.StackStmt input "cleanup_split_10" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_11`**: at every fuel, with the stack bound. -/
theorem correct_stack_14 : DeadCleanupStackBound.StackStmt input "cleanup_split_11" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_12`**: at every fuel, with the stack bound. -/
theorem correct_stack_15 : DeadCleanupStackBound.StackStmt input "cleanup_split_12" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_13`**: at every fuel, with the stack bound. -/
theorem correct_stack_16 : DeadCleanupStackBound.StackStmt input "cleanup_split_13" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_14`**: at every fuel, with the stack bound. -/
theorem correct_stack_17 : DeadCleanupStackBound.StackStmt input "cleanup_split_14" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_15`**: at every fuel, with the stack bound. -/
theorem correct_stack_18 : DeadCleanupStackBound.StackStmt input "cleanup_split_15" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_16`**: at every fuel, with the stack bound. -/
theorem correct_stack_19 : DeadCleanupStackBound.StackStmt input "cleanup_split_16" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_17`**: at every fuel, with the stack bound. -/
theorem correct_stack_20 : DeadCleanupStackBound.StackStmt input "cleanup_split_17" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_18`**: at every fuel, with the stack bound. -/
theorem correct_stack_21 : DeadCleanupStackBound.StackStmt input "cleanup_split_18" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_19`**: at every fuel, with the stack bound. -/
theorem correct_stack_22 : DeadCleanupStackBound.StackStmt input "cleanup_split_19" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_20`**: at every fuel, with the stack bound. -/
theorem correct_stack_23 : DeadCleanupStackBound.StackStmt input "cleanup_split_20" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_21`**: at every fuel, with the stack bound. -/
theorem correct_stack_24 : DeadCleanupStackBound.StackStmt input "cleanup_split_21" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_22`**: at every fuel, with the stack bound. -/
theorem correct_stack_25 : DeadCleanupStackBound.StackStmt input "cleanup_split_22" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_23`**: at every fuel, with the stack bound. -/
theorem correct_stack_26 : DeadCleanupStackBound.StackStmt input "cleanup_split_23" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_24`**: at every fuel, with the stack bound. -/
theorem correct_stack_27 : DeadCleanupStackBound.StackStmt input "cleanup_split_24" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_25`**: at every fuel, with the stack bound. -/
theorem correct_stack_28 : DeadCleanupStackBound.StackStmt input "cleanup_split_25" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_26`**: at every fuel, with the stack bound. -/
theorem correct_stack_29 : DeadCleanupStackBound.StackStmt input "cleanup_split_26" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_27`**: at every fuel, with the stack bound. -/
theorem correct_stack_30 : DeadCleanupStackBound.StackStmt input "cleanup_split_27" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_28`**: at every fuel, with the stack bound. -/
theorem correct_stack_31 : DeadCleanupStackBound.StackStmt input "cleanup_split_28" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `cleanup_split_29`**: at every fuel, with the stack bound. -/
theorem correct_stack_32 : DeadCleanupStackBound.StackStmt input "cleanup_split_29" :=
  DeadCleanupStackBound.crate_correct_stack okB_input stack_ok _

end Crates.DeadCleanupGeneratedSplit
