import Crates.FCrypto.Slice0
import Crates.FCrypto.Slice1
import FV.E2E.StackBound

/-! # Crate-level instance of `backend_correct_program` (generated)

Generated by `cargo fv link-proof` / `lake exe link-check` (docs/contracts/e2e.md,
"Crate-level instance") for the executable

  /home/kev/work/clifv-wt/bin-bytes/examples/survey/target/fv/plain/aarch64-unknown-linux-musl/debug/build/f_crypto/d4e972ae8ddc3a8a/out/values-d4e972ae8ddc3a8a

The program `P` is the 40 functions of `input` (the CLIF `lean-backend` compiled, with the
link's symbol names, and `lean-regalloc`'s output), loaded at their addresses in the
executable's link map (`addrs`). `okB_input` decides every premise of `LinkSys.Ok` about the
program and its layout by `native_decide` (`okB_of`: the program's checks, `globalB_input`, and
the per-function checks by slices of 32 functions, `sliceK_ok`, each in its own module), run as compiled
code (the package `crate-proofs` loads the shared library of `FV.E2E.StackBound` and
`FV.E2E.BinCheck`); `link_ok` is
`LinkSys.Ok` of the crate's linked system for every base environment satisfying the base
premises (`BaseOk`: the contracts of std, other crates' code and the runtime, which stay
premises), and the `correct_*` theorems are `backend_correct_program` for the entries;
`stack_ok` decides the stack bound (`FV/E2E/StackBound.lean`: the call graph has no cycle), and
the `correct_stack_*` theorems are `backend_correct_program_stack` for the entries (at every
fuel).

**The executable** (docs/contracts/e2e.md, "Binary level (M9)"): `bin_ok` states `BinOk input
dataObjs file` for every file whose bytes agree with the excerpts `exAll` of this executable
(its headers, the code of the functions and the GOT slots they load, the 123 data objects the
program reaches, its symbol entries): a static AArch64 executable whose loaded image holds every
function's compiled words with its relocations resolved (`ArtOk`), the data objects with theirs
(`DataOk`), and whose symbol table is the link map (`SymsOk`); by `native_decide` on the
excerpts (`hdr_bin`, `sliceK_bin`, `data_bin`, `syms_bin`).
-/

namespace Crates.FCrypto

open E2E E2E.LinkCheck E2E.BinCheck

/-- The checks of the program (`globalChks`). -/
theorem globalB_input : globalB input = true := by native_decide

/-- Every premise of `LinkSys.Ok` about the program and its layout. -/
theorem okB_input : okB input = true :=
  okB_of globalB_input (by
    show fnsB input (slice0 ++ slice1) = true
    simp only [fnsB_append, slice0_ok, slice1_ok, Bool.and_self])

/-- **`LinkSys.Ok` of the crate's linked system**, for every base environment satisfying the base
premises and every `F` containing the code. -/
theorem link_ok (B : BaseEnv) (F : BitVec 64 → Prop) (hB : BaseOk (LinkSys.ofInput input B F))
    (hF : ∀ a, (LinkSys.ofInput input B F).Img a → F a) : (LinkSys.ofInput input B F).Ok :=
  okB_sound okB_input hB hF

/-- No function has a `tls_value`. -/
theorem noTls : (progOf input.results).funcs.all (fun g => !Backend.hasTls g) = true := by
  native_decide

/-- **The base premises are satisfiable**: the closed base environment (`closedBase`: nothing
outside the program has a semantics) satisfies them, so `link_ok` and the `correct_*` theorems
are not vacuous in their base premises. -/
theorem base_closed (F : BitVec 64 → Prop) : BaseOk (LinkSys.ofInput input closedBase F) :=
  baseOk_closed fun g hg => by simpa using List.all_eq_true.1 noTls g hg

/-- The entries are functions of the program. -/
theorem entries_present :
    ["__fv_37189324023f__RNvMs5_NtCsazjiGSRkgVH_4core3numt12wrapping_sub", "__fv_37189324023f__RNvMs6_NtCsazjiGSRkgVH_4core3numm11rotate_left", "__fv_37189324023f__RNvMs6_NtCsazjiGSRkgVH_4core3numm12rotate_right", "__fv_37189324023f__RNvMs6_NtCsazjiGSRkgVH_4core3numm12wrapping_add", "__fv_37189324023f__RNvXs1c_NtNtCsazjiGSRkgVH_4core3cmp5implslNtB8_10PartialOrd2lt", "__fv_37189324023f__RNvXsU_NtNtCsazjiGSRkgVH_4core3cmp5implsjNtB7_10PartialOrd2lt", "_RNxC8f_crypto11H29OvvQRDpy", "_RNxC8f_crypto11HZ67z10Drjb", "_RNxC8f_crypto11Hn9wHlv6rwS", "__fv_37189324023f__RNxC8f_crypto12H1nPRDDeSNKs", "_RNxC8f_crypto12H2wOfoUDhHOO", "__fv_37189324023f__RNxC8f_crypto12H41t9vfOlBo5", "_RNxC8f_crypto12H4W4IX9lEWKt", "__fv_37189324023f__RNxC8f_crypto12H4cxagBYueUk", "_RNxC8f_crypto12H5VKc7o6RShp", "_RNxC8f_crypto12H5uXghGVnqSZ", "_RNxC8f_crypto12H6Sv4s6zdkLD", "__fv_37189324023f__RNxC8f_crypto12H6U31UEpDqFH", "__fv_37189324023f__RNxC8f_crypto12H7Q12NeDeJ4C", "__fv_37189324023f__RNxC8f_crypto12H8Ey3wq51RNO", "__fv_37189324023f__RNxC8f_crypto12Ha4YJ1jjLv4w", "_RNxC8f_crypto12HaHh8uvyanYB", "_RNxC8f_crypto12HbNWOuN1Xvlt", "_RNxC8f_crypto12HbZpZjoAalHX", "__fv_37189324023f__RNxC8f_crypto12HcKxZ5WAz64I", "__fv_37189324023f__RNxC8f_crypto12HekqC08LoBdF", "__fv_37189324023f__RNxC8f_crypto12HfgeW0Z2oBsQ", "_RNxC8f_crypto12HgIwETO0I2ur", "__fv_37189324023f__RNxC8f_crypto12Hgbng4aFzSom", "__fv_37189324023f__RNxC8f_crypto12HghN5Rmlyi4q", "_RNxC8f_crypto12HhiXAjCKBW7w", "__fv_37189324023f__RNxC8f_crypto12Hi5p372B4x00", "_RNxC8f_crypto12HimYCq6Bwri1", "_RNxC8f_crypto12HkTIWOU3z2ty", "_RNxC8f_crypto12HkqwaGP8eNcF", "__fv_37189324023f__RNxC8f_crypto12HkrKt9FxX5Uv", "chacha20_block", "chacha_quarter_round", "ct_eq", "sha256_compress"].all
      (fun n => ((progOf input.results).func? n).isSome) = true := by native_decide

/-- The executable's headers: a static AArch64 executable. -/
theorem hdr_bin : hdrB exHdr = true := by native_decide

/-- The data objects in the executable (`DataOk`). -/
theorem data_bin : dataB input dataObjs (exHdr ++ exData) = true := by native_decide

/-- The link map is the executable's symbol table (`SymsOk`). -/
theorem syms_bin : symsB input (exHdr ++ exSyms) symCert = true := by native_decide

/-- The excerpts of the executable the binary checks read. -/
def exAll : Elf.Excerpt := exHdr ++ (ex0 ++ (ex1 ++ (exData ++ (exSyms))))

/-- **The executable is the crate's linked program**: every file whose bytes agree with the
excerpts is a static AArch64 executable holding the program's code with its relocations
resolved, the data objects, and the link map as its symbol table (`BinOk`). -/
theorem bin_ok (file : ByteArray) (h : Elf.Agrees file exAll) : BinOk input dataObjs file := by
  simp only [exAll, Elf.agrees_append] at h
  obtain ⟨hH, h0, h1, hD, hS⟩ := h
  exact binOk_of (hdrB_sound hdr_bin hH)
    (artsOk_append (codeB_sound slice0_bin (Elf.agrees_append.2 ⟨hH, h0⟩))
      (codeB_sound slice1_bin (Elf.agrees_append.2 ⟨hH, h1⟩)))
    (dataB_sound data_bin (Elf.agrees_append.2 ⟨hH, hD⟩))
    (symsB_sound syms_bin (Elf.agrees_append.2 ⟨hH, hS⟩))

/-- **`backend_correct_program` for `__fv_37189324023f__RNvMs5_NtCsazjiGSRkgVH_4core3numt12wrapping_sub`** -/
theorem correct_0 : CrateStmt input "__fv_37189324023f__RNvMs5_NtCsazjiGSRkgVH_4core3numt12wrapping_sub" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_37189324023f__RNvMs6_NtCsazjiGSRkgVH_4core3numm11rotate_left`** -/
theorem correct_1 : CrateStmt input "__fv_37189324023f__RNvMs6_NtCsazjiGSRkgVH_4core3numm11rotate_left" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_37189324023f__RNvMs6_NtCsazjiGSRkgVH_4core3numm12rotate_right`** -/
theorem correct_2 : CrateStmt input "__fv_37189324023f__RNvMs6_NtCsazjiGSRkgVH_4core3numm12rotate_right" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_37189324023f__RNvMs6_NtCsazjiGSRkgVH_4core3numm12wrapping_add`** -/
theorem correct_3 : CrateStmt input "__fv_37189324023f__RNvMs6_NtCsazjiGSRkgVH_4core3numm12wrapping_add" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_37189324023f__RNvXs1c_NtNtCsazjiGSRkgVH_4core3cmp5implslNtB8_10PartialOrd2lt`** -/
theorem correct_4 : CrateStmt input "__fv_37189324023f__RNvXs1c_NtNtCsazjiGSRkgVH_4core3cmp5implslNtB8_10PartialOrd2lt" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_37189324023f__RNvXsU_NtNtCsazjiGSRkgVH_4core3cmp5implsjNtB7_10PartialOrd2lt`** -/
theorem correct_5 : CrateStmt input "__fv_37189324023f__RNvXsU_NtNtCsazjiGSRkgVH_4core3cmp5implsjNtB7_10PartialOrd2lt" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC8f_crypto11H29OvvQRDpy`** -/
theorem correct_6 : CrateStmt input "_RNxC8f_crypto11H29OvvQRDpy" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC8f_crypto11HZ67z10Drjb`** -/
theorem correct_7 : CrateStmt input "_RNxC8f_crypto11HZ67z10Drjb" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC8f_crypto11Hn9wHlv6rwS`** -/
theorem correct_8 : CrateStmt input "_RNxC8f_crypto11Hn9wHlv6rwS" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_37189324023f__RNxC8f_crypto12H1nPRDDeSNKs`** -/
theorem correct_9 : CrateStmt input "__fv_37189324023f__RNxC8f_crypto12H1nPRDDeSNKs" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC8f_crypto12H2wOfoUDhHOO`** -/
theorem correct_10 : CrateStmt input "_RNxC8f_crypto12H2wOfoUDhHOO" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_37189324023f__RNxC8f_crypto12H41t9vfOlBo5`** -/
theorem correct_11 : CrateStmt input "__fv_37189324023f__RNxC8f_crypto12H41t9vfOlBo5" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC8f_crypto12H4W4IX9lEWKt`** -/
theorem correct_12 : CrateStmt input "_RNxC8f_crypto12H4W4IX9lEWKt" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_37189324023f__RNxC8f_crypto12H4cxagBYueUk`** -/
theorem correct_13 : CrateStmt input "__fv_37189324023f__RNxC8f_crypto12H4cxagBYueUk" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC8f_crypto12H5VKc7o6RShp`** -/
theorem correct_14 : CrateStmt input "_RNxC8f_crypto12H5VKc7o6RShp" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC8f_crypto12H5uXghGVnqSZ`** -/
theorem correct_15 : CrateStmt input "_RNxC8f_crypto12H5uXghGVnqSZ" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC8f_crypto12H6Sv4s6zdkLD`** -/
theorem correct_16 : CrateStmt input "_RNxC8f_crypto12H6Sv4s6zdkLD" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_37189324023f__RNxC8f_crypto12H6U31UEpDqFH`** -/
theorem correct_17 : CrateStmt input "__fv_37189324023f__RNxC8f_crypto12H6U31UEpDqFH" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_37189324023f__RNxC8f_crypto12H7Q12NeDeJ4C`** -/
theorem correct_18 : CrateStmt input "__fv_37189324023f__RNxC8f_crypto12H7Q12NeDeJ4C" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_37189324023f__RNxC8f_crypto12H8Ey3wq51RNO`** -/
theorem correct_19 : CrateStmt input "__fv_37189324023f__RNxC8f_crypto12H8Ey3wq51RNO" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_37189324023f__RNxC8f_crypto12Ha4YJ1jjLv4w`** -/
theorem correct_20 : CrateStmt input "__fv_37189324023f__RNxC8f_crypto12Ha4YJ1jjLv4w" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC8f_crypto12HaHh8uvyanYB`** -/
theorem correct_21 : CrateStmt input "_RNxC8f_crypto12HaHh8uvyanYB" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC8f_crypto12HbNWOuN1Xvlt`** -/
theorem correct_22 : CrateStmt input "_RNxC8f_crypto12HbNWOuN1Xvlt" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC8f_crypto12HbZpZjoAalHX`** -/
theorem correct_23 : CrateStmt input "_RNxC8f_crypto12HbZpZjoAalHX" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_37189324023f__RNxC8f_crypto12HcKxZ5WAz64I`** -/
theorem correct_24 : CrateStmt input "__fv_37189324023f__RNxC8f_crypto12HcKxZ5WAz64I" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_37189324023f__RNxC8f_crypto12HekqC08LoBdF`** -/
theorem correct_25 : CrateStmt input "__fv_37189324023f__RNxC8f_crypto12HekqC08LoBdF" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_37189324023f__RNxC8f_crypto12HfgeW0Z2oBsQ`** -/
theorem correct_26 : CrateStmt input "__fv_37189324023f__RNxC8f_crypto12HfgeW0Z2oBsQ" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC8f_crypto12HgIwETO0I2ur`** -/
theorem correct_27 : CrateStmt input "_RNxC8f_crypto12HgIwETO0I2ur" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_37189324023f__RNxC8f_crypto12Hgbng4aFzSom`** -/
theorem correct_28 : CrateStmt input "__fv_37189324023f__RNxC8f_crypto12Hgbng4aFzSom" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_37189324023f__RNxC8f_crypto12HghN5Rmlyi4q`** -/
theorem correct_29 : CrateStmt input "__fv_37189324023f__RNxC8f_crypto12HghN5Rmlyi4q" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC8f_crypto12HhiXAjCKBW7w`** -/
theorem correct_30 : CrateStmt input "_RNxC8f_crypto12HhiXAjCKBW7w" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_37189324023f__RNxC8f_crypto12Hi5p372B4x00`** -/
theorem correct_31 : CrateStmt input "__fv_37189324023f__RNxC8f_crypto12Hi5p372B4x00" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC8f_crypto12HimYCq6Bwri1`** -/
theorem correct_32 : CrateStmt input "_RNxC8f_crypto12HimYCq6Bwri1" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC8f_crypto12HkTIWOU3z2ty`** -/
theorem correct_33 : CrateStmt input "_RNxC8f_crypto12HkTIWOU3z2ty" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC8f_crypto12HkqwaGP8eNcF`** -/
theorem correct_34 : CrateStmt input "_RNxC8f_crypto12HkqwaGP8eNcF" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_37189324023f__RNxC8f_crypto12HkrKt9FxX5Uv`** -/
theorem correct_35 : CrateStmt input "__fv_37189324023f__RNxC8f_crypto12HkrKt9FxX5Uv" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `chacha20_block`** -/
theorem correct_36 : CrateStmt input "chacha20_block" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `chacha_quarter_round`** -/
theorem correct_37 : CrateStmt input "chacha_quarter_round" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `ct_eq`** -/
theorem correct_38 : CrateStmt input "ct_eq" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `sha256_compress`** -/
theorem correct_39 : CrateStmt input "sha256_compress" :=
  crate_correct okB_input _

/-- **The stack bound** (`FV/E2E/StackBound.lean`): the program's call graph has no cycle, and an
activation of any of its functions uses at most 1120 bytes of stack with its callees
(`StackBound.stackFn_le`). -/
theorem stack_ok : StackBound.stackB input = some 1120 := by native_decide

/-- **`backend_correct_program_stack` for `__fv_37189324023f__RNvMs5_NtCsazjiGSRkgVH_4core3numt12wrapping_sub`**: at every fuel, with the stack bound. -/
theorem correct_stack_0 : StackBound.StackStmt input "__fv_37189324023f__RNvMs5_NtCsazjiGSRkgVH_4core3numt12wrapping_sub" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `__fv_37189324023f__RNvMs6_NtCsazjiGSRkgVH_4core3numm11rotate_left`**: at every fuel, with the stack bound. -/
theorem correct_stack_1 : StackBound.StackStmt input "__fv_37189324023f__RNvMs6_NtCsazjiGSRkgVH_4core3numm11rotate_left" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `__fv_37189324023f__RNvMs6_NtCsazjiGSRkgVH_4core3numm12rotate_right`**: at every fuel, with the stack bound. -/
theorem correct_stack_2 : StackBound.StackStmt input "__fv_37189324023f__RNvMs6_NtCsazjiGSRkgVH_4core3numm12rotate_right" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `__fv_37189324023f__RNvMs6_NtCsazjiGSRkgVH_4core3numm12wrapping_add`**: at every fuel, with the stack bound. -/
theorem correct_stack_3 : StackBound.StackStmt input "__fv_37189324023f__RNvMs6_NtCsazjiGSRkgVH_4core3numm12wrapping_add" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `__fv_37189324023f__RNvXs1c_NtNtCsazjiGSRkgVH_4core3cmp5implslNtB8_10PartialOrd2lt`**: at every fuel, with the stack bound. -/
theorem correct_stack_4 : StackBound.StackStmt input "__fv_37189324023f__RNvXs1c_NtNtCsazjiGSRkgVH_4core3cmp5implslNtB8_10PartialOrd2lt" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `__fv_37189324023f__RNvXsU_NtNtCsazjiGSRkgVH_4core3cmp5implsjNtB7_10PartialOrd2lt`**: at every fuel, with the stack bound. -/
theorem correct_stack_5 : StackBound.StackStmt input "__fv_37189324023f__RNvXsU_NtNtCsazjiGSRkgVH_4core3cmp5implsjNtB7_10PartialOrd2lt" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `_RNxC8f_crypto11H29OvvQRDpy`**: at every fuel, with the stack bound. -/
theorem correct_stack_6 : StackBound.StackStmt input "_RNxC8f_crypto11H29OvvQRDpy" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `_RNxC8f_crypto11HZ67z10Drjb`**: at every fuel, with the stack bound. -/
theorem correct_stack_7 : StackBound.StackStmt input "_RNxC8f_crypto11HZ67z10Drjb" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `_RNxC8f_crypto11Hn9wHlv6rwS`**: at every fuel, with the stack bound. -/
theorem correct_stack_8 : StackBound.StackStmt input "_RNxC8f_crypto11Hn9wHlv6rwS" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `__fv_37189324023f__RNxC8f_crypto12H1nPRDDeSNKs`**: at every fuel, with the stack bound. -/
theorem correct_stack_9 : StackBound.StackStmt input "__fv_37189324023f__RNxC8f_crypto12H1nPRDDeSNKs" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `_RNxC8f_crypto12H2wOfoUDhHOO`**: at every fuel, with the stack bound. -/
theorem correct_stack_10 : StackBound.StackStmt input "_RNxC8f_crypto12H2wOfoUDhHOO" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `__fv_37189324023f__RNxC8f_crypto12H41t9vfOlBo5`**: at every fuel, with the stack bound. -/
theorem correct_stack_11 : StackBound.StackStmt input "__fv_37189324023f__RNxC8f_crypto12H41t9vfOlBo5" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `_RNxC8f_crypto12H4W4IX9lEWKt`**: at every fuel, with the stack bound. -/
theorem correct_stack_12 : StackBound.StackStmt input "_RNxC8f_crypto12H4W4IX9lEWKt" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `__fv_37189324023f__RNxC8f_crypto12H4cxagBYueUk`**: at every fuel, with the stack bound. -/
theorem correct_stack_13 : StackBound.StackStmt input "__fv_37189324023f__RNxC8f_crypto12H4cxagBYueUk" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `_RNxC8f_crypto12H5VKc7o6RShp`**: at every fuel, with the stack bound. -/
theorem correct_stack_14 : StackBound.StackStmt input "_RNxC8f_crypto12H5VKc7o6RShp" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `_RNxC8f_crypto12H5uXghGVnqSZ`**: at every fuel, with the stack bound. -/
theorem correct_stack_15 : StackBound.StackStmt input "_RNxC8f_crypto12H5uXghGVnqSZ" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `_RNxC8f_crypto12H6Sv4s6zdkLD`**: at every fuel, with the stack bound. -/
theorem correct_stack_16 : StackBound.StackStmt input "_RNxC8f_crypto12H6Sv4s6zdkLD" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `__fv_37189324023f__RNxC8f_crypto12H6U31UEpDqFH`**: at every fuel, with the stack bound. -/
theorem correct_stack_17 : StackBound.StackStmt input "__fv_37189324023f__RNxC8f_crypto12H6U31UEpDqFH" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `__fv_37189324023f__RNxC8f_crypto12H7Q12NeDeJ4C`**: at every fuel, with the stack bound. -/
theorem correct_stack_18 : StackBound.StackStmt input "__fv_37189324023f__RNxC8f_crypto12H7Q12NeDeJ4C" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `__fv_37189324023f__RNxC8f_crypto12H8Ey3wq51RNO`**: at every fuel, with the stack bound. -/
theorem correct_stack_19 : StackBound.StackStmt input "__fv_37189324023f__RNxC8f_crypto12H8Ey3wq51RNO" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `__fv_37189324023f__RNxC8f_crypto12Ha4YJ1jjLv4w`**: at every fuel, with the stack bound. -/
theorem correct_stack_20 : StackBound.StackStmt input "__fv_37189324023f__RNxC8f_crypto12Ha4YJ1jjLv4w" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `_RNxC8f_crypto12HaHh8uvyanYB`**: at every fuel, with the stack bound. -/
theorem correct_stack_21 : StackBound.StackStmt input "_RNxC8f_crypto12HaHh8uvyanYB" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `_RNxC8f_crypto12HbNWOuN1Xvlt`**: at every fuel, with the stack bound. -/
theorem correct_stack_22 : StackBound.StackStmt input "_RNxC8f_crypto12HbNWOuN1Xvlt" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `_RNxC8f_crypto12HbZpZjoAalHX`**: at every fuel, with the stack bound. -/
theorem correct_stack_23 : StackBound.StackStmt input "_RNxC8f_crypto12HbZpZjoAalHX" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `__fv_37189324023f__RNxC8f_crypto12HcKxZ5WAz64I`**: at every fuel, with the stack bound. -/
theorem correct_stack_24 : StackBound.StackStmt input "__fv_37189324023f__RNxC8f_crypto12HcKxZ5WAz64I" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `__fv_37189324023f__RNxC8f_crypto12HekqC08LoBdF`**: at every fuel, with the stack bound. -/
theorem correct_stack_25 : StackBound.StackStmt input "__fv_37189324023f__RNxC8f_crypto12HekqC08LoBdF" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `__fv_37189324023f__RNxC8f_crypto12HfgeW0Z2oBsQ`**: at every fuel, with the stack bound. -/
theorem correct_stack_26 : StackBound.StackStmt input "__fv_37189324023f__RNxC8f_crypto12HfgeW0Z2oBsQ" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `_RNxC8f_crypto12HgIwETO0I2ur`**: at every fuel, with the stack bound. -/
theorem correct_stack_27 : StackBound.StackStmt input "_RNxC8f_crypto12HgIwETO0I2ur" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `__fv_37189324023f__RNxC8f_crypto12Hgbng4aFzSom`**: at every fuel, with the stack bound. -/
theorem correct_stack_28 : StackBound.StackStmt input "__fv_37189324023f__RNxC8f_crypto12Hgbng4aFzSom" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `__fv_37189324023f__RNxC8f_crypto12HghN5Rmlyi4q`**: at every fuel, with the stack bound. -/
theorem correct_stack_29 : StackBound.StackStmt input "__fv_37189324023f__RNxC8f_crypto12HghN5Rmlyi4q" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `_RNxC8f_crypto12HhiXAjCKBW7w`**: at every fuel, with the stack bound. -/
theorem correct_stack_30 : StackBound.StackStmt input "_RNxC8f_crypto12HhiXAjCKBW7w" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `__fv_37189324023f__RNxC8f_crypto12Hi5p372B4x00`**: at every fuel, with the stack bound. -/
theorem correct_stack_31 : StackBound.StackStmt input "__fv_37189324023f__RNxC8f_crypto12Hi5p372B4x00" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `_RNxC8f_crypto12HimYCq6Bwri1`**: at every fuel, with the stack bound. -/
theorem correct_stack_32 : StackBound.StackStmt input "_RNxC8f_crypto12HimYCq6Bwri1" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `_RNxC8f_crypto12HkTIWOU3z2ty`**: at every fuel, with the stack bound. -/
theorem correct_stack_33 : StackBound.StackStmt input "_RNxC8f_crypto12HkTIWOU3z2ty" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `_RNxC8f_crypto12HkqwaGP8eNcF`**: at every fuel, with the stack bound. -/
theorem correct_stack_34 : StackBound.StackStmt input "_RNxC8f_crypto12HkqwaGP8eNcF" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `__fv_37189324023f__RNxC8f_crypto12HkrKt9FxX5Uv`**: at every fuel, with the stack bound. -/
theorem correct_stack_35 : StackBound.StackStmt input "__fv_37189324023f__RNxC8f_crypto12HkrKt9FxX5Uv" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `chacha20_block`**: at every fuel, with the stack bound. -/
theorem correct_stack_36 : StackBound.StackStmt input "chacha20_block" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `chacha_quarter_round`**: at every fuel, with the stack bound. -/
theorem correct_stack_37 : StackBound.StackStmt input "chacha_quarter_round" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `ct_eq`**: at every fuel, with the stack bound. -/
theorem correct_stack_38 : StackBound.StackStmt input "ct_eq" :=
  StackBound.crate_correct_stack okB_input stack_ok _

/-- **`backend_correct_program_stack` for `sha256_compress`**: at every fuel, with the stack bound. -/
theorem correct_stack_39 : StackBound.StackStmt input "sha256_compress" :=
  StackBound.crate_correct_stack okB_input stack_ok _

end Crates.FCrypto
