import Crates.HDynGeneric.Slice0
import Crates.HDynGeneric.Slice1

/-! # Crate-level instance of `backend_correct_program` (generated)

Generated by `cargo fv link-proof` / `lake exe link-check` (docs/contracts/e2e.md,
"Crate-level instance") for the executable

  /home/kev/work/clifv-wt/crate-check/examples/survey/target/fv/plain/aarch64-unknown-linux-musl/debug/build/h_dyn_generic/0cd9cf5acd1981ba/out/values-0cd9cf5acd1981ba

The program `P` is the 43 functions of `input` (the CLIF `lean-backend` compiled, with the
link's symbol names, and `lean-regalloc`'s output), loaded at their addresses in the
executable's link map (`addrs`). `okB_input` decides every premise of `LinkSys.Ok` about the
program and its layout by `native_decide` (`okB_of`: the program's checks, `globalB_input`, and
the per-function checks by slices of 32 functions, `sliceK_ok`, each in its own module), run as compiled
code (the package `crate-proofs` loads the shared library of `FV.E2E.LinkCheck`); `link_ok` is
`LinkSys.Ok` of the crate's linked system for every base environment satisfying the base
premises (`BaseOk`: the contracts of std, other crates' code and the runtime, which stay
premises), and the `correct_*` theorems are `backend_correct_program` for the entries.
-/

namespace Crates.HDynGeneric

open E2E E2E.LinkCheck

/-- The checks of the program (`globalChks`). -/
theorem globalB_input : globalB input = true := by native_decide

/-- Every premise of `LinkSys.Ok` about the program and its layout. -/
theorem okB_input : okB input = true :=
  okB_of globalB_input (by
    show fnsB input (slice0 ++ slice1) = true
    simp only [fnsB_append, slice0_ok, slice1_ok, Bool.and_self])

/-- **`LinkSys.Ok` of the crate's linked system**, for every base environment satisfying the base
premises and every `F` containing the code. -/
theorem link_ok (B : BaseEnv) (F : BitVec 64 → Prop) (hB : BaseOk (LinkSys.ofInput input B F))
    (hF : ∀ a, (LinkSys.ofInput input B F).Img a → F a) : (LinkSys.ofInput input B F).Ok :=
  okB_sound okB_input hB hF

/-- No function has a `tls_value`. -/
theorem noTls : (progOf input.results).funcs.all (fun g => !Backend.hasTls g) = true := by
  native_decide

/-- **The base premises are satisfiable**: the closed base environment (`closedBase`: nothing
outside the program has a semantics) satisfies them, so `link_ok` and the `correct_*` theorems
are not vacuous in their base premises. -/
theorem base_closed (F : BitVec 64 → Prop) : BaseOk (LinkSys.ofInput input closedBase F) :=
  baseOk_closed fun g hg => by simpa using List.all_eq_true.1 noTls g hg

/-- The entries are functions of the program. -/
theorem entries_present :
    ["__fv_d894d4c3f88e__RNvMs6_NtCsazjiGSRkgVH_4core3numm11rotate_left", "__fv_d894d4c3f88e__RNvMs6_NtCsazjiGSRkgVH_4core3numm12wrapping_mul", "__fv_d894d4c3f88e__RNvMs7_NtCsazjiGSRkgVH_4core3numy12wrapping_add", "__fv_d894d4c3f88e__RNvMs7_NtCsazjiGSRkgVH_4core3numy12wrapping_mul", "_RNxC13h_dyn_generic11HN6Xx0RJjNG", "_RNxC13h_dyn_generic11HQvgjuNdzXd", "_RNxC13h_dyn_generic12H3GPtIT8Zs5B", "_RNxC13h_dyn_generic12H3j0Tjpru3GD", "_RNxC13h_dyn_generic12H3qutJ7nkORW", "__fv_d894d4c3f88e__RNxC13h_dyn_generic12H45rxnXEEpfr", "_RNxC13h_dyn_generic12H4U9dHdj5biM", "__fv_d894d4c3f88e__RNxC13h_dyn_generic12H4hii1BNpNhV", "_RNxC13h_dyn_generic12H59BmMmHkt8y", "__fv_d894d4c3f88e__RNxC13h_dyn_generic12H5CL8YmsPAiw", "__fv_d894d4c3f88e__RNxC13h_dyn_generic12H5hs7eUIIDjG", "_RNxC13h_dyn_generic12H6TRWZKHpQUL", "_RNxC13h_dyn_generic12H6bmPwWsY2Dd", "_RNxC13h_dyn_generic12H7D4ZMc9NR4C", "__fv_d894d4c3f88e__RNxC13h_dyn_generic12H7gUKaLj9lqi", "__fv_d894d4c3f88e__RNxC13h_dyn_generic12H8uk2XYm38DM", "_RNxC13h_dyn_generic12H97cb1VQkHME", "_RNxC13h_dyn_generic12HaHtjcZ4hgKT", "_RNxC13h_dyn_generic12HamAMOxBiYRp", "__fv_d894d4c3f88e__RNxC13h_dyn_generic12HcSrJ7KlAAsC", "_RNxC13h_dyn_generic12HeZMne786IV1", "_RNxC13h_dyn_generic12HfNH66ApBGlO", "__fv_d894d4c3f88e__RNxC13h_dyn_generic12HglEnLFzcUSY", "_RNxC13h_dyn_generic12HgmpHoCPvg2W", "_RNxC13h_dyn_generic12HgpskFWGXXuk", "__fv_d894d4c3f88e__RNxC13h_dyn_generic12Hgt37S96dUsX", "_RNxC13h_dyn_generic12HiWHXuWiEPM9", "_RNxC13h_dyn_generic12Hj7ArVpND0y9", "__fv_d894d4c3f88e__RNxC13h_dyn_generic12Hk0HoylcV1dH", "_RNxC13h_dyn_generic12HkQG5gCPBdy0", "closure_dyn", "closure_generic", "dyn_hash", "dyn_pick", "fn_ptr", "fn_ptr_table", "generic_fnv", "generic_xor", "total_area"].all
      (fun n => ((progOf input.results).func? n).isSome) = true := by native_decide

/-- **`backend_correct_program` for `__fv_d894d4c3f88e__RNvMs6_NtCsazjiGSRkgVH_4core3numm11rotate_left`** -/
theorem correct_0 : CrateStmt input "__fv_d894d4c3f88e__RNvMs6_NtCsazjiGSRkgVH_4core3numm11rotate_left" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_d894d4c3f88e__RNvMs6_NtCsazjiGSRkgVH_4core3numm12wrapping_mul`** -/
theorem correct_1 : CrateStmt input "__fv_d894d4c3f88e__RNvMs6_NtCsazjiGSRkgVH_4core3numm12wrapping_mul" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_d894d4c3f88e__RNvMs7_NtCsazjiGSRkgVH_4core3numy12wrapping_add`** -/
theorem correct_2 : CrateStmt input "__fv_d894d4c3f88e__RNvMs7_NtCsazjiGSRkgVH_4core3numy12wrapping_add" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_d894d4c3f88e__RNvMs7_NtCsazjiGSRkgVH_4core3numy12wrapping_mul`** -/
theorem correct_3 : CrateStmt input "__fv_d894d4c3f88e__RNvMs7_NtCsazjiGSRkgVH_4core3numy12wrapping_mul" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC13h_dyn_generic11HN6Xx0RJjNG`** -/
theorem correct_4 : CrateStmt input "_RNxC13h_dyn_generic11HN6Xx0RJjNG" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC13h_dyn_generic11HQvgjuNdzXd`** -/
theorem correct_5 : CrateStmt input "_RNxC13h_dyn_generic11HQvgjuNdzXd" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC13h_dyn_generic12H3GPtIT8Zs5B`** -/
theorem correct_6 : CrateStmt input "_RNxC13h_dyn_generic12H3GPtIT8Zs5B" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC13h_dyn_generic12H3j0Tjpru3GD`** -/
theorem correct_7 : CrateStmt input "_RNxC13h_dyn_generic12H3j0Tjpru3GD" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC13h_dyn_generic12H3qutJ7nkORW`** -/
theorem correct_8 : CrateStmt input "_RNxC13h_dyn_generic12H3qutJ7nkORW" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_d894d4c3f88e__RNxC13h_dyn_generic12H45rxnXEEpfr`** -/
theorem correct_9 : CrateStmt input "__fv_d894d4c3f88e__RNxC13h_dyn_generic12H45rxnXEEpfr" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC13h_dyn_generic12H4U9dHdj5biM`** -/
theorem correct_10 : CrateStmt input "_RNxC13h_dyn_generic12H4U9dHdj5biM" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_d894d4c3f88e__RNxC13h_dyn_generic12H4hii1BNpNhV`** -/
theorem correct_11 : CrateStmt input "__fv_d894d4c3f88e__RNxC13h_dyn_generic12H4hii1BNpNhV" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC13h_dyn_generic12H59BmMmHkt8y`** -/
theorem correct_12 : CrateStmt input "_RNxC13h_dyn_generic12H59BmMmHkt8y" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_d894d4c3f88e__RNxC13h_dyn_generic12H5CL8YmsPAiw`** -/
theorem correct_13 : CrateStmt input "__fv_d894d4c3f88e__RNxC13h_dyn_generic12H5CL8YmsPAiw" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_d894d4c3f88e__RNxC13h_dyn_generic12H5hs7eUIIDjG`** -/
theorem correct_14 : CrateStmt input "__fv_d894d4c3f88e__RNxC13h_dyn_generic12H5hs7eUIIDjG" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC13h_dyn_generic12H6TRWZKHpQUL`** -/
theorem correct_15 : CrateStmt input "_RNxC13h_dyn_generic12H6TRWZKHpQUL" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC13h_dyn_generic12H6bmPwWsY2Dd`** -/
theorem correct_16 : CrateStmt input "_RNxC13h_dyn_generic12H6bmPwWsY2Dd" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC13h_dyn_generic12H7D4ZMc9NR4C`** -/
theorem correct_17 : CrateStmt input "_RNxC13h_dyn_generic12H7D4ZMc9NR4C" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_d894d4c3f88e__RNxC13h_dyn_generic12H7gUKaLj9lqi`** -/
theorem correct_18 : CrateStmt input "__fv_d894d4c3f88e__RNxC13h_dyn_generic12H7gUKaLj9lqi" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_d894d4c3f88e__RNxC13h_dyn_generic12H8uk2XYm38DM`** -/
theorem correct_19 : CrateStmt input "__fv_d894d4c3f88e__RNxC13h_dyn_generic12H8uk2XYm38DM" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC13h_dyn_generic12H97cb1VQkHME`** -/
theorem correct_20 : CrateStmt input "_RNxC13h_dyn_generic12H97cb1VQkHME" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC13h_dyn_generic12HaHtjcZ4hgKT`** -/
theorem correct_21 : CrateStmt input "_RNxC13h_dyn_generic12HaHtjcZ4hgKT" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC13h_dyn_generic12HamAMOxBiYRp`** -/
theorem correct_22 : CrateStmt input "_RNxC13h_dyn_generic12HamAMOxBiYRp" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_d894d4c3f88e__RNxC13h_dyn_generic12HcSrJ7KlAAsC`** -/
theorem correct_23 : CrateStmt input "__fv_d894d4c3f88e__RNxC13h_dyn_generic12HcSrJ7KlAAsC" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC13h_dyn_generic12HeZMne786IV1`** -/
theorem correct_24 : CrateStmt input "_RNxC13h_dyn_generic12HeZMne786IV1" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC13h_dyn_generic12HfNH66ApBGlO`** -/
theorem correct_25 : CrateStmt input "_RNxC13h_dyn_generic12HfNH66ApBGlO" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_d894d4c3f88e__RNxC13h_dyn_generic12HglEnLFzcUSY`** -/
theorem correct_26 : CrateStmt input "__fv_d894d4c3f88e__RNxC13h_dyn_generic12HglEnLFzcUSY" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC13h_dyn_generic12HgmpHoCPvg2W`** -/
theorem correct_27 : CrateStmt input "_RNxC13h_dyn_generic12HgmpHoCPvg2W" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC13h_dyn_generic12HgpskFWGXXuk`** -/
theorem correct_28 : CrateStmt input "_RNxC13h_dyn_generic12HgpskFWGXXuk" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_d894d4c3f88e__RNxC13h_dyn_generic12Hgt37S96dUsX`** -/
theorem correct_29 : CrateStmt input "__fv_d894d4c3f88e__RNxC13h_dyn_generic12Hgt37S96dUsX" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC13h_dyn_generic12HiWHXuWiEPM9`** -/
theorem correct_30 : CrateStmt input "_RNxC13h_dyn_generic12HiWHXuWiEPM9" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC13h_dyn_generic12Hj7ArVpND0y9`** -/
theorem correct_31 : CrateStmt input "_RNxC13h_dyn_generic12Hj7ArVpND0y9" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `__fv_d894d4c3f88e__RNxC13h_dyn_generic12Hk0HoylcV1dH`** -/
theorem correct_32 : CrateStmt input "__fv_d894d4c3f88e__RNxC13h_dyn_generic12Hk0HoylcV1dH" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `_RNxC13h_dyn_generic12HkQG5gCPBdy0`** -/
theorem correct_33 : CrateStmt input "_RNxC13h_dyn_generic12HkQG5gCPBdy0" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `closure_dyn`** -/
theorem correct_34 : CrateStmt input "closure_dyn" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `closure_generic`** -/
theorem correct_35 : CrateStmt input "closure_generic" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `dyn_hash`** -/
theorem correct_36 : CrateStmt input "dyn_hash" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `dyn_pick`** -/
theorem correct_37 : CrateStmt input "dyn_pick" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `fn_ptr`** -/
theorem correct_38 : CrateStmt input "fn_ptr" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `fn_ptr_table`** -/
theorem correct_39 : CrateStmt input "fn_ptr_table" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `generic_fnv`** -/
theorem correct_40 : CrateStmt input "generic_fnv" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `generic_xor`** -/
theorem correct_41 : CrateStmt input "generic_xor" :=
  crate_correct okB_input _

/-- **`backend_correct_program` for `total_area`** -/
theorem correct_42 : CrateStmt input "total_area" :=
  crate_correct okB_input _

end Crates.HDynGeneric
