import FV.Backend.Proof.IselSzDefs
import FV.Backend.Proof.IselCovTab

/-!
# Generator of the V6c size cost table (`FV/Backend/Proof/IselSzTab.lean`)

Untrusted: computes, by a fixpoint over the entries of V3's value table `covTab`, the weight
(`cRule`, `IselSzDefs`) every entry's rules emit, drops the entries without a bound (those
reaching a `Call`/`CallInd`/`JTSequence` `emit` or `gen_call_args`, used only by the
hand-checked rules), and writes `IselSzTab.lean`: the cost table as Lean literals and the
`native_decide` checks (`chkCost` and the root checks) the proofs rely on. Prints the root costs
and failures.

Regenerate (from the repository root, after `lake build FV.Backend.Proof.IselSzDefs
FV.Backend.Proof.IselCovTab`):

    lake env lean --run FVTest/Backend/IselSzGen.lean FV/Backend/Proof/IselSzTab.lean
-/

open Isle Isle.Aarch64 Isle.Interp Backend Backend.Proof Backend.Proof.Cov Backend.Proof.Driver

namespace SzGen

def costOf (aw : TermId → List AW → Option Nat) (ctab : CTab) (ins : List AW) (t : TermId) : Option Nat :=
  (program.rulesOf t).foldl (fun acc r => match acc, cRule program covTab aw ctab aext actor apre aOracle ins r with
    | some a, some c => some (max a c)
    | _, _ => none) (some 0)

/-- One round: recompute every entry's cost with the current table; drop the unbounded ones. -/
def round (aw : TermId → List AW → Option Nat) (ctab : CTab) : CTab :=
  ctab.filterMap fun (t, ins, _) => (costOf aw ctab ins t).map fun c => (t, ins, c)

partial def fix (aw : TermId → List AW → Option Nat) (n : Nat) (ctab : CTab) : Nat × CTab :=
  let c' := round aw ctab
  if c' == ctab || n == 0 then (n, c') else fix aw (n - 1) c'

def handStmt : List Nat := [1031, 1032, 1033]
def handBranch : List Nat := [1034, 1035, 1036, 1140]

def stmtRules : List Rule := (program.rulesOf TId.lower).filter fun r =>
  closureRootIds.contains r.id && !handStmt.contains r.id
def termRules : List Rule := (program.rulesOf TId.lower).filter fun r => r.id == 964 || r.id == 1037
def branchRules : List Rule := (program.rulesOf TId.lower_branch).filter fun r => !handBranch.contains r.id

def ctyLit : CTy → String
  | .invalid => ".invalid" | .int n => s!"(.int {n})" | .float n => s!"(.float {n})"
  | .vec a b c => s!"(.vec {a} {b} {c})"

def szLit : OperandSize → String | .size32 => ".size32" | .size64 => ".size64"

def nkLit : NK → String
  | .int => "int" | .imm12 => "imm12" | .immShift => "immShift" | .uimm5 => "uimm5"
  | .uimm6 => "uimm6" | .shiftAmt => "shiftAmt" | .mwc => "mwc" | .callInfo => "callInfo"

partial def awLit : AW → String
  | .bot => ".bot" | .flat m c => s!"(.flat {m} {c})" | .reg m => s!"(.reg {m})"
  | .ty ts => s!"(.ty [{", ".intercalate (ts.map ctyLit)}])"
  | .bool b => s!"(.bool {b})" | .logic s => s!"(.logic {szLit s})" | .scale b => s!"(.scale {b})"
  | .simm9 => ".simm9"
  | .xv e => match e with | .inst => "(.xv .inst)" | .data => "(.xv .data)" | .value => "(.xv .value)"
  | .alts as => s!"(.alts [{", ".intercalate (as.map awLit)}])"
  | .data t k fs => s!"(.data {t} {k} [{", ".intercalate (fs.map awLit)}])"
  | .num k b => s!"(.num .{nkLit k} {b})"

def entryLit (e : TermId × List AW × Nat) : String :=
  s!"({e.1}, [{", ".intercalate (e.2.1.map awLit)}], {e.2.2})"

def chunk : Nat := 60

def header : String := "import FV.Backend.Proof.IselSzDefs
import FV.Backend.Proof.IselCovTab

/-!
# The size of the ISLE lowering's output (V6c): the cost table

GENERATED by `FVTest/Backend/IselSzGen.lean` (untrusted; regenerate with
`lake env lean --run FVTest/Backend/IselSzGen.lean FV/Backend/Proof/IselSzTab.lean`).
Do not edit by hand.

`szCTab`: per entry of V3's value table `covTab` whose rules have a bound, the weight they emit.
`szCTab_ok`: every rule of every entry checks (`chkCost` over `covTab` with V3's `aext`,
`actor`, `apre`, `aOracle`); `szStmt_ok`/`szTerm_ok`/`szBranch_ok`: the roots other than the
hand-checked call and `br_table` rules emit at most `szStmtK`/`szTermK`. All are decided once
over the exported rule data.
-/

namespace Backend.Proof.Cov

open Backend Backend.Proof Backend.Proof.Driver Isle Isle.Aarch64

"

def renderTab (nm : String) (awn : String) (tab : CTab) : String := Id.run do
  let n := (tab.length + chunk - 1) / chunk
  let mut out := ""
  for k in [0:n] do
    let es := (tab.drop (k * chunk)).take chunk
    out := out ++ s!"/-- Chunk {k} of the cost table `{nm}`. -/\ndef {nm}{k} : CTab := [\n  " ++
      ",\n  ".intercalate (es.map entryLit) ++ "]\n\n"
  out := out ++ s!"/-- **The cost table `{nm}`** (extern costs `{awn}`). -/\ndef {nm} : CTab :=\n  " ++
    " ++ ".intercalate ((List.range n).map (s!"{nm}{·}")) ++ "\n\n"
  out := out ++ s!"/-- `chkCost`'s test of one entry of `{nm}`. -/\nabbrev {nm}EntryOk (e : TermId × List AW × Nat) : Bool :=\n  (program.rulesOf e.1).all (cRuleLe program covTab {awn} {nm} aext actor apre aOracle e.2.1 e.2.2)\n\n"
  for k in [0:n] do
    out := out ++ s!"theorem {nm}{k}_ok : ({nm}{k}).all {nm}EntryOk = true := by native_decide\n\n"
  out := out ++ s!"/-- **Every rule of every entry of `{nm}` checks.** -/\ntheorem {nm}_ok : chkCost program covTab {awn} {nm} aext actor apre aOracle = true := by\n  unfold chkCost\n  show ({nm}).all {nm}EntryOk = true\n  simp only [{nm}, List.all_append, " ++
    ", ".intercalate ((List.range n).map (s!"{nm}{·}_ok")) ++ ", Bool.and_self]\n\n"
  return out

def render (tab tgt : CTab) : String :=
  header ++ renderTab "szCTab" "actorW" tab ++ renderTab "tgCTab" "actorT" tgt ++
"/-- The closure roots of `lower` other than the call rules (1031–1033) emit at most `szStmtK`. -/
theorem szStmt_ok : (program.rulesOf TId.lower).all (fun r => !closureRootIds.contains r.id ||
    r.id == 1031 || r.id == 1032 || r.id == 1033 ||
    cRuleLe program covTab actorW szCTab aext actor apre aOracle [.xv .inst] szStmtK r) = true := by native_decide

/-- The terminator rules of `lower` (964 `trap`, 1037 `return`) emit at most `szTermK`. -/
theorem szTerm_ok : (program.rulesOf TId.lower).all (fun r => !(r.id == 964 || r.id == 1037) ||
    cRuleLe program covTab actorW szCTab aext actor apre aOracle [.c0] szTermK r) = true := by native_decide

/-- The rules of `lower_branch` other than the `try_call` (1034–1036) and `br_table` (1140)
rules emit at most `szTermK`. -/
theorem szBranch_ok : (program.rulesOf TId.lower_branch).all (fun r =>
    r.id == 1034 || r.id == 1035 || r.id == 1036 || r.id == 1140 ||
    cRuleLe program covTab actorW szCTab aext actor apre aOracle [.c0, .c0] szTermK r) = true := by native_decide

/-- The closure roots of `lower` emit at most `tgStmtK` branch targets. -/
theorem tgStmt_ok : (program.rulesOf TId.lower).all (fun r => !closureRootIds.contains r.id ||
    cRuleLe program covTab actorT tgCTab aext actor apre aOracle [.xv .inst] tgStmtK r) = true := by native_decide

/-- The terminator rules of `lower` (964 `trap`, 1037 `return`) emit at most `tgTermK` branch targets. -/
theorem tgTerm_ok : (program.rulesOf TId.lower).all (fun r => !(r.id == 964 || r.id == 1037) ||
    cRuleLe program covTab actorT tgCTab aext actor apre aOracle [.c0] tgTermK r) = true := by native_decide

/-- The rules of `lower_branch` other than the `br_table` rule (1140) emit at most `tgTermK`
branch targets. -/
theorem tgBranch_ok : (program.rulesOf TId.lower_branch).all (fun r => r.id == 1140 ||
    cRuleLe program covTab actorT tgCTab aext actor apre aOracle [.c0, .c0] tgTermK r) = true := by native_decide

end Backend.Proof.Cov
"

end SzGen

open SzGen in
def run (nm : String) (aw : TermId → List AW → Option Nat) (hS hB : List Nat) : IO CTab := do
  let init : CTab := covTab.map fun (t, ins, _) => (t, ins, 0)
  let (left, tab) := fix aw 500 init
  IO.println s!"[{nm}] covTab {covTab.length} entries, cost table {tab.length} (fuel left {left})"
  let dropped := covTab.filter fun (t, ins, _) => !tab.any fun e => e.1 == t && e.2.1 == ins
  for (t, _, _) in dropped do IO.println s!"  dropped: {program.termName t}"
  IO.println s!"  max entry cost {tab.foldl (fun m e => max m e.2.2) 0}"
  let report (rn : String) (ins : List AW) (rs : List Rule) : IO Unit := do
    let mut m := 0
    for r in rs do
      match cRule program covTab aw tab aext actor apre aOracle ins r with
      | some c => m := max m c
      | none => IO.println s!"  {rn} root {r.id} {r.name}: no bound"
    IO.println s!"  {rn}: max {m}"
  report "stmt" [.xv .inst] ((program.rulesOf TId.lower).filter fun r => closureRootIds.contains r.id && !hS.contains r.id)
  report "term" [.c0] termRules
  report "branch" [.c0, .c0] ((program.rulesOf TId.lower_branch).filter fun r => !hB.contains r.id)
  pure tab

def main (args : List String) : IO Unit := do
  let tab ← run "weight" actorW SzGen.handStmt SzGen.handBranch
  let tgt ← run "targets" actorT [] [1140]
  match args with
  | [path] => IO.FS.writeFile path (SzGen.render tab tgt); IO.println s!"wrote {path}"
  | _ => pure ()
