import FV.E2E.LinkCheck

/-!
# `lake exe link-check <dir> [--lean FILE --module NAME] [--entries a,b,…] [--prune]`

Evaluates the checker `E2E.LinkCheck.okB` (every premise of `LinkSys.Ok` about the program and
its layout, `FV/E2E/LinkCheck.lean`) on the input of a crate-level instance written by
`cargo fv link-proof` (docs/USAGE.md, "Proving a crate"): `<dir>/link.json` lists the functions
(`fns/<i>.clif`, the CLIF `lean-backend` compiled, with the link's symbol names, and
`fns/<i>.ra.json`, `lean-regalloc`'s output for it) and the link-map addresses (`addrs`).

It completes the input (the CLIF image's symbols `syms`: every `symbol` global value and
`func_addr` target of the functions, at its link-map address; `D`: the largest frame of a
function; `raStar = 8`) and prints the failing checks per function and premise (`diagR`, the
diagnostic version of `okB`), then a count per premise. With `--prune` it drops the failing
functions (they become externs of the base environment) until the rest passes. With `--lean` it
writes, when the checks pass, the Lean file that proves `LinkSys.Ok` of the crate by
`native_decide` on `okB` and states `backend_correct_program` for the entries (default: every
function): the proof does not trust this executable.

Exit status: 0 iff the (pruned) input passes.
-/

open E2E E2E.LinkCheck Lean

/-- The names a function's CLIF takes the address of: its `symbol` global values and its
`func_addr` targets. -/
def addrNames (f : Clif.Function) : List String :=
  f.globals.filterMap (fun g => match g.2 with | .symbol n _ _ => some n | _ => none) ++
  f.blocks.flatMap fun b => b.body.filterMap fun st => match st.inst with
    | .funcAddr _ fn => (f.extern? fn).map (·.name)
    | _ => none

/-- A Lean string literal. -/
def leanStr (s : String) : String :=
  "\"" ++ String.join (s.toList.map fun c =>
    if c == '"' then "\\\"" else if c == '\\' then "\\\\"
    else if c == '\n' then "\\n" else if c == '\t' then "\\t"
    else if c.toNat < 0x20 then s!"\\x{(Nat.toDigits 16 c.toNat).asString}" else c.toString) ++ "\""

def usage : String :=
  "usage: link-check <dir> [--lean FILE.lean --module NAME] [--entries a,b,…] [--prune]"

structure Opts where
  dir : String
  lean : Option String := none
  module : String := "Crate"
  entries : Option (List String) := none
  prune : Bool := false

def parseOpts : List String → Option Opts → Option Opts
  | [], o => o
  | "--lean" :: f :: rest, some o => parseOpts rest (some { o with lean := some f })
  | "--module" :: m :: rest, some o => parseOpts rest (some { o with module := m })
  | "--entries" :: e :: rest, some o =>
    parseOpts rest (some { o with entries := some ((e.splitOn ",").filter (· ≠ "")) })
  | "--prune" :: rest, some o => parseOpts rest (some { o with prune := true })
  | d :: rest, none => parseOpts rest (some { dir := d })
  | _, _ => none

/-- The generated Lean file. -/
def leanFile (I : LinkInput) (names : List String) (entries : List String) (module exe : String)
    (noTls : Bool) : String := Id.run do
  let closedText := "/-- No function has a `tls_value`. -/
theorem noTls : (progOf input.results).funcs.all (fun g => !Backend.hasTls g) = true := by
  native_decide

/-- **The base premises are satisfiable**: the closed base environment (`closedBase`: nothing
outside the program has a semantics) satisfies them, so `link_ok` and the `correct_*` theorems
are not vacuous in their base premises. -/
theorem base_closed (F : BitVec 64 → Prop) : BaseOk (LinkSys.ofInput input closedBase F) :=
  baseOk_closed fun g hg => by simpa using List.all_eq_true.1 noTls g hg

"
  let mut s := s!"import FV.E2E.LinkCheck

/-! # Crate-level instance of `backend_correct_program` (generated)

Generated by `cargo fv link-proof` / `lake exe link-check` (docs/contracts/e2e.md,
\"Crate-level instance\") for the executable

  {exe}

The program `P` is the {I.funcs.length} functions below (the CLIF `lean-backend` compiled, with the
link's symbol names, and `lean-regalloc`'s output), loaded at their addresses in the
executable's link map (`addrs`). `okB_input` decides every premise of `LinkSys.Ok` about the
program and its layout by `native_decide`; `link_ok` is `LinkSys.Ok` of the crate's linked
system for every base environment satisfying the base premises (`BaseOk`: the contracts of
std, other crates' code and the runtime, which stay premises), and the `correct_*` theorems are
`backend_correct_program` for the entries.
-/

namespace Crates.{module}

open E2E E2E.LinkCheck

"
  for (fi, i) in I.funcs.zipIdx do
    s := s ++ s!"/-- `{names[i]!}` -/\ndef fn{i} : FnInput where\n  clif := {leanStr fi.clif}\n  ra := {leanStr fi.ra}\n\n"
  let fns := ", ".intercalate ((List.range I.funcs.length).map (s!"fn{·}"))
  let pairs (l : List (String × Nat)) := ",\n    ".intercalate (l.map fun p => s!"({leanStr p.1}, {p.2})")
  s := s ++ s!"/-- The crate's input. -/
def input : LinkInput where
  funcs := [{fns}]
  addrs := [
    {pairs I.addrs}]
  syms := [
    {pairs I.syms}]
  raStar := {I.raStar}
  D := {I.D}

/-- Every premise of `LinkSys.Ok` about the program and its layout. -/
theorem okB_input : okB input = true := by native_decide

/-- **`LinkSys.Ok` of the crate's linked system**, for every base environment satisfying the base
premises and every `F` containing the code. -/
theorem link_ok (B : BaseEnv) (F : BitVec 64 → Prop) (hB : BaseOk (LinkSys.ofInput input B F))
    (hF : ∀ a, (LinkSys.ofInput input B F).Img a → F a) : (LinkSys.ofInput input B F).Ok :=
  okB_sound okB_input hB hF

{if noTls then closedText else ""}/-- The entries are functions of the program. -/
theorem entries_present :
    [{", ".intercalate (entries.map leanStr)}].all
      (fun n => ((progOf input.results).func? n).isSome) = true := by native_decide

"
  for (n, i) in entries.zipIdx do
    s := s ++ s!"/-- **`backend_correct_program` for `{n}`** -/\ntheorem correct_{i} : CrateStmt input {leanStr n} :=\n  crate_correct okB_input _\n\n"
  s := s ++ s!"end Crates.{module}\n"
  return s

def main (args : List String) : IO UInt32 := do
  let some o := parseOpts args none | do IO.eprintln usage; return 2
  let dir : System.FilePath := o.dir
  let j ← match Json.parse (← IO.FS.readFile (dir / "link.json")) with
    | .ok j => pure j
    | .error e => do IO.eprintln s!"link-check: link.json: {e}"; return 2
  let exe := (j.getObjValAs? String "exe").toOption.getD "?"
  let fjs := ((j.getObjVal? "functions").bind (·.getArr?)).toOption.getD #[]
  let mut fis : Array FnInput := #[]
  for fj in fjs do
    let clif := (fj.getObjValAs? String "clif").toOption.getD ""
    let ra := (fj.getObjValAs? String "ra").toOption.getD ""
    fis := fis.push { clif := ← IO.FS.readFile (dir / clif), ra := ← IO.FS.readFile (dir / ra) }
  let ajs := ((j.getObjVal? "addrs").bind (·.getArr?)).toOption.getD #[]
  let addrs : List (String × Nat) := ajs.toList.filterMap fun a => do
    let arr ← a.getArr?.toOption
    let n ← (arr[0]?.bind (·.getStr?.toOption))
    let v ← (arr[1]?.bind (·.getNat?.toOption))
    pure (n, v)
  let I0 : LinkInput := { funcs := fis.toList, addrs, syms := [], raStar := 8, D := 0 }
  let t0 ← IO.monoMsNow
  let R0 := I0.results
  -- the CLIF image's symbols and the call-level stack
  let mut keep := R0
  let mut dropped : List (String × List String) := []
  let mut d := diagR I0 []
  let mut I := I0
  repeat
    let names := ((keep.flatMap fun e => addrNames e.1).eraseDups)
    let syms := names.filterMap fun n => (I0.addrs.lookup n).map (n, ·)
    let D := (keep.map fun e => frameDrop (getOk e.2).af).foldl max 0
    I := { I0 with syms, D }
    d := diagR I keep
    let bad := d.filter (·.1 != "(program)")
    if !o.prune || bad.isEmpty then break
    dropped := dropped ++ bad
    -- and their callers in the program, so that what is left is closed under calls (no function
    -- of the crate becomes an extern of the base environment)
    let mut gone := bad.map (·.1)
    repeat
      let callers := keep.filter fun e => !gone.contains e.1.name &&
        e.1.externs.any fun x => gone.contains x.2.name
      if callers.isEmpty then break
      for e in callers do
        dropped := dropped ++ [(e.1.name, ["(calls a dropped function)"])]
      gone := gone ++ callers.map (·.1.name)
    keep := keep.filter fun e => !gone.contains e.1.name
  let ms := (← IO.monoMsNow) - t0
  -- report
  IO.println s!"link-check: {exe}"
  IO.println s!"  {R0.length} functions, {I0.addrs.length} link-map addresses, {I.syms.length} CLIF image symbols, D = {I.D}; checked in {ms} ms"
  let failing := if o.prune then dropped ++ d else d
  for (n, bs) in failing do
    IO.println s!"  FAIL {n}:"
    for b in bs do IO.println s!"      {b}"
  let mut counts : Std.HashMap String Nat := {}
  for (_, bs) in failing do
    for b in bs.eraseDups do counts := counts.insert b (counts.getD b 0 + 1)
  if !counts.isEmpty then
    IO.println "  failing premises (functions):"
    for (b, c) in counts.toList.mergeSort (fun a b => a.2 ≥ b.2) do
      IO.println s!"    {c}  {b}"
  if o.prune then
    IO.println s!"  --prune: {keep.length} of {R0.length} functions pass ({dropped.length} dropped)"
  let ok := d.isEmpty
  IO.println (if ok then "  okB: true" else "  okB: false")
  -- the Lean file
  if let some out := o.lean then
    if !ok then
      IO.eprintln "link-check: the checks fail; no Lean file written"
      return 1
    let keepNames := keep.map (·.1.name)
    let funcs := (I0.funcs.zip (R0.map (·.1.name))).filter (keepNames.contains ·.2)
    let I' : LinkInput := { I with funcs := funcs.map (·.1) }
    let entries := o.entries.getD keepNames
    let missing := entries.filter (!keepNames.contains ·)
    if !missing.isEmpty then
      IO.eprintln s!"link-check: entries not in the program: {missing}"
      return 1
    let noTls := keep.all fun e => !Backend.hasTls e.1
    IO.FS.writeFile out (leanFile I' (funcs.map (·.2)) entries o.module exe noTls)
    IO.println s!"  wrote {out} ({funcs.length} functions, {entries.length} entries)"
  return (if ok then 0 else 1)
