import FV.Clif.Syntax

/-!
# The mid-end's extern Rust helpers, in Lean

Lean transcriptions of the Rust functions behind the extern constructors and extractors of
Cranelift 0.136.1's mid-end ISLE unit (`opt`) that the E closure reaches
(`Isle.Opt.Closure.rustSources` lists each function and its source line). Sources, relative to
`third_party/wasmtime/cranelift/codegen/`:

* `src/isle_prelude.rs` (`isle_common_prelude_methods!`): `Type` predicates, `Imm64`
  arithmetic, condition codes;
* `<OUT_DIR>/isle_numerics.rs`, generated by `cranelift-codegen-meta` 0.136.1
  (`gen_isle.rs`) from `numerics.isle`: `u64_*`, `i64_*`, `u32_*` arithmetic and conversions;
* `src/opts.rs` and `src/opts/div_const.rs`: `u64_bswap*`, `div_const_magic_*`;
* `src/ir/immediates.rs` (`Imm64::sign_extend_from_width`, `mask_to_width`),
  `src/ir/types.rs` (`Type::bits`, `lane_type`, `half_width`), `src/ir/condcodes.rs`
  (`IntCC::complement`, `swap_args`).

Representation: every ISLE integer (`u8`..`u128`, `i8`..`i128`) is an `Int` in the range of its
Rust type, and an `Imm64` is its `i64` payload (`Imm64::bits`). Rust panics (`assert!`,
`unwrap`, `checked_*().unwrap_or_else(panic!)`, and the arithmetic-overflow checks of a debug
build) are `Except.error` with the panic message: a panic is a compiler crash, never a rule
that does not match. Rust `Option` results are Lean `Option`s.
-/

namespace Isle.Opt

/-- A Cranelift `Type` as the mid-end rules see it (`src/ir/types.rs`): scalar integers and
floats, fixed vectors, and `INVALID`. Dynamic vectors do not occur (no rule constant names
one). -/
inductive CTy where
  | invalid
  | int (bits : Nat)
  | float (bits : Nat)
  | vec (laneBits lanes : Nat) (isFloat : Bool)
  deriving DecidableEq, Repr, Inhabited, Hashable

namespace CTy

/-- `Type::lane_type`. -/
def laneType : CTy → CTy
  | .vec lb _ f => if f then .float lb else .int lb
  | t => t

/-- `Type::lane_bits`. -/
def laneBits : CTy → Nat
  | .invalid => 0 | .int b => b | .float b => b | .vec lb _ _ => lb

/-- `Type::lane_count`. -/
def laneCount : CTy → Nat
  | .vec _ n _ => n | _ => 1

/-- `Type::bits`. -/
def bits (t : CTy) : Nat := t.laneBits * t.laneCount

/-- `Type::is_int`: `I8 I16 I32 I64 I128`. -/
def isInt : CTy → Bool
  | .int b => b == 8 || b == 16 || b == 32 || b == 64 || b == 128
  | _ => false

/-- `Type::is_float`. -/
def isFloat : CTy → Bool
  | .float _ => true | _ => false

/-- `Type::is_vector`. -/
def isVector : CTy → Bool
  | .vec .. => true | _ => false

/-- `Type::half_width`: halve the lane type (`I16 → I8` .. `I128 → I64`, `F32 → F16` ..
`F128 → F64`), keeping the lane count. -/
def halfWidth? : CTy → Option CTy
  | .int b => if b == 16 || b == 32 || b == 64 || b == 128 then some (.int (b / 2)) else none
  | .float b => if b == 32 || b == 64 || b == 128 then some (.float (b / 2)) else none
  | .vec lb n f =>
    if (!f && (lb == 16 || lb == 32 || lb == 64 || lb == 128)) ||
       (f && (lb == 32 || lb == 64 || lb == 128)) then some (.vec (lb / 2) n f) else none
  | .invalid => none

/-- The `$NAME` type constants of the prelude (`I8`, `F64`, `I32X4`, `INVALID`, ...). -/
def ofName? (s : String) : Option CTy :=
  let scalar (c : Char) (w : String) : Option CTy :=
    match w.toNat? with
    | some b =>
      if c == 'I' && (b == 8 || b == 16 || b == 32 || b == 64 || b == 128) then some (.int b)
      else if c == 'F' && (b == 16 || b == 32 || b == 64 || b == 128) then some (.float b)
      else none
    | none => none
  if s == "INVALID" then some .invalid else
  match s.toList with
  | c :: rest =>
    match (String.ofList rest).splitOn "X" with
    | [w] => scalar c w
    | [w, n] =>
      match scalar c w, n.toNat? with
      | some t, some k => if k ≥ 2 then some (.vec t.laneBits k (c == 'F')) else none
      | _, _ => none
    | _ => none
  | [] => none

def ofClif : Clif.Ty → CTy
  | .i8 => .int 8 | .i16 => .int 16 | .i32 => .int 32 | .i64 => .int 64 | .i128 => .int 128

def toClif? : CTy → Option Clif.Ty
  | .int 8 => some .i8 | .int 16 => some .i16 | .int 32 => some .i32 | .int 64 => some .i64
  | .int 128 => some .i128 | _ => none

end CTy

namespace Rust

/-- A Rust panic (compiler crash). -/
abbrev Panics := Except String

/-! ### Rust integer types (wrapping casts `as`) -/

def asU64 (i : Int) : Int := (BitVec.ofInt 64 i).toNat
def asI64 (i : Int) : Int := (BitVec.ofInt 64 i).toInt
def asU32 (i : Int) : Int := (BitVec.ofInt 32 i).toNat
def asI32 (i : Int) : Int := (BitVec.ofInt 32 i).toInt

def inU64 (i : Int) : Bool := 0 ≤ i && i < 2 ^ 64
def inU32 (i : Int) : Bool := 0 ≤ i && i < 2 ^ 32
def inI64 (i : Int) : Bool := -2 ^ 63 ≤ i && i < 2 ^ 63
def inI32 (i : Int) : Bool := -2 ^ 31 ≤ i && i < 2 ^ 31

/-- `&`, `|`, `^` on 64-bit two's-complement patterns, as a `u64`. -/
def band64 (a b : Int) : Int := (BitVec.ofInt 64 a &&& BitVec.ofInt 64 b).toNat
def bor64 (a b : Int) : Int := (BitVec.ofInt 64 a ||| BitVec.ofInt 64 b).toNat
def bxor64 (a b : Int) : Int := (BitVec.ofInt 64 a ^^^ BitVec.ofInt 64 b).toNat

/-- Rust `/` on integers (truncating). -/
def tdiv (a b : Int) : Int := a.tdiv b
/-- Rust `%` on integers (sign of the dividend). -/
def trem (a b : Int) : Int := a.tmod b

/-- `u64::leading_zeros`. -/
def clz64 (x : Int) : Nat :=
  let n := (asU64 x).toNat
  if n == 0 then 64 else 63 - n.log2
/-- `u64::trailing_zeros` / `i64::trailing_zeros` (64 for zero). -/
def ctz64 (x : Int) : Nat :=
  let n := (asU64 x).toNat
  if n == 0 then 64 else go n 0 64
where
  go (n k : Nat) : Nat → Nat
    | 0 => k
    | f + 1 => if n % 2 == 1 then k else go (n / 2) (k + 1) f
/-- `u32::trailing_zeros` (32 for zero). -/
def ctz32 (x : Int) : Nat := if asU32 x == 0 then 32 else ctz64 (asU32 x)
/-- `u64::is_power_of_two` / `u32::is_power_of_two`. -/
def isPow2 (x : Int) : Bool := x > 0 && x.toNat == 2 ^ x.toNat.log2

/-! ### `Type` helpers (`src/isle_prelude.rs`) -/

/-- `ty_mask`: `u64::MAX >> (64 - bits)`; panics for types wider than 64 bits (`expect`)
and for zero-bit types (`debug_assert_ne!`). -/
def tyMask (ty : CTy) : Panics Int :=
  if ty.bits == 0 then throw "ty_mask: zero-bit type"
  else if ty.bits > 64 then throw "ty_mask: unimplemented for > 64 bits"
  else pure (2 ^ ty.bits - 1)

/-- `ty_umax` = `ty_mask`. -/
def tyUmax := tyMask

/-- `ty_smin`: `(i64::MIN as u64) >> (64 - bits)`, as `u64`. -/
def tySmin (ty : CTy) : Panics Int :=
  if ty.bits == 0 then throw "ty_smin: zero-bit type"
  else if ty.bits > 64 then throw "ty_smin: unimplemented for > 64 bits"
  else pure (2 ^ (ty.bits - 1))

/-- `ty_smax`: `(i64::MAX as u64) >> (64 - bits)`. -/
def tySmax (ty : CTy) : Panics Int :=
  if ty.bits == 0 then throw "ty_smax: zero-bit type"
  else if ty.bits > 64 then throw "ty_smax: unimplemented for > 64 bits"
  else pure (2 ^ (ty.bits - 1) - 1)

/-- `ty_bits`: `ty.bits().try_into::<u8>().unwrap()`. -/
def tyBits (ty : CTy) : Panics Int :=
  if ty.bits < 256 then pure ty.bits else throw "ty_bits: does not fit u8"

/-- `fits_in_64`. -/
def fitsIn64 (ty : CTy) : Option CTy := if ty.bits ≤ 64 then some ty else none
/-- `ty_int_ref_scalar_64` (and `_extract`). -/
def tyIntRefScalar64 (ty : CTy) : Option CTy :=
  if ty.bits ≤ 64 && !ty.isFloat && !ty.isVector then some ty else none
/-- `ty_int`. -/
def tyInt (ty : CTy) : Option CTy := if ty.isInt then some ty else none
/-- `ty_vec128`. -/
def tyVec128 (ty : CTy) : Option CTy := if ty.isVector && ty.bits == 128 then some ty else none
/-- `ty_vector` (`src/opts.rs`). -/
def tyVector (ty : CTy) : Option CTy := if ty.isVector then some ty else none
/-- `ty_int_vec128`: an integer, or a 128-bit vector of integers. -/
def tyIntVec128 (ty : CTy) : Option CTy :=
  if ty.isInt || (ty.isVector && ty.bits == 128 && ty.laneType.isInt) then some ty else none
/-- `ty_vec128_int`. -/
def tyVec128Int (ty : CTy) : Option CTy :=
  if ty.isVector && ty.bits == 128 && ty.laneType.isInt then some ty else none
/-- `ty_vector_not_float`. -/
def tyVectorNotFloat (ty : CTy) : Option CTy :=
  if ty.isVector && !ty.laneType.isFloat then some ty else none
/-- `multi_lane`: `(lane_bits, lane_count)` of a type with more than one lane. -/
def multiLane (ty : CTy) : Option (Nat × Nat) :=
  if ty.laneCount > 1 then some (ty.laneBits, ty.laneCount) else none

/-! ### `Imm64` (`src/ir/immediates.rs`, `src/isle_prelude.rs`); an `Imm64` is its `i64` -/

/-- `Imm64::sign_extend_from_width(w)`: `(x << (64 - w)) >> (64 - w)`, identity for
`w ≥ 64`. -/
def sext (w : Nat) (x : Int) : Int := if w ≥ 64 then x else (BitVec.ofInt w x).toInt
/-- `Imm64::mask_to_width(w)`: `x & ((1 << w) - 1)`, identity for `w ≥ 64`. -/
def maskTo (w : Nat) (x : Int) : Int := if w ≥ 64 then x else (BitVec.ofInt w x).toNat

/-- `x & (ty_mask(ty) as i64)`. -/
def andMask (ty : CTy) (x : Int) : Panics Int := do
  let m ← tyMask ty
  pure (asI64 (band64 (asU64 x) m))

/-- Width assertion of the `imm64_*` helpers (`assert!(bits <= 64)`). -/
def width64 (fn : String) (ty : CTy) : Panics Nat :=
  if ty.bits ≤ 64 then pure ty.bits else throw s!"{fn}: assertion failed: bits <= 64"

def imm64Clz (ty : CTy) (a : Int) : Panics Int := do
  let b ← width64 "imm64_clz" ty
  let lz := clz64 a
  if lz < 64 - b then throw "imm64_clz: attempt to subtract with overflow"
  pure (lz - (64 - b))

def imm64Ctz (ty : CTy) (a : Int) : Panics Int := do
  let b ← width64 "imm64_ctz" ty
  pure (if asU64 a == 0 then b else ctz64 a)

def imm64Sdiv (ty : CTy) (x y : Int) : Panics (Option Int) := do
  let w ← width64 "imm64_sdiv" ty
  let x := sext w x
  let y := sext w y
  let min := sext w (asI64 (← tySmin ty))
  if x == min && y == -1 then return none
  -- `i64::checked_div`: `None` on division by zero and on `i64::MIN / -1`.
  if y == 0 || (x == -2 ^ 63 && y == -1) then return none
  pure (some (maskTo w (tdiv x y)))

def imm64Udiv (ty : CTy) (x y : Int) : Panics (Option Int) := do
  let w ← width64 "imm64_udiv" ty
  let m ← tyMask ty
  let x := band64 (asU64 x) m
  let y := band64 (asU64 y) m
  if y == 0 then return none
  pure (some (maskTo w (asI64 (tdiv x y))))

def imm64Srem (ty : CTy) (x y : Int) : Panics (Option Int) := do
  let w ← width64 "imm64_srem" ty
  let x := sext w x
  let y := sext w y
  if y == 0 || (x == -2 ^ 63 && y == -1) then return none
  pure (some (maskTo w (trem x y)))

def imm64Urem (ty : CTy) (x y : Int) : Panics (Option Int) := do
  let w ← width64 "imm64_urem" ty
  let m ← tyMask ty
  let x := band64 (asU64 x) m
  let y := band64 (asU64 y) m
  if y == 0 then return none
  pure (some (maskTo w (asI64 (trem x y))))

/-- `imm64_add` .. `imm64_neg`: an `i64` operation (wrapping), then `& ty_mask`. -/
def imm64Add (ty : CTy) (x y : Int) : Panics Int := andMask ty (x + y)
def imm64Sub (ty : CTy) (x y : Int) : Panics Int := andMask ty (x - y)
def imm64Mul (ty : CTy) (x y : Int) : Panics Int := andMask ty (x * y)
def imm64And (ty : CTy) (x y : Int) : Panics Int := andMask ty (band64 x y)
def imm64Or (ty : CTy) (x y : Int) : Panics Int := andMask ty (bor64 x y)
def imm64Xor (ty : CTy) (x y : Int) : Panics Int := andMask ty (bxor64 x y)
def imm64Not (ty : CTy) (x : Int) : Panics Int := andMask ty (-x - 1)
def imm64Neg (ty : CTy) (x : Int) : Panics Int := andMask ty (-x)

def imm64Umin (ty : CTy) (x y : Int) : Panics Int := do
  let m ← tyMask ty
  let xu := band64 (asU64 x) m
  let yu := band64 (asU64 y) m
  pure (asI64 (if xu ≤ yu then xu else yu))

def imm64Umax (ty : CTy) (x y : Int) : Panics Int := do
  let m ← tyMask ty
  let xu := band64 (asU64 x) m
  let yu := band64 (asU64 y) m
  pure (asI64 (if xu ≥ yu then xu else yu))

def imm64Smin (ty : CTy) (x y : Int) : Panics Int := do
  let w ← width64 "imm64_smin" ty
  let xs := sext w x
  let ys := sext w y
  pure (maskTo w (if xs ≤ ys then xs else ys))

def imm64Smax (ty : CTy) (x y : Int) : Panics Int := do
  let w ← width64 "imm64_smax" ty
  let xs := sext w x
  let ys := sext w y
  pure (maskTo w (if xs ≥ ys then xs else ys))

/-- `imm64_shl`: shift amount masked to `bits - 1`, `i64 <<`, then `& ty_mask`. -/
def imm64Shl (ty : CTy) (x y : Int) : Panics Int := do
  if ty.bits == 0 then throw "imm64_shl: attempt to subtract with overflow"
  let s := band64 (asU64 y) (ty.bits - 1)
  andMask ty (x * 2 ^ s.toNat)

def imm64Ushr (ty : CTy) (x y : Int) : Panics Int := do
  let m ← tyMask ty
  let x := band64 (asU64 x) m
  let s := band64 (asU64 y) (ty.bits - 1)
  pure (asI64 (x / 2 ^ s.toNat))

def imm64Sshr (ty : CTy) (x y : Int) : Panics Int := do
  let sh := 64 - ty.bits  -- `u32::checked_sub(64, bits).unwrap_or(0)`
  if ty.bits == 0 then throw "imm64_sshr: attempt to subtract with overflow"
  let x := if sh ≥ 64 then x else (BitVec.ofInt (64 - sh) x).toInt
  let s := band64 y (ty.bits - 1)
  andMask ty (x / 2 ^ s.toNat)  -- `Int./` floors: arithmetic shift right

def imm64Rotl (ty : CTy) (x y : Int) : Panics Int := do
  let b ← width64 "imm64_rotl" ty
  let m ← tyMask ty
  let x := band64 (asU64 x) m
  let s := (band64 (asU64 y) (b - 1)).toNat
  let r := if s == 0 then x else bor64 (asU64 (x * 2 ^ s)) (x / 2 ^ (b - s))
  pure (asI64 (band64 r m))

def imm64Rotr (ty : CTy) (x y : Int) : Panics Int := do
  let b ← width64 "imm64_rotr" ty
  let m ← tyMask ty
  let x := band64 (asU64 x) m
  let s := (band64 (asU64 y) (b - 1)).toNat
  let r := if s == 0 then x else bor64 (x / 2 ^ s) (asU64 (x * 2 ^ (b - s)))
  pure (asI64 (band64 r m))

/-- `i64_sextend_u64(ty, x)`: `((x as i64) << s) >> s` with `s = max(0, 64 - bits)`
(the `u32` subtraction panics for types wider than 64 bits). -/
def i64SextendU64 (ty : CTy) (x : Int) : Panics Int :=
  if ty.bits > 64 then throw "i64_sextend_u64: attempt to subtract with overflow"
  else pure (sext ty.bits (asI64 x))

/-- `i64_sextend_imm64(ty, x)` = `x.sign_extend_from_width(bits)`. -/
def i64SextendImm64 (ty : CTy) (x : Int) : Int := sext ty.bits x

/-- `u64_uextend_imm64(ty, x)` = `(x as u64) & ty_mask(ty)`. -/
def u64UextendImm64 (ty : CTy) (x : Int) : Panics Int := do
  pure (band64 (asU64 x) (← tyMask ty))

/-- `checked_add_with_type(ty, a, b)`: `a + b` if it does not overflow `u64` and fits in
`ty_mask(ty)`. -/
def checkedAddWithType (ty : CTy) (a b : Int) : Panics (Option Int) := do
  let c := a + b
  if c ≥ 2 ^ 64 then return none
  let m ← tyMask ty
  pure (if band64 c (asU64 (-m - 1)) == 0 then some c else none)

/-- `imm64_power_of_two`: the exponent if the `i64` is a non-negative power of two. -/
def imm64PowerOfTwo (x : Int) : Option Int :=
  if x ≥ 0 && isPow2 x then some (ctz64 x) else none

/-- `imm64_masked(ty, x)` = `Imm64::new((x & ty_mask(ty)) as i64)`. -/
def imm64Masked (ty : CTy) (x : Int) : Panics Int := do
  pure (asI64 (band64 x (← tyMask ty)))

/-! ### Condition codes (`src/ir/condcodes.rs`, `src/isle_prelude.rs`) -/

/-- `IntCC::complement`. -/
def intccComplement : Clif.IntCC → Clif.IntCC
  | .eq => .ne | .ne => .eq | .slt => .sge | .sge => .slt | .sgt => .sle | .sle => .sgt
  | .ult => .uge | .uge => .ult | .ugt => .ule | .ule => .ugt

/-- `IntCC::swap_args`. -/
def intccSwapArgs : Clif.IntCC → Clif.IntCC
  | .eq => .eq | .ne => .ne | .slt => .sgt | .sge => .sle | .sgt => .slt | .sle => .sge
  | .ult => .ugt | .uge => .ule | .ugt => .ult | .ule => .uge

/-- `signed_cond_code`: the code itself if it is a signed comparison. -/
def signedCondCode : Clif.IntCC → Option Clif.IntCC
  | .slt => some .slt | .sge => some .sge | .sgt => some .sgt | .sle => some .sle
  | _ => none

/-- `imm64_icmp(ty, cc, x, y)`: compare the zero- or sign-extended immediates; `1`/`0`. -/
def imm64Icmp (ty : CTy) (cc : Clif.IntCC) (x y : Int) : Panics Int := do
  let ux ← u64UextendImm64 ty x
  let uy ← u64UextendImm64 ty y
  let sx := i64SextendImm64 ty x
  let sy := i64SextendImm64 ty y
  let r := match cc with
    | .eq => ux == uy | .ne => ux != uy
    | .uge => ux ≥ uy | .ugt => ux > uy | .ule => ux ≤ uy | .ult => ux < uy
    | .sge => sx ≥ sy | .sgt => sx > sy | .sle => sx ≤ sy | .slt => sx < sy
  pure (if r then 1 else 0)

/-! ### `numerics.isle` helpers (`<OUT_DIR>/isle_numerics.rs`) -/

/-- `checked_sub(..).unwrap_or_else(panic!)` on an unsigned type. -/
def checkedSubU (fn : String) (a b : Int) : Panics Int :=
  if a ≥ b then pure (a - b) else throw s!"{fn}: subtraction overflow: {a} - {b}"

/-- `u64::checked_shl(b).unwrap_or_else(panic!)`: `None` iff `b ≥ 64`; bits shifted out are
lost. -/
def u64Shl (a b : Int) : Panics Int :=
  if b ≥ 64 then throw s!"u64_shl: shl overflow: {a} << {b}" else pure (asU64 (a * 2 ^ b.toNat))

/-- `i64::checked_shl(b).unwrap_or_else(panic!)`. -/
def i64Shl (a b : Int) : Panics Int :=
  if b ≥ 64 then throw s!"i64_shl: shl overflow: {a} << {b}" else pure (asI64 (a * 2 ^ b.toNat))

/-- `u64::checked_ilog2().unwrap_or_else(panic!)`. -/
def u64Ilog2 (a : Int) : Panics Int :=
  if a > 0 then pure a.toNat.log2 else throw s!"u64_ilog2: ilog2 overflow: {a}"

/-- `u64_bswap16/32/64` (`src/opts.rs`): `(n as uK).swap_bytes() as u64`. -/
def bswap (bytes : Nat) (n : Int) : Int :=
  let v := (asU64 n).toNat % 2 ^ (8 * bytes)
  (List.range bytes).foldl (fun acc i => acc * 256 + (v / 2 ^ (8 * i)) % 256) 0

/-! ### Division by constants (`src/opts/div_const.rs`, release-build wrapping arithmetic) -/

/-- `magic_u32` / `magic_u64` at width `w` (32 or 64): `(mul_by, do_add, shift_by)`.
The Rust loop ends by `p < 2w` at the latest; the fuel is that bound. -/
def magicU (w : Nat) (d : Nat) : Nat × Bool × Int :=
  let M := 2 ^ w
  let wrap (x : Int) : Nat := (x % M).toNat
  let nc : Nat := wrap ((M - 1 : Int) - (wrap (-(d : Int)) % d : Nat))
  let top := 2 ^ (w - 1)
  let q1 := top / nc
  let r1 := wrap ((top : Int) - q1 * nc)
  let q2 := (top - 1) / d
  let r2 := wrap ((top - 1 : Int) - q2 * d)
  let rec loop : Nat → Int → Bool → Nat → Nat → Nat → Nat → Nat × Bool × Int
    | 0, p, doAdd, _, _, q2, _ => (wrap (q2 + 1), doAdd, p - w)
    | f + 1, p, doAdd, q1, r1, q2, r2 =>
      let p := p + 1
      let (q1, r1) :=
        if r1 ≥ wrap ((nc : Int) - r1) then (wrap (2 * q1 + 1), wrap (2 * (r1 : Int) - nc))
        else (wrap (2 * q1), wrap (2 * r1))
      let (doAdd, q2, r2) :=
        if wrap (r2 + 1) ≥ wrap ((d : Int) - r2) then
          (doAdd || q2 ≥ top - 1, wrap (2 * q2 + 1), wrap (2 * (r2 : Int) + 1 - d))
        else
          (doAdd || q2 ≥ top, wrap (2 * q2), wrap (2 * r2 + 1))
      let delta := wrap ((d : Int) - 1 - r2)
      if !(p < 2 * w && (q1 < delta || (q1 == delta && r1 == 0))) then
        (wrap (q2 + 1), doAdd, p - w)
      else loop f p doAdd q1 r1 q2 r2
  loop (2 * w) (w - 1) false q1 r1 q2 r2

/-- `magic_s32` / `magic_s64` at width `w` on a signed divisor `d`: `(mul_by, shift_by)`. -/
def magicS (w : Nat) (d : Int) : Int × Int :=
  let M := 2 ^ w
  let wrap (x : Int) : Nat := (x % M).toNat
  let two := 2 ^ (w - 1)
  let ad : Nat := wrap d.natAbs  -- `wrapping_abs(d) as uW`
  let t : Nat := two + wrap d / two  -- `two + ((d as uW) >> (w - 1))`
  let anc : Nat := wrap ((t - 1 : Int) - (t % ad : Nat))
  let q1 := two / anc
  let r1 := wrap ((two : Int) - q1 * anc)
  let q2 := two / ad
  let r2 := wrap ((two : Int) - q2 * ad)
  let rec loop : Nat → Int → Nat → Nat → Nat → Nat → Nat × Int
    | 0, p, _, _, q2, _ => (q2, p)
    | f + 1, p, q1, r1, q2, r2 =>
      let p := p + 1
      let q1 := wrap (2 * q1)
      let r1 := wrap (2 * r1)
      let (q1, r1) := if r1 ≥ anc then (wrap (q1 + 1), wrap ((r1 : Int) - anc)) else (q1, r1)
      let q2 := wrap (2 * q2)
      let r2 := wrap (2 * r2)
      let (q2, r2) := if r2 ≥ ad then (wrap (q2 + 1), wrap ((r2 : Int) - ad)) else (q2, r2)
      let delta := wrap ((ad : Int) - r2)
      if !(q1 < delta || (q1 == delta && r1 == 0)) then (q2, p)
      else loop f p q1 r1 q2 r2
  let (q2, p) := loop (2 * w) (w - 1) q1 r1 q2 r2
  let mul : Nat := if d < 0 then wrap (-((q2 + 1 : Nat) : Int)) else wrap (q2 + 1)
  ((BitVec.ofNat w mul).toInt, p - w)

end Rust

end Isle.Opt
