import FV.Isle.Syntax
import FV.Isle.Pretty
import FV.Isle.Interp
import FV.Isle.Generated.Program
import FV.Isle.Generated.Manifest
import FV.Isle.Generated.Closure

/-!
# ISLE (M4 preparation)

Cranelift's aarch64 ISLE lowering unit as Lean data (`Isle.Aarch64.program`, generated by
`rust/crates/isle2lean`), the emitter-subset closure (`Isle.Aarch64.Closure`), a printer back to
ISLE text, and a generic rule interpreter (`Isle.Interp.run`). Contract: `docs/contracts/isle.md`.
-/
