import FV.Isle.Generated.Opt.Program
import FV.Isle.Generated.Opt.Manifest
import FV.Isle.Generated.Opt.Closure
import FV.Isle.Opt.Helpers
import FV.Isle.Opt.Simplify

/-!
# The mid-end ISLE unit (`opt`)

Cranelift 0.136.1's mid-end rules as Lean data (`Isle.Opt.program`, generated by
`rust/crates/isle2lean` into `FV/Isle/Generated/Opt/`), the E closure of `simplify` /
`simplify_skeleton` (`Isle.Opt.Closure`), Lean transcriptions of the extern Rust helpers
(`Isle.Opt.Rust`), and `Isle.Opt.simplify`, which runs the rules on CLIF e-graph nodes through
the multi-term interpreter (`Isle.Interp.runMultiTerm`). Contracts: `docs/contracts/isle.md`
("Mid-end export"), `docs/contracts/midend.md`.
-/
