import FV.Backend.Proof.IselFlowCheck
import FV.Backend.Proof.IselExcl

/-!
# The flow summary table and its kernel check

Generated by the table inference of the IselFlow work (kept as literal data; every table
term's rules are checked by kernel decisions, in chunks to bound the kernel's memory).
-/

namespace Backend.Proof.Flow

open Isle Isle.Aarch64

/-- Chunk 0 of `flowTab`. -/
def flowTab0 : Tab :=
  [(172, [⟨0, true⟩], ⟨0, true⟩),
   (242, [⟨0, true⟩], ⟨0, true⟩),
   (243, [⟨0, true⟩], ⟨0, true⟩),
   (246, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (249, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (250, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (251, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (254, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (255, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (294, [⟨0, true⟩], ⟨0, true⟩),
   (305, [⟨0, true⟩], ⟨0, true⟩),
   (306, [⟨0, true⟩], ⟨0, true⟩)]

/-- Chunk 1 of `flowTab`. -/
def flowTab1 : Tab :=
  [(307, [⟨0, true⟩], ⟨0, true⟩),
   (310, [⟨0, true⟩], ⟨0, true⟩),
   (344, [⟨0, true⟩], ⟨0, true⟩),
   (358, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (359, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (360, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (361, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (362, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (363, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (370, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (371, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (376, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩)]

/-- Chunk 2 of `flowTab`. -/
def flowTab2 : Tab :=
  [(377, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (379, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (380, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (381, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (382, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (383, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (385, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (386, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (390, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (391, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (392, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (393, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩)]

/-- Chunk 3 of `flowTab`. -/
def flowTab3 : Tab :=
  [(395, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (406, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (407, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (409, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (410, [⟨0, true⟩], ⟨0, true⟩),
   (414, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (417, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (418, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (422, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (423, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (424, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (425, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩)]

/-- Chunk 4 of `flowTab`. -/
def flowTab4 : Tab :=
  [(426, [⟨0, true⟩], ⟨0, true⟩),
   (428, [⟨0, true⟩], ⟨0, true⟩),
   (430, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (432, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (433, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (434, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (435, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (437, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (438, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (439, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (440, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (443, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩)]

/-- Chunk 5 of `flowTab`. -/
def flowTab5 : Tab :=
  [(444, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (451, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (452, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (466, [], ⟨0, true⟩),
   (469, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (473, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (487, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (488, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (489, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (490, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (491, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (492, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩)]

/-- Chunk 6 of `flowTab`. -/
def flowTab6 : Tab :=
  [(493, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (495, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (496, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (497, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (498, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (501, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (502, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (513, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (514, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (515, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (517, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (518, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩)]

/-- Chunk 7 of `flowTab`. -/
def flowTab7 : Tab :=
  [(520, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (521, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (522, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (524, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (528, [⟨0, true⟩], ⟨0, true⟩),
   (529, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (530, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (531, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (532, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (533, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (534, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (535, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩)]

/-- Chunk 8 of `flowTab`. -/
def flowTab8 : Tab :=
  [(541, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (542, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (543, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (544, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (553, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (555, [⟨0, true⟩], ⟨0, true⟩),
   (556, [⟨0, true⟩], ⟨0, true⟩),
   (557, [⟨0, true⟩], ⟨0, true⟩),
   (558, [⟨0, true⟩], ⟨0, true⟩),
   (559, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (560, [⟨0, true⟩], ⟨0, true⟩),
   (561, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩)]

/-- Chunk 9 of `flowTab`. -/
def flowTab9 : Tab :=
  [(562, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (564, [⟨0, true⟩], ⟨0, true⟩),
   (565, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (566, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (570, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (571, [⟨0, true⟩], ⟨0, true⟩),
   (572, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (573, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (574, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (575, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (576, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (577, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩)]

/-- Chunk 10 of `flowTab`. -/
def flowTab10 : Tab :=
  [(612, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (613, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (638, [⟨0, true⟩], ⟨0, true⟩),
   (639, [⟨0, true⟩], ⟨0, true⟩),
   (643, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (647, [⟨0, true⟩], ⟨0, true⟩),
   (648, [⟨0, true⟩], ⟨0, true⟩),
   (649, [⟨0, true⟩], ⟨0, true⟩),
   (650, [⟨0, true⟩], ⟨0, true⟩),
   (651, [⟨0, true⟩], ⟨0, true⟩),
   (652, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (653, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩)]

/-- Chunk 11 of `flowTab`. -/
def flowTab11 : Tab :=
  [(654, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (655, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (656, [⟨0, true⟩], ⟨0, true⟩),
   (657, [⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (658, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (659, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (660, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (698, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (699, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (700, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (703, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (710, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩)]

/-- Chunk 12 of `flowTab`. -/
def flowTab12 : Tab :=
  [(712, [⟨0, true⟩, ⟨0, true⟩, ⟨0, true⟩], ⟨0, true⟩),
   (715, [⟨0, true⟩], ⟨0, true⟩)]

/-- The summary table. -/
def flowTab : Tab := flowTab0 ++ flowTab1 ++ flowTab2 ++ flowTab3 ++ flowTab4 ++ flowTab5 ++ flowTab6 ++ flowTab7 ++ flowTab8 ++ flowTab9 ++ flowTab10 ++ flowTab11 ++ flowTab12

set_option maxRecDepth 100000 in
theorem flowTab0_ok :
    flowTab0.all (fun e => (program.rulesOf e.1).all (aRule program flowTab false e.2.1 e.2.2)) =
      true := by
  decide +kernel

set_option maxRecDepth 100000 in
theorem flowTab1_ok :
    flowTab1.all (fun e => (program.rulesOf e.1).all (aRule program flowTab false e.2.1 e.2.2)) =
      true := by
  decide +kernel

set_option maxRecDepth 100000 in
theorem flowTab2_ok :
    flowTab2.all (fun e => (program.rulesOf e.1).all (aRule program flowTab false e.2.1 e.2.2)) =
      true := by
  decide +kernel

set_option maxRecDepth 100000 in
theorem flowTab3_ok :
    flowTab3.all (fun e => (program.rulesOf e.1).all (aRule program flowTab false e.2.1 e.2.2)) =
      true := by
  decide +kernel

set_option maxRecDepth 100000 in
theorem flowTab4_ok :
    flowTab4.all (fun e => (program.rulesOf e.1).all (aRule program flowTab false e.2.1 e.2.2)) =
      true := by
  decide +kernel

set_option maxRecDepth 100000 in
theorem flowTab5_ok :
    flowTab5.all (fun e => (program.rulesOf e.1).all (aRule program flowTab false e.2.1 e.2.2)) =
      true := by
  decide +kernel

set_option maxRecDepth 100000 in
theorem flowTab6_ok :
    flowTab6.all (fun e => (program.rulesOf e.1).all (aRule program flowTab false e.2.1 e.2.2)) =
      true := by
  decide +kernel

set_option maxRecDepth 100000 in
theorem flowTab7_ok :
    flowTab7.all (fun e => (program.rulesOf e.1).all (aRule program flowTab false e.2.1 e.2.2)) =
      true := by
  decide +kernel

set_option maxRecDepth 100000 in
theorem flowTab8_ok :
    flowTab8.all (fun e => (program.rulesOf e.1).all (aRule program flowTab false e.2.1 e.2.2)) =
      true := by
  decide +kernel

set_option maxRecDepth 100000 in
theorem flowTab9_ok :
    flowTab9.all (fun e => (program.rulesOf e.1).all (aRule program flowTab false e.2.1 e.2.2)) =
      true := by
  decide +kernel

set_option maxRecDepth 100000 in
theorem flowTab10_ok :
    flowTab10.all (fun e => (program.rulesOf e.1).all (aRule program flowTab false e.2.1 e.2.2)) =
      true := by
  decide +kernel

set_option maxRecDepth 100000 in
theorem flowTab11_ok :
    flowTab11.all (fun e => (program.rulesOf e.1).all (aRule program flowTab false e.2.1 e.2.2)) =
      true := by
  decide +kernel

set_option maxRecDepth 100000 in
theorem flowTab12_ok :
    flowTab12.all (fun e => (program.rulesOf e.1).all (aRule program flowTab false e.2.1 e.2.2)) =
      true := by
  decide +kernel

/-- Every rule of every term of `flowTab` checks. -/
theorem flowTab_ok : chkTab program flowTab false = true := by
  unfold chkTab
  show (flowTab0 ++ flowTab1 ++ flowTab2 ++ flowTab3 ++ flowTab4 ++ flowTab5 ++ flowTab6 ++ flowTab7 ++ flowTab8 ++ flowTab9 ++ flowTab10 ++ flowTab11 ++ flowTab12).all
    (fun e => (program.rulesOf e.1).all (aRule program flowTab false e.2.1 e.2.2)) = true
  simp only [List.all_append, flowTab0_ok, flowTab1_ok, flowTab2_ok, flowTab3_ok, flowTab4_ok, flowTab5_ok, flowTab6_ok, flowTab7_ok, flowTab8_ok, flowTab9_ok, flowTab10_ok, flowTab11_ok, flowTab12_ok, Bool.and_self]

end Backend.Proof.Flow
