import FV.Backend.Proof.IselFamAluBIconst
import FV.Backend.Proof.IselFamAluBMisc
import FV.Backend.Proof.IselFamilyALU
import FV.Backend.Proof.IselFamALUARules
import FV.Backend.Proof.IselFamALUAExt
import FV.Backend.Proof.IselFamALUALogic
import FV.Backend.Proof.IselFamALUAMul
import FV.Backend.Proof.IselFamALUAMulN
import FV.Backend.Proof.IselFamAluBUnary
import FV.Backend.Proof.IselCmpDivRoot
import FV.Backend.Proof.IselCmpSdiv
import FV.Backend.Proof.IselCmpDivRem
import FV.Backend.Proof.IselCmpMinMax
import FV.Backend.Proof.IselCmpVec
import FV.Backend.Proof.IselFamAluBExtend
import FV.Backend.Proof.IselCmpRoot
import FV.Backend.Proof.IselFamAluBNotShift
import FV.Backend.Proof.IselFamALUALogicNot
import FV.Backend.Proof.IselFamALUAExtr
import FV.Backend.Proof.IselFamAluBShift
import FV.Backend.Proof.IselFamAluBBfm
import FV.Backend.Proof.IselFamAluBRot
import FV.Backend.Proof.IselFamAluBBitrev
import FV.Backend.Proof.IselFamAluBClz
import FV.Backend.Proof.IselFamAluBBswap
import FV.Backend.Proof.IselFamAluBPopcnt
import FV.Backend.Proof.IselCmpSelect
import FV.Backend.Proof.IselCtlUnmatch
import FV.Backend.Proof.IselExclData
import FV.Backend.Proof.IselAtomic

/-!
# M4: `LowerRulesCorrect program`

Assembly of the per-rule theorems of families A, B, C (`*_ok` / `*_ruleOk`) into
`lowerRulesCorrect_program`. Every closure root rule of `lower` (`closureRootIds`) that is not a
call (`callRootRule`) or memory (`memRootRule`) rule is dispatched by its rule id to its theorem;
the terminator rules `trap` (964) and `return` (1037) are vacuous here (their format `Trap` /
`MultiAry` is not the format of an E instruction; they are proven as `LowerTermRuleOk` in
`IselCtl`), and the `lower_branch` roots (1132, 1137–1140) are not rules of `lower`.

The per-id case split below was generated by an untrusted script from `closureRootIds`, the
rule list `data_program.r686` (indices) and the theorem names; Lean checks every case.
-/

namespace Backend.Proof

open Backend Isle Isle.Interp Isle.Aarch64

set_option maxRecDepth 100000

/-- The formats of E instructions are neither `Trap` (26) nor `MultiAry` (18). -/
theorem eNamePairs_fmt : eNamePairs.all (fun pr =>
    variantIdx 152 pr.1 != some 26 && variantIdx 152 pr.1 != some 18) = true := by
  decide +kernel

theorem instData_fmt_ne {f : Clif.Function} {c : Clif.Inst} {kf : Nat} {fs : List V}
    (h : instData f c = .ok (.data 152 kf fs)) : kf ≠ 26 ∧ kf ≠ 18 := by
  obtain ⟨rest, hd⟩ := instData_names h
  have hm := List.all_eq_true.mp eNamePairs_fmt _ (instNames_mem h)
  unfold instDataV mkVariant at hd
  split at hd
  · rename_i k hk
    cases hd
    rw [hk] at hm
    simp only [bne_iff_ne, ne_eq, Option.some.injEq, Bool.and_eq_true, decide_eq_true_eq] at hm
    exact hm
  · cases hd

/-- A rule of `lower` whose root format is `Trap`/`MultiAry` never matches an E instruction. -/
theorem lowerRuleOk_of_fmt {isem : Sem} {MR : MemRelT} {env : Clif.Env}
    {cp : Clif.Program} {r : Rule} {fT : Nat} (hq : ruleFmt r = some fT)
    (hf : fT = 2447 + 26 ∨ fT = 2447 + 18) : LowerRuleOk isem MR env cp program r := by
  intro f ctx hctx ii info inst hi hic cfg hco m n st tr env' s1 out st' tr' hm hn hvb _ hmatch _
  exfalso
  obtain ⟨info', fs, hinfo, hdat⟩ :=
    ruleFmt_match (vs := []) data_program fmtKinds_program hq (by omega) (by omega) hmatch
  rw [hi] at hinfo
  cases hinfo
  have hd := hctx.data ii _ inst hi hic
  rw [hdat] at hd
  have := instData_fmt_ne hd
  omega

theorem eq_of_mem_of_id' {r r0 : Rule} :
    ∀ {L : List Rule}, (L.map Rule.id).Nodup → r ∈ L → r0 ∈ L → r.id = r0.id → r = r0
  | [], _, hr, _, _ => by cases hr
  | a :: L, hnd, hr, hr0, h => by
    simp only [List.map_cons, List.nodup_cons, List.mem_map, not_exists, not_and] at hnd
    rcases List.mem_cons.mp hr with h1 | h1 <;> rcases List.mem_cons.mp hr0 with h2 | h2
    · rw [h1, h2]
    · subst h1; exact absurd h.symm (fun e => hnd.1 r0 h2 e)
    · subst h2; exact absurd h (fun e => hnd.1 r h1 e)
    · exact eq_of_mem_of_id' hnd.2 h1 h2 h

theorem lowerAll_ids_nodup : ((program.rulesOf TId.lower).map Rule.id).Nodup := by
  rw [show TId.lower = 686 from rfl, data_program.r686]
  decide +kernel

theorem lower_rule_eq {r r0 : Rule} (hr : r ∈ program.rulesOf TId.lower) {k : Nat}
    (hk : (program.rulesOf TId.lower)[k]? = some r0) (hid : r.id = r0.id) : r = r0 :=
  eq_of_mem_of_id' lowerAll_ids_nodup hr (List.mem_of_getElem? hk) hid

theorem lower_ids_not_branch :
    (program.rulesOf TId.lower).all (fun r => r.id != 1132 && r.id != 1137 && r.id != 1138 &&
      r.id != 1139 && r.id != 1140) = true := by
  rw [show TId.lower = 686 from rfl, data_program.r686]
  decide +kernel

/-- **M4's target (`lower`)**: every closure root rule of `lower` other than the call
(`callRootRule`, `indRootRule`) and memory rules is correct. -/
theorem lowerRulesCorrect_program : LowerRulesCorrect program := by
  intro F isem MR env cp hR hMR r hr hroot hcall hind hmem
  have hp := data_program
  rw [closureRoot_eq] at hroot
  have hnb := List.all_eq_true.mp lower_ids_not_branch r hr
  simp only [closureRootIds, List.contains_cons, List.contains_nil, Bool.or_false,
    Bool.or_eq_true, beq_iff_eq] at hroot

  rcases hroot with h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h
  · rw [lower_rule_eq hr (k := 172) (r0 := rule_lower_53) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply iconst_ok <;> assumption
  · rw [lower_rule_eq hr (k := 177) (r0 := rule_lower_78) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply nop_ok <;> assumption
  · rw [lower_rule_eq hr (k := 396) (r0 := rule_lower_86) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply iadd_base_case_ok <;> assumption
  · rw [lower_rule_eq hr (k := 24) (r0 := rule_lower_90) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply iadd_imm12_right_ok <;> assumption
  · rw [lower_rule_eq hr (k := 15) (r0 := rule_lower_93) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply iadd_imm12_left_ok <;> assumption
  · rw [lower_rule_eq hr (k := 46) (r0 := rule_lower_98) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply iadd_imm12_neg_right_ok <;> assumption
  · rw [lower_rule_eq hr (k := 33) (r0 := rule_lower_102) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply iadd_imm12_neg_left_ok <;> assumption
  · rw [lower_rule_eq hr (k := 178) (r0 := rule_lower_108) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply iadd_extend_right_ok <;> assumption
  · rw [lower_rule_eq hr (k := 77) (r0 := rule_lower_111) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply iadd_extend_left_ok <;> assumption
  · rw [lower_rule_eq hr (k := 4) (r0 := rule_lower_116) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply iadd_ishl_right_ok <;> assumption
  · rw [lower_rule_eq hr (k := 9) (r0 := rule_lower_120) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply iadd_ishl_left_ok <;> assumption
  · rw [lower_rule_eq hr (k := 5) (r0 := rule_lower_125) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply iadd_imul_right_ok <;> assumption
  · rw [lower_rule_eq hr (k := 10) (r0 := rule_lower_128) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply iadd_imul_left_ok <;> assumption
  · rw [lower_rule_eq hr (k := 179) (r0 := rule_lower_132) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply isub_imul_ok <;> assumption
  · rw [lower_rule_eq hr (k := 499) (r0 := rule_lower_801) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply isub_base_case_ok <;> assumption
  · rw [lower_rule_eq hr (k := 228) (r0 := rule_lower_805) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply isub_imm12_ok <;> assumption
  · rw [lower_rule_eq hr (k := 50) (r0 := rule_lower_810) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply isub_imm12_neg_ok <;> assumption
  · rw [lower_rule_eq hr (k := 120) (r0 := rule_lower_816) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply isub_extend_ok <;> assumption
  · rw [lower_rule_eq hr (k := 484) (r0 := rule_lower_821) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply isub_ishl_ok <;> assumption
  · rw [lower_rule_eq hr (k := 121) (r0 := rule_lower_857) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply ineg_base_case_ok <;> assumption
  · rw [lower_rule_eq hr (k := 485) (r0 := rule_lower_871) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply imul_base_case_ok <;> assumption
  · rw [lower_rule_eq hr (k := 122) (r0 := rule_lower_1056) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply smulhi_64_ok <;> assumption
  · rw [lower_rule_eq hr (k := 248) (r0 := rule_lower_1059) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply smulhi_fits_in_32_ok <;> assumption
  · rw [lower_rule_eq hr (k := 123) (r0 := rule_lower_1068) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply umulhi_64_ok <;> assumption
  · rw [lower_rule_eq hr (k := 249) (r0 := rule_lower_1071) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply umulhi_fits_in_32_ok <;> assumption
  · rw [lower_rule_eq hr (k := 124) (r0 := rule_lower_1116) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply udiv64_ruleOk <;> assumption
  · rw [lower_rule_eq hr (k := 250) (r0 := rule_lower_1119) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply udiv32_ruleOk <;> assumption
  · rw [lower_rule_eq hr (k := 251) (r0 := rule_lower_1145) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply sdiv64_ruleOk <;> assumption
  · rw [lower_rule_eq hr (k := 426) (r0 := rule_lower_1153) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply sdiv32_ruleOk <;> assumption
  · rw [lower_rule_eq hr (k := 52) (r0 := rule_lower_1163) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply sdiv_safe64_ruleOk <;> assumption
  · rw [lower_rule_eq hr (k := 125) (r0 := rule_lower_1167) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply sdiv_safe32_ruleOk <;> assumption
  · rw [lower_rule_eq hr (k := 252) (r0 := rule_lower_1190) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply urem64_ruleOk <;> assumption
  · rw [lower_rule_eq hr (k := 427) (r0 := rule_lower_1197) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply urem32_ruleOk <;> assumption
  · rw [lower_rule_eq hr (k := 253) (r0 := rule_lower_1204) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply srem64_ruleOk <;> assumption
  · rw [lower_rule_eq hr (k := 428) (r0 := rule_lower_1211) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply srem32_ruleOk <;> assumption
  · rw [lower_rule_eq hr (k := 53) (r0 := rule_lower_1222) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply umin_ruleOk <;> assumption
  · rw [lower_rule_eq hr (k := 54) (r0 := rule_lower_1224) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply smin_ruleOk <;> assumption
  · rw [lower_rule_eq hr (k := 55) (r0 := rule_lower_1226) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply umax_ruleOk <;> assumption
  · rw [lower_rule_eq hr (k := 56) (r0 := rule_lower_1228) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply smax_ruleOk <;> assumption
  · rw [lower_rule_eq hr (k := 254) (r0 := rule_lower_1233) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply vec_smin_ruleOk <;> assumption
  · rw [lower_rule_eq hr (k := 255) (r0 := rule_lower_1239) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply vec_umin_ruleOk <;> assumption
  · rw [lower_rule_eq hr (k := 256) (r0 := rule_lower_1245) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply vec_smax_ruleOk <;> assumption
  · rw [lower_rule_eq hr (k := 257) (r0 := rule_lower_1251) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply vec_umax_ruleOk <;> assumption
  · rw [lower_rule_eq hr (k := 459) (r0 := rule_lower_1261) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply uextend_ok <;> assumption
  · exfalso; simp [memRootRule, h] at hmem
  · rw [lower_rule_eq hr (k := 132) (r0 := rule_lower_1281) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply uextend_icmp_ruleOk <;> assumption
  · exfalso; simp [memRootRule, h] at hmem
  · rw [lower_rule_eq hr (k := 500) (r0 := rule_lower_1315) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply sextend_ok <;> assumption
  · exfalso; simp [memRootRule, h] at hmem
  · rw [lower_rule_eq hr (k := 501) (r0 := rule_lower_1377) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply bnot_base_case_ok <;> assumption
  · rw [lower_rule_eq hr (k := 134) (r0 := rule_lower_1401) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply bnot_ishl_ok <;> assumption
  · rw [lower_rule_eq hr (k := 57) (r0 := rule_lower_1406) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply bnot_bxor_ok <;> assumption
  · rw [lower_rule_eq hr (k := 511) (r0 := rule_lower_1412) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply band_fits_in_64_ok <;> assumption
  · rw [lower_rule_eq hr (k := 135) (r0 := rule_lower_1429) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply band_not_right_ok <;> assumption
  · rw [lower_rule_eq hr (k := 58) (r0 := rule_lower_1431) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply band_not_left_ok <;> assumption
  · rw [lower_rule_eq hr (k := 503) (r0 := rule_lower_1449) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply bor_fits_in_64_ok <;> assumption
  · rw [lower_rule_eq hr (k := 136) (r0 := rule_lower_1466) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply bor_not_right_ok <;> assumption
  · rw [lower_rule_eq hr (k := 59) (r0 := rule_lower_1468) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply bor_not_left_ok <;> assumption
  · rw [lower_rule_eq hr (k := 19) (r0 := rule_lower_1501) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply extr_32_or_64_ok <;> assumption
  · rw [lower_rule_eq hr (k := 20) (r0 := rule_lower_1507) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply extr_32_or_64_2_ok <;> assumption
  · rw [lower_rule_eq hr (k := 504) (r0 := rule_lower_1516) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply bxor_fits_in_64_ok <;> assumption
  · rw [lower_rule_eq hr (k := 137) (r0 := rule_lower_1534) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply bxor_not_right_ok <;> assumption
  · rw [lower_rule_eq hr (k := 60) (r0 := rule_lower_1536) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply bxor_not_left_ok <;> assumption
  · rw [lower_rule_eq hr (k := 435) (r0 := rule_lower_1545) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply ishl_fits_in_32_ok <;> assumption
  · rw [lower_rule_eq hr (k := 266) (r0 := rule_lower_1549) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply ishl_64_ok <;> assumption
  · rw [lower_rule_eq hr (k := 436) (r0 := rule_lower_1638) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply ushr_fits_in_32_ok <;> assumption
  · rw [lower_rule_eq hr (k := 268) (r0 := rule_lower_1642) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply ushr_64_ok <;> assumption
  · rw [lower_rule_eq hr (k := 506) (r0 := rule_lower_1695) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply sshr_fits_in_32_ok <;> assumption
  · rw [lower_rule_eq hr (k := 270) (r0 := rule_lower_1699) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply sshr_64_ok <;> assumption
  · rw [lower_rule_eq hr (k := 138) (r0 := rule_lower_1704) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply sbfm_ok <;> assumption
  · rw [lower_rule_eq hr (k := 139) (r0 := rule_lower_1707) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply ubfm_ok <;> assumption
  · rw [lower_rule_eq hr (k := 468) (r0 := rule_lower_1772) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply rotl_fits_in_16_ok <;> assumption
  · rw [lower_rule_eq hr (k := 438) (r0 := rule_lower_1778) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply rotl_fits_in_16_imm_ok <;> assumption
  · rw [lower_rule_eq hr (k := 272) (r0 := rule_lower_1791) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply rotl_32_base_case_ok <;> assumption
  · rw [lower_rule_eq hr (k := 273) (r0 := rule_lower_1797) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply rotl_64_base_case_ok <;> assumption
  · rw [lower_rule_eq hr (k := 140) (r0 := rule_lower_1803) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply rotl_32_imm_ok <;> assumption
  · rw [lower_rule_eq hr (k := 141) (r0 := rule_lower_1808) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply rotl_64_imm_ok <;> assumption
  · rw [lower_rule_eq hr (k := 493) (r0 := rule_lower_1840) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply rotr_fits_in_16_ok <;> assumption
  · rw [lower_rule_eq hr (k := 439) (r0 := rule_lower_1844) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply rotr_32_base_case_ok <;> assumption
  · rw [lower_rule_eq hr (k := 440) (r0 := rule_lower_1848) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply rotr_64_base_case_ok <;> assumption
  · rw [lower_rule_eq hr (k := 469) (r0 := rule_lower_1852) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply rotr_fits_in_16_imm_ok <;> assumption
  · rw [lower_rule_eq hr (k := 275) (r0 := rule_lower_1857) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply rotr_32_imm_ok <;> assumption
  · rw [lower_rule_eq hr (k := 276) (r0 := rule_lower_1862) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply rotr_64_imm_ok <;> assumption
  · rw [lower_rule_eq hr (k := 278) (r0 := rule_lower_1931) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply bitrev_i8_ok <;> assumption
  · rw [lower_rule_eq hr (k := 279) (r0 := rule_lower_1937) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply bitrev_i16_ok <;> assumption
  · rw [lower_rule_eq hr (k := 441) (r0 := rule_lower_1946) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply bitrev_ok <;> assumption
  · rw [lower_rule_eq hr (k := 281) (r0 := rule_lower_1951) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply clz_i8_ok <;> assumption
  · rw [lower_rule_eq hr (k := 282) (r0 := rule_lower_1955) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply clz_i16_ok <;> assumption
  · rw [lower_rule_eq hr (k := 442) (r0 := rule_lower_1961) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply clz_ok <;> assumption
  · rw [lower_rule_eq hr (k := 284) (r0 := rule_lower_1982) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply ctz_i8_ok <;> assumption
  · rw [lower_rule_eq hr (k := 285) (r0 := rule_lower_1986) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply ctz_i16_ok <;> assumption
  · rw [lower_rule_eq hr (k := 443) (r0 := rule_lower_1995) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply ctz_ok <;> assumption
  · rw [lower_rule_eq hr (k := 290) (r0 := rule_lower_2035) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply bswap_i16_ok <;> assumption
  · rw [lower_rule_eq hr (k := 291) (r0 := rule_lower_2038) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply bswap_i32_ok <;> assumption
  · rw [lower_rule_eq hr (k := 292) (r0 := rule_lower_2041) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply bswap_i64_ok <;> assumption
  · rw [lower_rule_eq hr (k := 294) (r0 := rule_lower_2052) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply bmask_ok <;> assumption
  · rw [lower_rule_eq hr (k := 295) (r0 := rule_lower_2074) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply popcnt_8_ok <;> assumption
  · rw [lower_rule_eq hr (k := 296) (r0 := rule_lower_2080) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply popcnt_16_ok <;> assumption
  · rw [lower_rule_eq hr (k := 297) (r0 := rule_lower_2086) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply popcnt_32_ok <;> assumption
  · rw [lower_rule_eq hr (k := 298) (r0 := rule_lower_2092) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply popcnt_64_ok <;> assumption
  · rw [lower_rule_eq hr (k := 302) (r0 := rule_lower_2146) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply ireduce_ok <;> assumption
  · rw [lower_rule_eq hr (k := 470) (r0 := rule_lower_2215) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply icmp_ruleOk <;> assumption
  · rw [lower_rule_eq hr (k := 305) (r0 := rule_lower_2237) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    exact lowerRuleOk_of_fmt rfl (.inl rfl)
  · rw [lower_rule_eq hr (k := 308) (r0 := rule_lower_2267) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply select_ruleOk <;> assumption
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · rw [lower_rule_eq hr (k := 337) (r0 := rule_lower_2476) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    apply fence_ok <;> assumption
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [callRootRule, h] at hcall
  · exfalso; simp [callRootRule, h] at hcall
  · exfalso; simp [indRootRule, h] at hind
  · rw [lower_rule_eq hr (k := 346) (r0 := rule_lower_2574) (by rw [show TId.lower = 686 from rfl, data_program.r686]; rfl) (by rw [h]; rfl)]
    exact lowerRuleOk_of_fmt rfl (.inr rfl)
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [memRootRule, h] at hmem
  · exfalso; simp [h] at hnb
  · exfalso; simp [h] at hnb
  · exfalso; simp [h] at hnb
  · exfalso; simp [h] at hnb
  · exfalso; simp [h] at hnb

end Backend.Proof
