// Minimal panic / mem* runtime for the Rust route (step 2): freestanding C for
// aarch64, linked with `clif-native --link`.
//
// * `memcpy` / `memset` / `memmove` / `memcmp`: plain AAPCS64 implementations.
// * The `core` panic entry points the corpus references abort (`udf`), i.e. they never
//   return. Their names are mangled Rust symbols, so the stubs are emitted as assembly
//   (rustroute_panic.s, generated by the caller) and jump to the shared abort stub.

static void rustroute_abort(void) {
    __asm__ volatile("udf #251");
    __builtin_unreachable();
}

void *memcpy(void *dst, const void *src, unsigned long n) {
    unsigned char *d = dst;
    const unsigned char *s = src;
    for (unsigned long i = 0; i < n; i++) d[i] = s[i];
    return dst;
}

void *memset(void *dst, int c, unsigned long n) {
    unsigned char *d = dst;
    for (unsigned long i = 0; i < n; i++) d[i] = (unsigned char)c;
    return dst;
}

void *memmove(void *dst, const void *src, unsigned long n) {
    unsigned char *d = dst;
    const unsigned char *s = src;
    if (d < s) {
        for (unsigned long i = 0; i < n; i++) d[i] = s[i];
    } else if (d > s) {
        for (unsigned long i = n; i > 0; i--) d[i - 1] = s[i - 1];
    }
    return dst;
}

int memcmp(const void *a, const void *b, unsigned long n) {
    const unsigned char *p = a, *q = b;
    for (unsigned long i = 0; i < n; i++) {
        if (p[i] != q[i]) return p[i] < q[i] ? -1 : 1;
    }
    return 0;
}

// The abort itself is the generated stub assembly (rust_panic.s): every diverging
// entry point is a label that jumps to `rustroute_abort` there (`udf #251` = SIGILL).
