import FV.Opt.Proof.RuleArith
import FV.Opt.Proof.RuleCprop
import FV.Opt.Proof.RuleBitops1
import FV.Opt.Proof.RuleBitops2
import FV.Opt.Proof.RuleBitops3
import FV.Opt.Proof.RuleBitops4
import FV.Opt.Proof.RuleBitops5
import FV.Opt.Proof.RuleBitops6
import FV.Opt.Proof.RuleBitops7
import FV.Opt.Proof.RuleIcmp1
import FV.Opt.Proof.RuleIcmp2
import FV.Opt.Proof.RuleIcmp3
import FV.Opt.Proof.RuleIcmp4
import FV.Opt.Proof.RuleIcmp5
import FV.Opt.Proof.RuleIcmp6
import FV.Opt.Proof.RuleIcmp7
import FV.Opt.Proof.RuleIcmp8
import FV.Opt.Proof.RuleSelects1
import FV.Opt.Proof.RuleSelects2
import FV.Opt.Proof.RuleSelects3
import FV.Opt.Proof.RuleSelects4
import FV.Opt.Proof.RuleSelects5
import FV.Opt.Proof.RuleSelects6
import FV.Opt.Proof.RuleSkel
import FV.Opt.Optimize

/-!
# The proven allow-list is sound

`simplifyRulesCorrect_proven`: every `simplify` rule of `Isle.Opt.program` whose id is in
`Opt.provenSimplifyRules` is `RuleOk`. `simplifySound_proven`: the Cranelift rule set with the
`proven` allow-list is a sound rule set (`Opt.SimplifySound`), the obligation the `simplify`
pass proof takes (`Opt.Config.simplifyFn` with `ruleAllow := .proven`).

The rule list of `simplify` is only inspected through `List.filter` on rule ids (`rfl`: the
kernel reads each rule's `id` field, nothing else); the rules themselves are handled by the
per-rule theorems over an abstract program with `Data p` (`data_program`).
-/

namespace Opt.Proof

open Isle Isle.Opt

set_option maxRecDepth 20000 in
set_option maxHeartbeats 4000000 in
/-- The `simplify` rules in the proven allow-list. -/
theorem simplify_rules_proven :
    (program.rulesOf T.«simplify».id).filter (fun r => RuleAllow.proven.pred r.id) =
      [rule_arithmetic_8, rule_arithmetic_13, rule_arithmetic_18, rule_arithmetic_24,
        rule_arithmetic_26, rule_arithmetic_28, rule_arithmetic_31, rule_arithmetic_35,
        rule_arithmetic_59, rule_arithmetic_233, rule_arithmetic_239, rule_arithmetic_240,
        rule_arithmetic_243, rule_arithmetic_244, rule_arithmetic_247, rule_arithmetic_295,
        rule_arithmetic_296, rule_arithmetic_297, rule_arithmetic_298, rule_arithmetic_301,
        rule_arithmetic_302, rule_arithmetic_303, rule_arithmetic_304, rule_arithmetic_307,
        rule_arithmetic_308, rule_arithmetic_311, rule_arithmetic_312, rule_arithmetic_313,
        rule_arithmetic_314, rule_arithmetic_317, rule_arithmetic_318, rule_arithmetic_319,
        rule_arithmetic_320, rule_arithmetic_323, rule_arithmetic_324, rule_arithmetic_337,
        rule_arithmetic_338, rule_arithmetic_339, rule_arithmetic_340, rule_arithmetic_346,
        rule_arithmetic_352, rule_arithmetic_353, rule_arithmetic_354, rule_arithmetic_355,
        rule_arithmetic_356, rule_arithmetic_357, rule_arithmetic_358, rule_arithmetic_359,
        rule_arithmetic_362, rule_arithmetic_363, rule_arithmetic_364, rule_arithmetic_365,
        rule_arithmetic_366, rule_arithmetic_367, rule_arithmetic_368, rule_arithmetic_369,
        rule_arithmetic_372, rule_arithmetic_373, rule_arithmetic_374, rule_arithmetic_375,
        rule_arithmetic_378, rule_arithmetic_379, rule_arithmetic_380, rule_arithmetic_381,
        rule_arithmetic_384, rule_arithmetic_385, rule_arithmetic_388, rule_arithmetic_389,
        rule_arithmetic_390, rule_arithmetic_391, rule_arithmetic_424, rule_arithmetic_451,
        rule_arithmetic_452, rule_arithmetic_453, rule_arithmetic_454, rule_arithmetic_457,
        rule_arithmetic_458, rule_arithmetic_459, rule_arithmetic_460, rule_arithmetic_461,
        rule_arithmetic_462, rule_arithmetic_463, rule_arithmetic_464, rule_arithmetic_467,
        rule_arithmetic_468, rule_arithmetic_469, rule_arithmetic_470, rule_arithmetic_471,
        rule_arithmetic_472, rule_arithmetic_473, rule_arithmetic_474, rule_arithmetic_477,
        rule_arithmetic_478, rule_arithmetic_479, rule_arithmetic_480, rule_arithmetic_481,
        rule_arithmetic_482, rule_arithmetic_483, rule_arithmetic_484, rule_arithmetic_485,
        rule_arithmetic_486, rule_arithmetic_487, rule_arithmetic_488, rule_arithmetic_489,
        rule_arithmetic_490, rule_arithmetic_491, rule_arithmetic_492, rule_arithmetic_495,
        rule_arithmetic_496, rule_arithmetic_497, rule_arithmetic_498, rule_arithmetic_500,
        rule_arithmetic_501, rule_arithmetic_502, rule_arithmetic_503, rule_arithmetic_505,
        rule_arithmetic_506, rule_arithmetic_507, rule_arithmetic_508, rule_arithmetic_510,
        rule_arithmetic_511, rule_arithmetic_512, rule_arithmetic_513, rule_arithmetic_515,
        rule_arithmetic_516, rule_arithmetic_517, rule_arithmetic_518, rule_arithmetic_520,
        rule_arithmetic_521, rule_arithmetic_522, rule_arithmetic_523, rule_arithmetic_525,
        rule_arithmetic_526, rule_arithmetic_527, rule_arithmetic_528, rule_arithmetic_530,
        rule_arithmetic_531, rule_arithmetic_532, rule_arithmetic_533, rule_arithmetic_536,
        rule_arithmetic_537, rule_arithmetic_538, rule_arithmetic_539, rule_arithmetic_541,
        rule_arithmetic_542, rule_arithmetic_543, rule_arithmetic_544, rule_arithmetic_546,
        rule_arithmetic_547, rule_arithmetic_548, rule_arithmetic_549, rule_arithmetic_551,
        rule_arithmetic_552, rule_arithmetic_553, rule_arithmetic_554, rule_arithmetic_556,
        rule_arithmetic_557, rule_arithmetic_558, rule_arithmetic_559, rule_arithmetic_561,
        rule_arithmetic_562, rule_arithmetic_563, rule_arithmetic_564, rule_arithmetic_566,
        rule_arithmetic_567, rule_arithmetic_568, rule_arithmetic_569, rule_arithmetic_571,
        rule_arithmetic_572, rule_arithmetic_573, rule_arithmetic_574, rule_arithmetic_599,
        rule_bitops_21, rule_bitops_22, rule_bitops_23, rule_bitops_26, rule_bitops_27,
        rule_bitops_30, rule_bitops_40, rule_bitops_41, rule_bitops_45, rule_bitops_46,
        rule_bitops_49, rule_bitops_50, rule_bitops_53, rule_bitops_56, rule_bitops_59,
        rule_bitops_68, rule_bitops_87, rule_bitops_94, rule_bitops_98, rule_bitops_104,
        rule_bitops_139, rule_bitops_140, rule_bitops_143, rule_bitops_146, rule_bitops_199,
        rule_bitops_202, rule_bitops_203, rule_bitops_204, rule_bitops_205, rule_bitops_207,
        rule_bitops_208, rule_bitops_209, rule_bitops_210, rule_bitops_213, rule_bitops_214,
        rule_bitops_215, rule_bitops_216, rule_bitops_219, rule_bitops_220, rule_bitops_223,
        rule_bitops_224, rule_bitops_227, rule_bitops_228, rule_bitops_231, rule_bitops_232,
        rule_bitops_235, rule_bitops_236, rule_bitops_239, rule_bitops_244, rule_bitops_245,
        rule_bitops_246, rule_bitops_247, rule_bitops_248, rule_bitops_249, rule_bitops_250,
        rule_bitops_251, rule_bitops_254, rule_bitops_256, rule_bitops_258, rule_bitops_260,
        rule_bitops_264, rule_bitops_265, rule_bitops_266, rule_bitops_267, rule_bitops_270,
        rule_bitops_271, rule_bitops_272, rule_bitops_273, rule_bitops_274, rule_bitops_275,
        rule_bitops_276, rule_bitops_277, rule_bitops_280, rule_bitops_281, rule_bitops_282,
        rule_bitops_283, rule_bitops_284, rule_bitops_285, rule_bitops_286, rule_bitops_287,
        rule_bitops_290, rule_bitops_291, rule_bitops_292, rule_bitops_293, rule_bitops_294,
        rule_bitops_295, rule_bitops_296, rule_bitops_297, rule_bitops_300, rule_bitops_301,
        rule_bitops_304, rule_bitops_305, rule_bitops_308, rule_bitops_309, rule_bitops_310,
        rule_bitops_311, rule_bitops_312, rule_bitops_313, rule_bitops_314, rule_bitops_315,
        rule_bitops_318, rule_bitops_319, rule_bitops_320, rule_bitops_321, rule_bitops_322,
        rule_bitops_323, rule_bitops_324, rule_bitops_325, rule_bitops_328, rule_bitops_329,
        rule_bitops_330, rule_bitops_331, rule_bitops_334, rule_bitops_335, rule_bitops_336,
        rule_bitops_337, rule_bitops_340, rule_bitops_341, rule_bitops_342, rule_bitops_343,
        rule_bitops_346, rule_bitops_347, rule_bitops_348, rule_bitops_349, rule_bitops_350,
        rule_bitops_351, rule_bitops_352, rule_bitops_353, rule_bitops_356, rule_bitops_357,
        rule_bitops_358, rule_bitops_359, rule_bitops_360, rule_bitops_361, rule_bitops_362,
        rule_bitops_363, rule_bitops_366, rule_bitops_367, rule_bitops_370, rule_bitops_371,
        rule_bitops_374, rule_bitops_375, rule_bitops_376, rule_bitops_377, rule_bitops_380,
        rule_bitops_381, rule_bitops_382, rule_bitops_383, rule_bitops_386, rule_bitops_387,
        rule_bitops_388, rule_bitops_389, rule_bitops_392, rule_bitops_393, rule_bitops_394,
        rule_bitops_395, rule_bitops_398, rule_bitops_399, rule_bitops_400, rule_bitops_401,
        rule_bitops_403, rule_bitops_404, rule_bitops_405, rule_bitops_406, rule_bitops_408,
        rule_bitops_409, rule_bitops_410, rule_bitops_411, rule_bitops_413, rule_bitops_414,
        rule_bitops_415, rule_bitops_416, rule_bitops_419, rule_bitops_420, rule_bitops_421,
        rule_bitops_422, rule_bitops_425, rule_bitops_426, rule_bitops_429, rule_bitops_430,
        rule_bitops_431, rule_bitops_432, rule_bitops_433, rule_bitops_434, rule_bitops_435,
        rule_bitops_436, rule_bitops_439, rule_bitops_440, rule_bitops_441, rule_bitops_442,
        rule_bitops_443, rule_bitops_444, rule_bitops_445, rule_bitops_446, rule_bitops_449,
        rule_bitops_450, rule_bitops_451, rule_bitops_452, rule_bitops_453, rule_bitops_454,
        rule_bitops_455, rule_bitops_456, rule_bitops_459, rule_bitops_460, rule_bitops_461,
        rule_bitops_462, rule_bitops_463, rule_bitops_464, rule_bitops_465, rule_bitops_466,
        rule_bitops_469, rule_bitops_470, rule_bitops_471, rule_bitops_472, rule_bitops_473,
        rule_bitops_474, rule_bitops_475, rule_bitops_476, rule_bitops_479, rule_bitops_480,
        rule_bitops_481, rule_bitops_482, rule_bitops_483, rule_bitops_484, rule_bitops_485,
        rule_bitops_486, rule_bitops_489, rule_bitops_490, rule_bitops_491, rule_bitops_492,
        rule_bitops_493, rule_bitops_494, rule_bitops_495, rule_bitops_496, rule_bitops_499,
        rule_bitops_500, rule_bitops_501, rule_bitops_502, rule_bitops_505, rule_bitops_506,
        rule_bitops_507, rule_bitops_508, rule_bitops_511, rule_bitops_512, rule_bitops_513,
        rule_bitops_514, rule_bitops_515, rule_bitops_516, rule_bitops_517, rule_bitops_518,
        rule_bitops_521, rule_bitops_522, rule_bitops_523, rule_bitops_524, rule_bitops_525,
        rule_bitops_526, rule_bitops_527, rule_bitops_528, rule_bitops_531, rule_bitops_532,
        rule_bitops_533, rule_bitops_534, rule_bitops_535, rule_bitops_536, rule_bitops_537,
        rule_bitops_538, rule_bitops_541, rule_bitops_542, rule_bitops_543, rule_bitops_544,
        rule_bitops_547, rule_bitops_548, rule_bitops_549, rule_bitops_550, rule_bitops_553,
        rule_bitops_554, rule_bitops_555, rule_bitops_556, rule_bitops_557, rule_bitops_558,
        rule_bitops_559, rule_bitops_560, rule_bitops_563, rule_bitops_564, rule_bitops_565,
        rule_bitops_566, rule_bitops_567, rule_bitops_568, rule_bitops_569, rule_bitops_570,
        rule_bitops_573, rule_bitops_574, rule_bitops_575, rule_bitops_576, rule_bitops_577,
        rule_bitops_578, rule_bitops_579, rule_bitops_580, rule_bitops_583, rule_bitops_586,
        rule_bitops_587, rule_bitops_588, rule_bitops_589, rule_bitops_592, rule_bitops_593,
        rule_bitops_594, rule_bitops_595, rule_bitops_598, rule_bitops_599, rule_bitops_602,
        rule_bitops_603, rule_bitops_604, rule_bitops_605, rule_bitops_608, rule_bitops_609,
        rule_bitops_610, rule_bitops_611, rule_bitops_614, rule_bitops_615, rule_bitops_616,
        rule_bitops_617, rule_bitops_620, rule_bitops_621, rule_bitops_622, rule_bitops_623,
        rule_bitops_626, rule_bitops_627, rule_bitops_628, rule_bitops_629, rule_bitops_630,
        rule_bitops_631, rule_bitops_632, rule_bitops_633, rule_bitops_636, rule_bitops_637,
        rule_bitops_638, rule_bitops_639, rule_bitops_642, rule_bitops_643, rule_bitops_644,
        rule_bitops_645, rule_bitops_648, rule_bitops_649, rule_bitops_650, rule_bitops_651,
        rule_bitops_654, rule_bitops_655, rule_bitops_656, rule_bitops_657, rule_bitops_660,
        rule_bitops_661, rule_bitops_662, rule_bitops_663, rule_bitops_664, rule_bitops_665,
        rule_bitops_666, rule_bitops_667, rule_bitops_670, rule_bitops_671, rule_bitops_672,
        rule_bitops_673, rule_bitops_674, rule_bitops_675, rule_bitops_676, rule_bitops_677,
        rule_bitops_678, rule_bitops_679, rule_bitops_680, rule_bitops_681, rule_bitops_682,
        rule_bitops_683, rule_bitops_684, rule_bitops_685, rule_bitops_688, rule_bitops_689,
        rule_bitops_690, rule_bitops_691, rule_bitops_694, rule_bitops_697, rule_bitops_698,
        rule_bitops_699, rule_bitops_700, rule_bitops_701, rule_bitops_702, rule_bitops_703,
        rule_bitops_704, rule_bitops_707, rule_bitops_708, rule_bitops_709, rule_bitops_710,
        rule_bitops_711, rule_bitops_712, rule_bitops_713, rule_bitops_714, rule_bitops_717,
        rule_bitops_718, rule_bitops_719, rule_bitops_720, rule_bitops_721, rule_bitops_722,
        rule_bitops_723, rule_bitops_724, rule_bitops_727, rule_bitops_728, rule_bitops_729,
        rule_bitops_730, rule_bitops_731, rule_bitops_732, rule_bitops_733, rule_bitops_734,
        rule_bitops_737, rule_bitops_738, rule_bitops_739, rule_bitops_740, rule_bitops_743,
        rule_bitops_745, rule_bitops_747, rule_bitops_749, rule_bitops_753, rule_bitops_755,
        rule_bitops_757, rule_bitops_759, rule_bitops_763, rule_bitops_764, rule_bitops_765,
        rule_bitops_766, rule_bitops_767, rule_bitops_768, rule_bitops_769, rule_bitops_770,
        rule_bitops_773, rule_bitops_774, rule_bitops_775, rule_bitops_776, rule_bitops_777,
        rule_bitops_778, rule_bitops_779, rule_bitops_780, rule_bitops_783, rule_bitops_784,
        rule_bitops_785, rule_bitops_786, rule_bitops_789, rule_bitops_792, rule_cprop_3,
        rule_cprop_9, rule_cprop_14, rule_cprop_20, rule_cprop_26, rule_cprop_56, rule_cprop_62,
        rule_cprop_68, rule_cprop_74, rule_cprop_104, rule_cprop_109, rule_cprop_114,
        rule_cprop_119, rule_cprop_147, rule_cprop_152, rule_cprop_155, rule_cprop_159,
        rule_cprop_162, rule_cprop_165, rule_cprop_169, rule_cprop_170, rule_cprop_171,
        rule_cprop_172, rule_cprop_174, rule_cprop_183, rule_cprop_193, rule_cprop_197,
        rule_cprop_201, rule_cprop_205, rule_cprop_209, rule_cprop_214, rule_cprop_217,
        rule_cprop_220, rule_cprop_223, rule_cprop_227, rule_cprop_229, rule_cprop_232,
        rule_cprop_235, rule_cprop_238, rule_cprop_241, rule_cprop_247, rule_cprop_249,
        rule_cprop_252, rule_cprop_254, rule_cprop_257, rule_cprop_259, rule_cprop_333,
        rule_cprop_337, rule_cprop_341, rule_cprop_345, rule_cprop_349, rule_cprop_521, rule_icmp_5,
        rule_icmp_6, rule_icmp_7, rule_icmp_8, rule_icmp_9, rule_icmp_10, rule_icmp_11,
        rule_icmp_12, rule_icmp_13, rule_icmp_14, rule_icmp_21, rule_icmp_23, rule_icmp_25,
        rule_icmp_27, rule_icmp_29, rule_icmp_31, rule_icmp_33, rule_icmp_35, rule_icmp_41,
        rule_icmp_43, rule_icmp_49, rule_icmp_63, rule_icmp_70, rule_icmp_77, rule_icmp_84,
        rule_icmp_91, rule_icmp_96, rule_icmp_104, rule_icmp_108, rule_icmp_112, rule_icmp_116,
        rule_icmp_120, rule_icmp_125, rule_icmp_130, rule_icmp_135, rule_icmp_140, rule_icmp_145,
        rule_icmp_150, rule_icmp_155, rule_icmp_160, rule_icmp_165, rule_icmp_170, rule_icmp_175,
        rule_icmp_180, rule_icmp_184, rule_icmp_190, rule_icmp_193, rule_icmp_205, rule_icmp_254,
        rule_icmp_259, rule_icmp_264, rule_icmp_269, rule_icmp_274, rule_icmp_279, rule_icmp_284,
        rule_icmp_289, rule_icmp_295, rule_icmp_296, rule_icmp_299, rule_icmp_300, rule_icmp_303,
        rule_icmp_304, rule_icmp_306, rule_icmp_307, rule_icmp_310, rule_icmp_311, rule_icmp_312,
        rule_icmp_313, rule_icmp_314, rule_icmp_315, rule_icmp_316, rule_icmp_317, rule_icmp_325,
        rule_icmp_329, rule_icmp_333, rule_icmp_337, rule_icmp_341, rule_icmp_345, rule_icmp_349,
        rule_icmp_353, rule_icmp_359, rule_icmp_362, rule_icmp_365, rule_icmp_368, rule_icmp_371,
        rule_icmp_374, rule_icmp_377, rule_icmp_380, rule_icmp_386, rule_icmp_394, rule_icmp_402,
        rule_icmp_410, rule_icmp_438, rule_icmp_442, rule_icmp_447, rule_icmp_451, rule_icmp_479,
        rule_icmp_482, rule_icmp_485, rule_icmp_486, rule_icmp_489, rule_icmp_490, rule_icmp_491,
        rule_icmp_492, rule_icmp_495, rule_icmp_498, rule_icmp_501, rule_icmp_502, rule_icmp_505,
        rule_icmp_506, rule_icmp_509, rule_icmp_510, rule_icmp_513, rule_icmp_514, rule_icmp_517,
        rule_icmp_520, rule_icmp_523, rule_icmp_526, rule_icmp_529, rule_icmp_532, rule_icmp_535,
        rule_selects_4, rule_selects_9, rule_selects_20, rule_selects_26, rule_selects_27,
        rule_selects_28, rule_selects_29, rule_selects_30, rule_selects_31, rule_selects_32,
        rule_selects_33, rule_selects_36, rule_selects_37, rule_selects_38, rule_selects_39,
        rule_selects_40, rule_selects_41, rule_selects_42, rule_selects_43, rule_selects_91,
        rule_selects_95, rule_selects_103, rule_selects_109, rule_selects_110, rule_selects_113,
        rule_selects_114, rule_selects_115, rule_selects_116, rule_selects_117, rule_selects_118,
        rule_selects_119, rule_selects_120, rule_selects_124, rule_selects_125, rule_selects_126,
        rule_selects_127, rule_selects_130, rule_selects_131, rule_selects_132, rule_selects_133,
        rule_selects_137, rule_selects_138, rule_selects_139, rule_selects_140, rule_selects_141,
        rule_selects_142, rule_selects_143, rule_selects_144, rule_selects_148, rule_selects_149,
        rule_selects_150, rule_selects_151, rule_selects_152, rule_selects_153, rule_selects_154,
        rule_selects_155, rule_selects_159, rule_selects_160, rule_selects_161, rule_selects_162,
        rule_selects_163, rule_selects_164, rule_selects_165, rule_selects_166, rule_selects_170,
        rule_selects_171, rule_selects_172, rule_selects_173, rule_selects_174, rule_selects_175,
        rule_selects_176, rule_selects_177, rule_selects_178, rule_selects_179, rule_selects_180,
        rule_selects_181, rule_selects_182, rule_selects_183, rule_selects_184, rule_selects_185,
        rule_selects_205, rule_selects_209, rule_selects_213] := by
  rfl

set_option maxRecDepth 20000 in
theorem simplify_rules_length : (program.rulesOf T.«simplify».id).length = 1281 := by
  rfl

/-- Every rule of a list is `RuleOk` (a conjunction, built from the per-rule theorems). -/
def AllOk : List Rule → Prop
  | [] => True
  | r :: rs => RuleOk program r ∧ AllOk rs

theorem AllOk.mem : ∀ {rs : List Rule}, AllOk rs → ∀ r ∈ rs, RuleOk program r
  | _ :: _, ⟨h, _⟩, _, .head _ => h
  | _ :: _, ⟨_, hs⟩, r, .tail _ hm => AllOk.mem hs r hm

set_option maxRecDepth 20000 in
/-- Every rule of the proven list is `RuleOk`. -/
theorem proven_rules_ok : AllOk
    ((program.rulesOf T.«simplify».id).filter (fun r => RuleAllow.proven.pred r.id)) := by
  rw [simplify_rules_proven]
  exact ⟨ok_rule_arithmetic_8 data_program,
    ok_rule_arithmetic_13 data_program,
    ok_rule_arithmetic_18 data_program,
    ok_rule_arithmetic_24 data_program,
    ok_rule_arithmetic_26 data_program,
    ok_rule_arithmetic_28 data_program,
    ok_rule_arithmetic_31 data_program,
    ok_rule_arithmetic_35 data_program,
    ok_rule_arithmetic_59 data_program,
    ok_rule_arithmetic_233 data_program,
    ok_rule_arithmetic_239 data_program,
    ok_rule_arithmetic_240 data_program,
    ok_rule_arithmetic_243 data_program,
    ok_rule_arithmetic_244 data_program,
    ok_rule_arithmetic_247 data_program,
    ok_rule_arithmetic_295 data_program,
    ok_rule_arithmetic_296 data_program,
    ok_rule_arithmetic_297 data_program,
    ok_rule_arithmetic_298 data_program,
    ok_rule_arithmetic_301 data_program,
    ok_rule_arithmetic_302 data_program,
    ok_rule_arithmetic_303 data_program,
    ok_rule_arithmetic_304 data_program,
    ok_rule_arithmetic_307 data_program,
    ok_rule_arithmetic_308 data_program,
    ok_rule_arithmetic_311 data_program,
    ok_rule_arithmetic_312 data_program,
    ok_rule_arithmetic_313 data_program,
    ok_rule_arithmetic_314 data_program,
    ok_rule_arithmetic_317 data_program,
    ok_rule_arithmetic_318 data_program,
    ok_rule_arithmetic_319 data_program,
    ok_rule_arithmetic_320 data_program,
    ok_rule_arithmetic_323 data_program,
    ok_rule_arithmetic_324 data_program,
    ok_rule_arithmetic_337 data_program,
    ok_rule_arithmetic_338 data_program,
    ok_rule_arithmetic_339 data_program,
    ok_rule_arithmetic_340 data_program,
    ok_rule_arithmetic_346 data_program,
    ok_rule_arithmetic_352 data_program,
    ok_rule_arithmetic_353 data_program,
    ok_rule_arithmetic_354 data_program,
    ok_rule_arithmetic_355 data_program,
    ok_rule_arithmetic_356 data_program,
    ok_rule_arithmetic_357 data_program,
    ok_rule_arithmetic_358 data_program,
    ok_rule_arithmetic_359 data_program,
    ok_rule_arithmetic_362 data_program,
    ok_rule_arithmetic_363 data_program,
    ok_rule_arithmetic_364 data_program,
    ok_rule_arithmetic_365 data_program,
    ok_rule_arithmetic_366 data_program,
    ok_rule_arithmetic_367 data_program,
    ok_rule_arithmetic_368 data_program,
    ok_rule_arithmetic_369 data_program,
    ok_rule_arithmetic_372 data_program,
    ok_rule_arithmetic_373 data_program,
    ok_rule_arithmetic_374 data_program,
    ok_rule_arithmetic_375 data_program,
    ok_rule_arithmetic_378 data_program,
    ok_rule_arithmetic_379 data_program,
    ok_rule_arithmetic_380 data_program,
    ok_rule_arithmetic_381 data_program,
    ok_rule_arithmetic_384 data_program,
    ok_rule_arithmetic_385 data_program,
    ok_rule_arithmetic_388 data_program,
    ok_rule_arithmetic_389 data_program,
    ok_rule_arithmetic_390 data_program,
    ok_rule_arithmetic_391 data_program,
    ok_rule_arithmetic_424 data_program,
    ok_rule_arithmetic_451 data_program,
    ok_rule_arithmetic_452 data_program,
    ok_rule_arithmetic_453 data_program,
    ok_rule_arithmetic_454 data_program,
    ok_rule_arithmetic_457 data_program,
    ok_rule_arithmetic_458 data_program,
    ok_rule_arithmetic_459 data_program,
    ok_rule_arithmetic_460 data_program,
    ok_rule_arithmetic_461 data_program,
    ok_rule_arithmetic_462 data_program,
    ok_rule_arithmetic_463 data_program,
    ok_rule_arithmetic_464 data_program,
    ok_rule_arithmetic_467 data_program,
    ok_rule_arithmetic_468 data_program,
    ok_rule_arithmetic_469 data_program,
    ok_rule_arithmetic_470 data_program,
    ok_rule_arithmetic_471 data_program,
    ok_rule_arithmetic_472 data_program,
    ok_rule_arithmetic_473 data_program,
    ok_rule_arithmetic_474 data_program,
    ok_rule_arithmetic_477 data_program,
    ok_rule_arithmetic_478 data_program,
    ok_rule_arithmetic_479 data_program,
    ok_rule_arithmetic_480 data_program,
    ok_rule_arithmetic_481 data_program,
    ok_rule_arithmetic_482 data_program,
    ok_rule_arithmetic_483 data_program,
    ok_rule_arithmetic_484 data_program,
    ok_rule_arithmetic_485 data_program,
    ok_rule_arithmetic_486 data_program,
    ok_rule_arithmetic_487 data_program,
    ok_rule_arithmetic_488 data_program,
    ok_rule_arithmetic_489 data_program,
    ok_rule_arithmetic_490 data_program,
    ok_rule_arithmetic_491 data_program,
    ok_rule_arithmetic_492 data_program,
    ok_rule_arithmetic_495 data_program,
    ok_rule_arithmetic_496 data_program,
    ok_rule_arithmetic_497 data_program,
    ok_rule_arithmetic_498 data_program,
    ok_rule_arithmetic_500 data_program,
    ok_rule_arithmetic_501 data_program,
    ok_rule_arithmetic_502 data_program,
    ok_rule_arithmetic_503 data_program,
    ok_rule_arithmetic_505 data_program,
    ok_rule_arithmetic_506 data_program,
    ok_rule_arithmetic_507 data_program,
    ok_rule_arithmetic_508 data_program,
    ok_rule_arithmetic_510 data_program,
    ok_rule_arithmetic_511 data_program,
    ok_rule_arithmetic_512 data_program,
    ok_rule_arithmetic_513 data_program,
    ok_rule_arithmetic_515 data_program,
    ok_rule_arithmetic_516 data_program,
    ok_rule_arithmetic_517 data_program,
    ok_rule_arithmetic_518 data_program,
    ok_rule_arithmetic_520 data_program,
    ok_rule_arithmetic_521 data_program,
    ok_rule_arithmetic_522 data_program,
    ok_rule_arithmetic_523 data_program,
    ok_rule_arithmetic_525 data_program,
    ok_rule_arithmetic_526 data_program,
    ok_rule_arithmetic_527 data_program,
    ok_rule_arithmetic_528 data_program,
    ok_rule_arithmetic_530 data_program,
    ok_rule_arithmetic_531 data_program,
    ok_rule_arithmetic_532 data_program,
    ok_rule_arithmetic_533 data_program,
    ok_rule_arithmetic_536 data_program,
    ok_rule_arithmetic_537 data_program,
    ok_rule_arithmetic_538 data_program,
    ok_rule_arithmetic_539 data_program,
    ok_rule_arithmetic_541 data_program,
    ok_rule_arithmetic_542 data_program,
    ok_rule_arithmetic_543 data_program,
    ok_rule_arithmetic_544 data_program,
    ok_rule_arithmetic_546 data_program,
    ok_rule_arithmetic_547 data_program,
    ok_rule_arithmetic_548 data_program,
    ok_rule_arithmetic_549 data_program,
    ok_rule_arithmetic_551 data_program,
    ok_rule_arithmetic_552 data_program,
    ok_rule_arithmetic_553 data_program,
    ok_rule_arithmetic_554 data_program,
    ok_rule_arithmetic_556 data_program,
    ok_rule_arithmetic_557 data_program,
    ok_rule_arithmetic_558 data_program,
    ok_rule_arithmetic_559 data_program,
    ok_rule_arithmetic_561 data_program,
    ok_rule_arithmetic_562 data_program,
    ok_rule_arithmetic_563 data_program,
    ok_rule_arithmetic_564 data_program,
    ok_rule_arithmetic_566 data_program,
    ok_rule_arithmetic_567 data_program,
    ok_rule_arithmetic_568 data_program,
    ok_rule_arithmetic_569 data_program,
    ok_rule_arithmetic_571 data_program,
    ok_rule_arithmetic_572 data_program,
    ok_rule_arithmetic_573 data_program,
    ok_rule_arithmetic_574 data_program,
    ok_rule_arithmetic_599 data_program,
    ok_rule_bitops_21 data_program,
    ok_rule_bitops_22 data_program,
    ok_rule_bitops_23 data_program,
    ok_rule_bitops_26 data_program,
    ok_rule_bitops_27 data_program,
    ok_rule_bitops_30 data_program,
    ok_rule_bitops_40 data_program,
    ok_rule_bitops_41 data_program,
    ok_rule_bitops_45 data_program,
    ok_rule_bitops_46 data_program,
    ok_rule_bitops_49 data_program,
    ok_rule_bitops_50 data_program,
    ok_rule_bitops_53 data_program,
    ok_rule_bitops_56 data_program,
    ok_rule_bitops_59 data_program,
    ok_rule_bitops_68 data_program,
    ok_rule_bitops_87 data_program,
    ok_rule_bitops_94 data_program,
    ok_rule_bitops_98 data_program,
    ok_rule_bitops_104 data_program,
    ok_rule_bitops_139 data_program,
    ok_rule_bitops_140 data_program,
    ok_rule_bitops_143 data_program,
    ok_rule_bitops_146 data_program,
    ok_rule_bitops_199 data_program,
    ok_rule_bitops_202 data_program,
    ok_rule_bitops_203 data_program,
    ok_rule_bitops_204 data_program,
    ok_rule_bitops_205 data_program,
    ok_rule_bitops_207 data_program,
    ok_rule_bitops_208 data_program,
    ok_rule_bitops_209 data_program,
    ok_rule_bitops_210 data_program,
    ok_rule_bitops_213 data_program,
    ok_rule_bitops_214 data_program,
    ok_rule_bitops_215 data_program,
    ok_rule_bitops_216 data_program,
    ok_rule_bitops_219 data_program,
    ok_rule_bitops_220 data_program,
    ok_rule_bitops_223 data_program,
    ok_rule_bitops_224 data_program,
    ok_rule_bitops_227 data_program,
    ok_rule_bitops_228 data_program,
    ok_rule_bitops_231 data_program,
    ok_rule_bitops_232 data_program,
    ok_rule_bitops_235 data_program,
    ok_rule_bitops_236 data_program,
    ok_rule_bitops_239 data_program,
    ok_rule_bitops_244 data_program,
    ok_rule_bitops_245 data_program,
    ok_rule_bitops_246 data_program,
    ok_rule_bitops_247 data_program,
    ok_rule_bitops_248 data_program,
    ok_rule_bitops_249 data_program,
    ok_rule_bitops_250 data_program,
    ok_rule_bitops_251 data_program,
    ok_rule_bitops_254 data_program,
    ok_rule_bitops_256 data_program,
    ok_rule_bitops_258 data_program,
    ok_rule_bitops_260 data_program,
    ok_rule_bitops_264 data_program,
    ok_rule_bitops_265 data_program,
    ok_rule_bitops_266 data_program,
    ok_rule_bitops_267 data_program,
    ok_rule_bitops_270 data_program,
    ok_rule_bitops_271 data_program,
    ok_rule_bitops_272 data_program,
    ok_rule_bitops_273 data_program,
    ok_rule_bitops_274 data_program,
    ok_rule_bitops_275 data_program,
    ok_rule_bitops_276 data_program,
    ok_rule_bitops_277 data_program,
    ok_rule_bitops_280 data_program,
    ok_rule_bitops_281 data_program,
    ok_rule_bitops_282 data_program,
    ok_rule_bitops_283 data_program,
    ok_rule_bitops_284 data_program,
    ok_rule_bitops_285 data_program,
    ok_rule_bitops_286 data_program,
    ok_rule_bitops_287 data_program,
    ok_rule_bitops_290 data_program,
    ok_rule_bitops_291 data_program,
    ok_rule_bitops_292 data_program,
    ok_rule_bitops_293 data_program,
    ok_rule_bitops_294 data_program,
    ok_rule_bitops_295 data_program,
    ok_rule_bitops_296 data_program,
    ok_rule_bitops_297 data_program,
    ok_rule_bitops_300 data_program,
    ok_rule_bitops_301 data_program,
    ok_rule_bitops_304 data_program,
    ok_rule_bitops_305 data_program,
    ok_rule_bitops_308 data_program,
    ok_rule_bitops_309 data_program,
    ok_rule_bitops_310 data_program,
    ok_rule_bitops_311 data_program,
    ok_rule_bitops_312 data_program,
    ok_rule_bitops_313 data_program,
    ok_rule_bitops_314 data_program,
    ok_rule_bitops_315 data_program,
    ok_rule_bitops_318 data_program,
    ok_rule_bitops_319 data_program,
    ok_rule_bitops_320 data_program,
    ok_rule_bitops_321 data_program,
    ok_rule_bitops_322 data_program,
    ok_rule_bitops_323 data_program,
    ok_rule_bitops_324 data_program,
    ok_rule_bitops_325 data_program,
    ok_rule_bitops_328 data_program,
    ok_rule_bitops_329 data_program,
    ok_rule_bitops_330 data_program,
    ok_rule_bitops_331 data_program,
    ok_rule_bitops_334 data_program,
    ok_rule_bitops_335 data_program,
    ok_rule_bitops_336 data_program,
    ok_rule_bitops_337 data_program,
    ok_rule_bitops_340 data_program,
    ok_rule_bitops_341 data_program,
    ok_rule_bitops_342 data_program,
    ok_rule_bitops_343 data_program,
    ok_rule_bitops_346 data_program,
    ok_rule_bitops_347 data_program,
    ok_rule_bitops_348 data_program,
    ok_rule_bitops_349 data_program,
    ok_rule_bitops_350 data_program,
    ok_rule_bitops_351 data_program,
    ok_rule_bitops_352 data_program,
    ok_rule_bitops_353 data_program,
    ok_rule_bitops_356 data_program,
    ok_rule_bitops_357 data_program,
    ok_rule_bitops_358 data_program,
    ok_rule_bitops_359 data_program,
    ok_rule_bitops_360 data_program,
    ok_rule_bitops_361 data_program,
    ok_rule_bitops_362 data_program,
    ok_rule_bitops_363 data_program,
    ok_rule_bitops_366 data_program,
    ok_rule_bitops_367 data_program,
    ok_rule_bitops_370 data_program,
    ok_rule_bitops_371 data_program,
    ok_rule_bitops_374 data_program,
    ok_rule_bitops_375 data_program,
    ok_rule_bitops_376 data_program,
    ok_rule_bitops_377 data_program,
    ok_rule_bitops_380 data_program,
    ok_rule_bitops_381 data_program,
    ok_rule_bitops_382 data_program,
    ok_rule_bitops_383 data_program,
    ok_rule_bitops_386 data_program,
    ok_rule_bitops_387 data_program,
    ok_rule_bitops_388 data_program,
    ok_rule_bitops_389 data_program,
    ok_rule_bitops_392 data_program,
    ok_rule_bitops_393 data_program,
    ok_rule_bitops_394 data_program,
    ok_rule_bitops_395 data_program,
    ok_rule_bitops_398 data_program,
    ok_rule_bitops_399 data_program,
    ok_rule_bitops_400 data_program,
    ok_rule_bitops_401 data_program,
    ok_rule_bitops_403 data_program,
    ok_rule_bitops_404 data_program,
    ok_rule_bitops_405 data_program,
    ok_rule_bitops_406 data_program,
    ok_rule_bitops_408 data_program,
    ok_rule_bitops_409 data_program,
    ok_rule_bitops_410 data_program,
    ok_rule_bitops_411 data_program,
    ok_rule_bitops_413 data_program,
    ok_rule_bitops_414 data_program,
    ok_rule_bitops_415 data_program,
    ok_rule_bitops_416 data_program,
    ok_rule_bitops_419 data_program,
    ok_rule_bitops_420 data_program,
    ok_rule_bitops_421 data_program,
    ok_rule_bitops_422 data_program,
    ok_rule_bitops_425 data_program,
    ok_rule_bitops_426 data_program,
    ok_rule_bitops_429 data_program,
    ok_rule_bitops_430 data_program,
    ok_rule_bitops_431 data_program,
    ok_rule_bitops_432 data_program,
    ok_rule_bitops_433 data_program,
    ok_rule_bitops_434 data_program,
    ok_rule_bitops_435 data_program,
    ok_rule_bitops_436 data_program,
    ok_rule_bitops_439 data_program,
    ok_rule_bitops_440 data_program,
    ok_rule_bitops_441 data_program,
    ok_rule_bitops_442 data_program,
    ok_rule_bitops_443 data_program,
    ok_rule_bitops_444 data_program,
    ok_rule_bitops_445 data_program,
    ok_rule_bitops_446 data_program,
    ok_rule_bitops_449 data_program,
    ok_rule_bitops_450 data_program,
    ok_rule_bitops_451 data_program,
    ok_rule_bitops_452 data_program,
    ok_rule_bitops_453 data_program,
    ok_rule_bitops_454 data_program,
    ok_rule_bitops_455 data_program,
    ok_rule_bitops_456 data_program,
    ok_rule_bitops_459 data_program,
    ok_rule_bitops_460 data_program,
    ok_rule_bitops_461 data_program,
    ok_rule_bitops_462 data_program,
    ok_rule_bitops_463 data_program,
    ok_rule_bitops_464 data_program,
    ok_rule_bitops_465 data_program,
    ok_rule_bitops_466 data_program,
    ok_rule_bitops_469 data_program,
    ok_rule_bitops_470 data_program,
    ok_rule_bitops_471 data_program,
    ok_rule_bitops_472 data_program,
    ok_rule_bitops_473 data_program,
    ok_rule_bitops_474 data_program,
    ok_rule_bitops_475 data_program,
    ok_rule_bitops_476 data_program,
    ok_rule_bitops_479 data_program,
    ok_rule_bitops_480 data_program,
    ok_rule_bitops_481 data_program,
    ok_rule_bitops_482 data_program,
    ok_rule_bitops_483 data_program,
    ok_rule_bitops_484 data_program,
    ok_rule_bitops_485 data_program,
    ok_rule_bitops_486 data_program,
    ok_rule_bitops_489 data_program,
    ok_rule_bitops_490 data_program,
    ok_rule_bitops_491 data_program,
    ok_rule_bitops_492 data_program,
    ok_rule_bitops_493 data_program,
    ok_rule_bitops_494 data_program,
    ok_rule_bitops_495 data_program,
    ok_rule_bitops_496 data_program,
    ok_rule_bitops_499 data_program,
    ok_rule_bitops_500 data_program,
    ok_rule_bitops_501 data_program,
    ok_rule_bitops_502 data_program,
    ok_rule_bitops_505 data_program,
    ok_rule_bitops_506 data_program,
    ok_rule_bitops_507 data_program,
    ok_rule_bitops_508 data_program,
    ok_rule_bitops_511 data_program,
    ok_rule_bitops_512 data_program,
    ok_rule_bitops_513 data_program,
    ok_rule_bitops_514 data_program,
    ok_rule_bitops_515 data_program,
    ok_rule_bitops_516 data_program,
    ok_rule_bitops_517 data_program,
    ok_rule_bitops_518 data_program,
    ok_rule_bitops_521 data_program,
    ok_rule_bitops_522 data_program,
    ok_rule_bitops_523 data_program,
    ok_rule_bitops_524 data_program,
    ok_rule_bitops_525 data_program,
    ok_rule_bitops_526 data_program,
    ok_rule_bitops_527 data_program,
    ok_rule_bitops_528 data_program,
    ok_rule_bitops_531 data_program,
    ok_rule_bitops_532 data_program,
    ok_rule_bitops_533 data_program,
    ok_rule_bitops_534 data_program,
    ok_rule_bitops_535 data_program,
    ok_rule_bitops_536 data_program,
    ok_rule_bitops_537 data_program,
    ok_rule_bitops_538 data_program,
    ok_rule_bitops_541 data_program,
    ok_rule_bitops_542 data_program,
    ok_rule_bitops_543 data_program,
    ok_rule_bitops_544 data_program,
    ok_rule_bitops_547 data_program,
    ok_rule_bitops_548 data_program,
    ok_rule_bitops_549 data_program,
    ok_rule_bitops_550 data_program,
    ok_rule_bitops_553 data_program,
    ok_rule_bitops_554 data_program,
    ok_rule_bitops_555 data_program,
    ok_rule_bitops_556 data_program,
    ok_rule_bitops_557 data_program,
    ok_rule_bitops_558 data_program,
    ok_rule_bitops_559 data_program,
    ok_rule_bitops_560 data_program,
    ok_rule_bitops_563 data_program,
    ok_rule_bitops_564 data_program,
    ok_rule_bitops_565 data_program,
    ok_rule_bitops_566 data_program,
    ok_rule_bitops_567 data_program,
    ok_rule_bitops_568 data_program,
    ok_rule_bitops_569 data_program,
    ok_rule_bitops_570 data_program,
    ok_rule_bitops_573 data_program,
    ok_rule_bitops_574 data_program,
    ok_rule_bitops_575 data_program,
    ok_rule_bitops_576 data_program,
    ok_rule_bitops_577 data_program,
    ok_rule_bitops_578 data_program,
    ok_rule_bitops_579 data_program,
    ok_rule_bitops_580 data_program,
    ok_rule_bitops_583 data_program,
    ok_rule_bitops_586 data_program,
    ok_rule_bitops_587 data_program,
    ok_rule_bitops_588 data_program,
    ok_rule_bitops_589 data_program,
    ok_rule_bitops_592 data_program,
    ok_rule_bitops_593 data_program,
    ok_rule_bitops_594 data_program,
    ok_rule_bitops_595 data_program,
    ok_rule_bitops_598 data_program,
    ok_rule_bitops_599 data_program,
    ok_rule_bitops_602 data_program,
    ok_rule_bitops_603 data_program,
    ok_rule_bitops_604 data_program,
    ok_rule_bitops_605 data_program,
    ok_rule_bitops_608 data_program,
    ok_rule_bitops_609 data_program,
    ok_rule_bitops_610 data_program,
    ok_rule_bitops_611 data_program,
    ok_rule_bitops_614 data_program,
    ok_rule_bitops_615 data_program,
    ok_rule_bitops_616 data_program,
    ok_rule_bitops_617 data_program,
    ok_rule_bitops_620 data_program,
    ok_rule_bitops_621 data_program,
    ok_rule_bitops_622 data_program,
    ok_rule_bitops_623 data_program,
    ok_rule_bitops_626 data_program,
    ok_rule_bitops_627 data_program,
    ok_rule_bitops_628 data_program,
    ok_rule_bitops_629 data_program,
    ok_rule_bitops_630 data_program,
    ok_rule_bitops_631 data_program,
    ok_rule_bitops_632 data_program,
    ok_rule_bitops_633 data_program,
    ok_rule_bitops_636 data_program,
    ok_rule_bitops_637 data_program,
    ok_rule_bitops_638 data_program,
    ok_rule_bitops_639 data_program,
    ok_rule_bitops_642 data_program,
    ok_rule_bitops_643 data_program,
    ok_rule_bitops_644 data_program,
    ok_rule_bitops_645 data_program,
    ok_rule_bitops_648 data_program,
    ok_rule_bitops_649 data_program,
    ok_rule_bitops_650 data_program,
    ok_rule_bitops_651 data_program,
    ok_rule_bitops_654 data_program,
    ok_rule_bitops_655 data_program,
    ok_rule_bitops_656 data_program,
    ok_rule_bitops_657 data_program,
    ok_rule_bitops_660 data_program,
    ok_rule_bitops_661 data_program,
    ok_rule_bitops_662 data_program,
    ok_rule_bitops_663 data_program,
    ok_rule_bitops_664 data_program,
    ok_rule_bitops_665 data_program,
    ok_rule_bitops_666 data_program,
    ok_rule_bitops_667 data_program,
    ok_rule_bitops_670 data_program,
    ok_rule_bitops_671 data_program,
    ok_rule_bitops_672 data_program,
    ok_rule_bitops_673 data_program,
    ok_rule_bitops_674 data_program,
    ok_rule_bitops_675 data_program,
    ok_rule_bitops_676 data_program,
    ok_rule_bitops_677 data_program,
    ok_rule_bitops_678 data_program,
    ok_rule_bitops_679 data_program,
    ok_rule_bitops_680 data_program,
    ok_rule_bitops_681 data_program,
    ok_rule_bitops_682 data_program,
    ok_rule_bitops_683 data_program,
    ok_rule_bitops_684 data_program,
    ok_rule_bitops_685 data_program,
    ok_rule_bitops_688 data_program,
    ok_rule_bitops_689 data_program,
    ok_rule_bitops_690 data_program,
    ok_rule_bitops_691 data_program,
    ok_rule_bitops_694 data_program,
    ok_rule_bitops_697 data_program,
    ok_rule_bitops_698 data_program,
    ok_rule_bitops_699 data_program,
    ok_rule_bitops_700 data_program,
    ok_rule_bitops_701 data_program,
    ok_rule_bitops_702 data_program,
    ok_rule_bitops_703 data_program,
    ok_rule_bitops_704 data_program,
    ok_rule_bitops_707 data_program,
    ok_rule_bitops_708 data_program,
    ok_rule_bitops_709 data_program,
    ok_rule_bitops_710 data_program,
    ok_rule_bitops_711 data_program,
    ok_rule_bitops_712 data_program,
    ok_rule_bitops_713 data_program,
    ok_rule_bitops_714 data_program,
    ok_rule_bitops_717 data_program,
    ok_rule_bitops_718 data_program,
    ok_rule_bitops_719 data_program,
    ok_rule_bitops_720 data_program,
    ok_rule_bitops_721 data_program,
    ok_rule_bitops_722 data_program,
    ok_rule_bitops_723 data_program,
    ok_rule_bitops_724 data_program,
    ok_rule_bitops_727 data_program,
    ok_rule_bitops_728 data_program,
    ok_rule_bitops_729 data_program,
    ok_rule_bitops_730 data_program,
    ok_rule_bitops_731 data_program,
    ok_rule_bitops_732 data_program,
    ok_rule_bitops_733 data_program,
    ok_rule_bitops_734 data_program,
    ok_rule_bitops_737 data_program,
    ok_rule_bitops_738 data_program,
    ok_rule_bitops_739 data_program,
    ok_rule_bitops_740 data_program,
    ok_rule_bitops_743 data_program,
    ok_rule_bitops_745 data_program,
    ok_rule_bitops_747 data_program,
    ok_rule_bitops_749 data_program,
    ok_rule_bitops_753 data_program,
    ok_rule_bitops_755 data_program,
    ok_rule_bitops_757 data_program,
    ok_rule_bitops_759 data_program,
    ok_rule_bitops_763 data_program,
    ok_rule_bitops_764 data_program,
    ok_rule_bitops_765 data_program,
    ok_rule_bitops_766 data_program,
    ok_rule_bitops_767 data_program,
    ok_rule_bitops_768 data_program,
    ok_rule_bitops_769 data_program,
    ok_rule_bitops_770 data_program,
    ok_rule_bitops_773 data_program,
    ok_rule_bitops_774 data_program,
    ok_rule_bitops_775 data_program,
    ok_rule_bitops_776 data_program,
    ok_rule_bitops_777 data_program,
    ok_rule_bitops_778 data_program,
    ok_rule_bitops_779 data_program,
    ok_rule_bitops_780 data_program,
    ok_rule_bitops_783 data_program,
    ok_rule_bitops_784 data_program,
    ok_rule_bitops_785 data_program,
    ok_rule_bitops_786 data_program,
    ok_rule_bitops_789 data_program,
    ok_rule_bitops_792 data_program,
    ok_rule_cprop_3 data_program,
    ok_rule_cprop_9 data_program,
    ok_rule_cprop_14 data_program,
    ok_rule_cprop_20 data_program,
    ok_rule_cprop_26 data_program,
    ok_rule_cprop_56 data_program,
    ok_rule_cprop_62 data_program,
    ok_rule_cprop_68 data_program,
    ok_rule_cprop_74 data_program,
    ok_rule_cprop_104 data_program,
    ok_rule_cprop_109 data_program,
    ok_rule_cprop_114 data_program,
    ok_rule_cprop_119 data_program,
    ok_rule_cprop_147 data_program,
    ok_rule_cprop_152 data_program,
    ok_rule_cprop_155 data_program,
    ok_rule_cprop_159 data_program,
    ok_rule_cprop_162 data_program,
    ok_rule_cprop_165 data_program,
    ok_rule_cprop_169 data_program,
    ok_rule_cprop_170 data_program,
    ok_rule_cprop_171 data_program,
    ok_rule_cprop_172 data_program,
    ok_rule_cprop_174 data_program,
    ok_rule_cprop_183 data_program,
    ok_rule_cprop_193 data_program,
    ok_rule_cprop_197 data_program,
    ok_rule_cprop_201 data_program,
    ok_rule_cprop_205 data_program,
    ok_rule_cprop_209 data_program,
    ok_rule_cprop_214 data_program,
    ok_rule_cprop_217 data_program,
    ok_rule_cprop_220 data_program,
    ok_rule_cprop_223 data_program,
    ok_rule_cprop_227 data_program,
    ok_rule_cprop_229 data_program,
    ok_rule_cprop_232 data_program,
    ok_rule_cprop_235 data_program,
    ok_rule_cprop_238 data_program,
    ok_rule_cprop_241 data_program,
    ok_rule_cprop_247 data_program,
    ok_rule_cprop_249 data_program,
    ok_rule_cprop_252 data_program,
    ok_rule_cprop_254 data_program,
    ok_rule_cprop_257 data_program,
    ok_rule_cprop_259 data_program,
    ok_rule_cprop_333 data_program,
    ok_rule_cprop_337 data_program,
    ok_rule_cprop_341 data_program,
    ok_rule_cprop_345 data_program,
    ok_rule_cprop_349 data_program,
    ok_rule_cprop_521 data_program,
    ok_rule_icmp_5 data_program,
    ok_rule_icmp_6 data_program,
    ok_rule_icmp_7 data_program,
    ok_rule_icmp_8 data_program,
    ok_rule_icmp_9 data_program,
    ok_rule_icmp_10 data_program,
    ok_rule_icmp_11 data_program,
    ok_rule_icmp_12 data_program,
    ok_rule_icmp_13 data_program,
    ok_rule_icmp_14 data_program,
    ok_rule_icmp_21 data_program,
    ok_rule_icmp_23 data_program,
    ok_rule_icmp_25 data_program,
    ok_rule_icmp_27 data_program,
    ok_rule_icmp_29 data_program,
    ok_rule_icmp_31 data_program,
    ok_rule_icmp_33 data_program,
    ok_rule_icmp_35 data_program,
    ok_rule_icmp_41 data_program,
    ok_rule_icmp_43 data_program,
    ok_rule_icmp_49 data_program,
    ok_rule_icmp_63 data_program,
    ok_rule_icmp_70 data_program,
    ok_rule_icmp_77 data_program,
    ok_rule_icmp_84 data_program,
    ok_rule_icmp_91 data_program,
    ok_rule_icmp_96 data_program,
    ok_rule_icmp_104 data_program,
    ok_rule_icmp_108 data_program,
    ok_rule_icmp_112 data_program,
    ok_rule_icmp_116 data_program,
    ok_rule_icmp_120 data_program,
    ok_rule_icmp_125 data_program,
    ok_rule_icmp_130 data_program,
    ok_rule_icmp_135 data_program,
    ok_rule_icmp_140 data_program,
    ok_rule_icmp_145 data_program,
    ok_rule_icmp_150 data_program,
    ok_rule_icmp_155 data_program,
    ok_rule_icmp_160 data_program,
    ok_rule_icmp_165 data_program,
    ok_rule_icmp_170 data_program,
    ok_rule_icmp_175 data_program,
    ok_rule_icmp_180 data_program,
    ok_rule_icmp_184 data_program,
    ok_rule_icmp_190 data_program,
    ok_rule_icmp_193 data_program,
    ok_rule_icmp_205 data_program,
    ok_rule_icmp_254 data_program,
    ok_rule_icmp_259 data_program,
    ok_rule_icmp_264 data_program,
    ok_rule_icmp_269 data_program,
    ok_rule_icmp_274 data_program,
    ok_rule_icmp_279 data_program,
    ok_rule_icmp_284 data_program,
    ok_rule_icmp_289 data_program,
    ok_rule_icmp_295 data_program,
    ok_rule_icmp_296 data_program,
    ok_rule_icmp_299 data_program,
    ok_rule_icmp_300 data_program,
    ok_rule_icmp_303 data_program,
    ok_rule_icmp_304 data_program,
    ok_rule_icmp_306 data_program,
    ok_rule_icmp_307 data_program,
    ok_rule_icmp_310 data_program,
    ok_rule_icmp_311 data_program,
    ok_rule_icmp_312 data_program,
    ok_rule_icmp_313 data_program,
    ok_rule_icmp_314 data_program,
    ok_rule_icmp_315 data_program,
    ok_rule_icmp_316 data_program,
    ok_rule_icmp_317 data_program,
    ok_rule_icmp_325 data_program,
    ok_rule_icmp_329 data_program,
    ok_rule_icmp_333 data_program,
    ok_rule_icmp_337 data_program,
    ok_rule_icmp_341 data_program,
    ok_rule_icmp_345 data_program,
    ok_rule_icmp_349 data_program,
    ok_rule_icmp_353 data_program,
    ok_rule_icmp_359 data_program,
    ok_rule_icmp_362 data_program,
    ok_rule_icmp_365 data_program,
    ok_rule_icmp_368 data_program,
    ok_rule_icmp_371 data_program,
    ok_rule_icmp_374 data_program,
    ok_rule_icmp_377 data_program,
    ok_rule_icmp_380 data_program,
    ok_rule_icmp_386 data_program,
    ok_rule_icmp_394 data_program,
    ok_rule_icmp_402 data_program,
    ok_rule_icmp_410 data_program,
    ok_rule_icmp_438 data_program,
    ok_rule_icmp_442 data_program,
    ok_rule_icmp_447 data_program,
    ok_rule_icmp_451 data_program,
    ok_rule_icmp_479 data_program,
    ok_rule_icmp_482 data_program,
    ok_rule_icmp_485 data_program,
    ok_rule_icmp_486 data_program,
    ok_rule_icmp_489 data_program,
    ok_rule_icmp_490 data_program,
    ok_rule_icmp_491 data_program,
    ok_rule_icmp_492 data_program,
    ok_rule_icmp_495 data_program,
    ok_rule_icmp_498 data_program,
    ok_rule_icmp_501 data_program,
    ok_rule_icmp_502 data_program,
    ok_rule_icmp_505 data_program,
    ok_rule_icmp_506 data_program,
    ok_rule_icmp_509 data_program,
    ok_rule_icmp_510 data_program,
    ok_rule_icmp_513 data_program,
    ok_rule_icmp_514 data_program,
    ok_rule_icmp_517 data_program,
    ok_rule_icmp_520 data_program,
    ok_rule_icmp_523 data_program,
    ok_rule_icmp_526 data_program,
    ok_rule_icmp_529 data_program,
    ok_rule_icmp_532 data_program,
    ok_rule_icmp_535 data_program,
    ok_rule_selects_4 data_program,
    ok_rule_selects_9 data_program,
    ok_rule_selects_20 data_program,
    ok_rule_selects_26 data_program,
    ok_rule_selects_27 data_program,
    ok_rule_selects_28 data_program,
    ok_rule_selects_29 data_program,
    ok_rule_selects_30 data_program,
    ok_rule_selects_31 data_program,
    ok_rule_selects_32 data_program,
    ok_rule_selects_33 data_program,
    ok_rule_selects_36 data_program,
    ok_rule_selects_37 data_program,
    ok_rule_selects_38 data_program,
    ok_rule_selects_39 data_program,
    ok_rule_selects_40 data_program,
    ok_rule_selects_41 data_program,
    ok_rule_selects_42 data_program,
    ok_rule_selects_43 data_program,
    ok_rule_selects_91 data_program,
    ok_rule_selects_95 data_program,
    ok_rule_selects_103 data_program,
    ok_rule_selects_109 data_program,
    ok_rule_selects_110 data_program,
    ok_rule_selects_113 data_program,
    ok_rule_selects_114 data_program,
    ok_rule_selects_115 data_program,
    ok_rule_selects_116 data_program,
    ok_rule_selects_117 data_program,
    ok_rule_selects_118 data_program,
    ok_rule_selects_119 data_program,
    ok_rule_selects_120 data_program,
    ok_rule_selects_124 data_program,
    ok_rule_selects_125 data_program,
    ok_rule_selects_126 data_program,
    ok_rule_selects_127 data_program,
    ok_rule_selects_130 data_program,
    ok_rule_selects_131 data_program,
    ok_rule_selects_132 data_program,
    ok_rule_selects_133 data_program,
    ok_rule_selects_137 data_program,
    ok_rule_selects_138 data_program,
    ok_rule_selects_139 data_program,
    ok_rule_selects_140 data_program,
    ok_rule_selects_141 data_program,
    ok_rule_selects_142 data_program,
    ok_rule_selects_143 data_program,
    ok_rule_selects_144 data_program,
    ok_rule_selects_148 data_program,
    ok_rule_selects_149 data_program,
    ok_rule_selects_150 data_program,
    ok_rule_selects_151 data_program,
    ok_rule_selects_152 data_program,
    ok_rule_selects_153 data_program,
    ok_rule_selects_154 data_program,
    ok_rule_selects_155 data_program,
    ok_rule_selects_159 data_program,
    ok_rule_selects_160 data_program,
    ok_rule_selects_161 data_program,
    ok_rule_selects_162 data_program,
    ok_rule_selects_163 data_program,
    ok_rule_selects_164 data_program,
    ok_rule_selects_165 data_program,
    ok_rule_selects_166 data_program,
    ok_rule_selects_170 data_program,
    ok_rule_selects_171 data_program,
    ok_rule_selects_172 data_program,
    ok_rule_selects_173 data_program,
    ok_rule_selects_174 data_program,
    ok_rule_selects_175 data_program,
    ok_rule_selects_176 data_program,
    ok_rule_selects_177 data_program,
    ok_rule_selects_178 data_program,
    ok_rule_selects_179 data_program,
    ok_rule_selects_180 data_program,
    ok_rule_selects_181 data_program,
    ok_rule_selects_182 data_program,
    ok_rule_selects_183 data_program,
    ok_rule_selects_184 data_program,
    ok_rule_selects_185 data_program,
    ok_rule_selects_205 data_program,
    ok_rule_selects_209 data_program,
    ok_rule_selects_213 data_program,
    trivial⟩

set_option maxRecDepth 20000 in
theorem simplifyRulesCorrect_proven : SimplifyRulesCorrect program RuleAllow.proven.pred := by
  intro r hr ha
  have hm : r ∈ (program.rulesOf T.«simplify».id).filter (fun r => RuleAllow.proven.pred r.id) :=
    List.mem_filter.2 ⟨hr, ha⟩
  have hall := proven_rules_ok
  generalize (program.rulesOf T.«simplify».id).filter (fun r => RuleAllow.proven.pred r.id) = rs
    at hm hall
  exact AllOk.mem hall r hm

/-- **The proven rule set is sound.** -/
theorem simplifySound_proven : SimplifySound (RuleSetId.fnWith .proven .cranelift) :=
  simplifySound _ simplifyRulesCorrect_proven (by rw [simplify_rules_length]; decide)

set_option maxRecDepth 20000 in
/-- No `simplify_skeleton` rule is in the proven allow-list. -/
theorem skeleton_rules_proven :
    (program.rulesOf T.«simplify_skeleton».id).filter (fun r => RuleAllow.proven.pred r.id) = [] := by
  rfl

set_option maxRecDepth 20000 in
theorem skeleton_rules_length : (program.rulesOf T.«simplify_skeleton».id).length = 39 := by
  rfl

theorem skeletonRulesCorrect_proven : SkeletonRulesCorrect program RuleAllow.proven.pred := by
  intro r hr ha
  have hm : r ∈ (program.rulesOf T.«simplify_skeleton».id).filter
      (fun r => RuleAllow.proven.pred r.id) := List.mem_filter.2 ⟨hr, ha⟩
  rw [skeleton_rules_proven] at hm
  cases hm

/-- **The proven skeleton rule set is sound** (the obligation `simplify`'s pass proof takes for
`Opt.Config.skeletonFn` with `ruleAllow := .proven`). -/
theorem skeletonSound_proven : SkeletonSound (RuleSetId.skeletonFnWith .proven .cranelift) :=
  skeletonSound _ skeletonRulesCorrect_proven (by rw [skeleton_rules_length]; decide)

end Opt.Proof
