//! `isle2lean`: export Cranelift's aarch64 ISLE lowering unit (rules, terms,
//! types, VeriISLE specs) as Lean data under `FV/Isle/Generated/`.
//!
//! Usage: `isle2lean [--codegen-dir DIR] [--gen-dir DIR] [--out DIR]`
//! (defaults: the pinned `third_party/wasmtime/cranelift/codegen`, a scratch
//! directory under the Cargo target dir, and `FV/Isle/Generated`, all
//! relative to the repository root). See `docs/contracts/isle.md`.

mod closure;
mod lean;
mod load;

use anyhow::{Context, Result, bail};
use std::fmt::Write;
use std::path::{Path, PathBuf};

/// Maximum lines per generated Lean file.
const MAX_LINES: usize = 4000;
/// Maximum inline items per array chunk.
const MAX_ITEMS: usize = 400;
/// Maximum bytes per generated Lean file (keeps elaboration memory bounded).
const MAX_BYTES: usize = 250_000;

const HEADER: &str = "-- Generated by `rust/crates/isle2lean` from the Cranelift 0.136.1 aarch64 ISLE unit.\n\
-- Do not edit. Regenerate: `cargo run --manifest-path rust/Cargo.toml -p isle2lean --release`.\n";

struct Args {
    codegen_dir: PathBuf,
    gen_dir: PathBuf,
    out: PathBuf,
}

fn repo_root() -> PathBuf {
    // rust/crates/isle2lean -> repo root
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../..")
        .canonicalize()
        .expect("repository root")
}

fn parse_args() -> Result<Args> {
    let root = repo_root();
    let mut a = Args {
        codegen_dir: root.join("third_party/wasmtime/cranelift/codegen"),
        gen_dir: root.join("rust/target/isle2lean-gen"),
        out: root.join("FV/Isle/Generated"),
    };
    let mut it = std::env::args().skip(1);
    while let Some(flag) = it.next() {
        let val = |it: &mut dyn Iterator<Item = String>| {
            it.next()
                .map(PathBuf::from)
                .with_context(|| format!("{flag} needs a value"))
        };
        match flag.as_str() {
            "--codegen-dir" => a.codegen_dir = val(&mut it)?,
            "--gen-dir" => a.gen_dir = val(&mut it)?,
            "--out" => a.out = val(&mut it)?,
            "-h" | "--help" => {
                println!("isle2lean [--codegen-dir DIR] [--gen-dir DIR] [--out DIR]");
                std::process::exit(0);
            }
            _ => bail!("unknown argument {flag}"),
        }
    }
    a.codegen_dir = a
        .codegen_dir
        .canonicalize()
        .with_context(|| format!("codegen dir {}", a.codegen_dir.display()))?;
    std::fs::create_dir_all(&a.gen_dir)?;
    a.gen_dir = a.gen_dir.canonicalize()?;
    Ok(a)
}

/// One generated Lean module: `FV.Isle.Generated.<name>`.
struct Module {
    name: String,
    body: String,
}

/// Split blocks (each ending in a newline) into modules of at most
/// `MAX_LINES` lines and `max_items` blocks. Returns the block ranges.
fn chunk(blocks: &[String], max_items: usize) -> Vec<std::ops::Range<usize>> {
    let mut out = Vec::new();
    let mut start = 0;
    let mut lines = 0;
    let mut bytes = 0;
    for (i, b) in blocks.iter().enumerate() {
        let n = b.lines().count();
        if i > start
            && (lines + n > MAX_LINES || bytes + b.len() > MAX_BYTES || i - start >= max_items)
        {
            out.push(start..i);
            start = i;
            lines = 0;
            bytes = 0;
        }
        lines += n;
        bytes += b.len();
    }
    if start < blocks.len() {
        out.push(start..blocks.len());
    }
    out
}

fn module_header(imports: &[&str]) -> String {
    let mut s = String::from(HEADER);
    for i in imports {
        let _ = writeln!(s, "import {i}");
    }
    s.push_str("\nset_option maxRecDepth 100000\n\nnamespace Isle.Aarch64\nopen Isle\n\n");
    s
}

/// Modules of named `def`s plus a trailing `def <array>_<k> : Array <ty>`.
fn named_def_modules(
    prefix: &str,
    array: &str,
    ty: &str,
    names: &[String],
    blocks: &[String],
    max_items: usize,
) -> (Vec<Module>, Vec<String>) {
    let mut mods = Vec::new();
    let mut arrays = Vec::new();
    for (k, r) in chunk(blocks, max_items).into_iter().enumerate() {
        let mut body = module_header(&["FV.Isle.Syntax"]);
        for b in &blocks[r.clone()] {
            body.push_str(b);
            body.push('\n');
        }
        let arr = format!("{array}_{k}");
        let _ = writeln!(body, "def {arr} : Array {ty} := #[");
        let items: Vec<&str> = names[r].iter().map(|s| s.as_str()).collect();
        for (i, n) in items.iter().enumerate() {
            let _ = writeln!(body, "  {n}{}", if i + 1 < items.len() { "," } else { "]" });
        }
        body.push_str("\nend Isle.Aarch64\n");
        mods.push(Module {
            name: format!("{prefix}{k:02}"),
            body,
        });
        arrays.push(arr);
    }
    (mods, arrays)
}

/// Modules holding inline array literals `def <array>_<k> : Array <ty> := #[...]`.
fn inline_modules(
    prefix: &str,
    array: &str,
    ty: &str,
    items: &[String],
) -> (Vec<Module>, Vec<String>) {
    let blocks: Vec<String> = items.iter().map(|s| format!("{s}\n")).collect();
    let chunks = chunk(&blocks, MAX_ITEMS);
    // Group array chunks into modules by line count.
    let mut mods = Vec::new();
    let mut arrays = Vec::new();
    let mut body = String::new();
    let mut lines = 0;
    let mut bytes = 0;
    let mut modk = 0;
    let flush = |body: &mut String, modk: &mut usize, mods: &mut Vec<Module>| {
        let mut full = module_header(&["FV.Isle.Syntax"]);
        full.push_str(body);
        full.push_str("end Isle.Aarch64\n");
        mods.push(Module {
            name: format!("{prefix}{:02}", *modk),
            body: full,
        });
        body.clear();
        *modk += 1;
    };
    for (k, r) in chunks.into_iter().enumerate() {
        let n: usize = blocks[r.clone()].iter().map(|b| b.lines().count()).sum();
        let nb: usize = blocks[r.clone()].iter().map(|b| b.len()).sum();
        if lines > 0 && (lines + n > MAX_LINES || bytes + nb > MAX_BYTES) {
            flush(&mut body, &mut modk, &mut mods);
            lines = 0;
            bytes = 0;
        }
        let arr = format!("{array}_{k}");
        let _ = writeln!(body, "def {arr} : Array {ty} := #[");
        let len = r.len();
        for (i, b) in blocks[r].iter().enumerate() {
            let _ = write!(body, "  {}", b.trim_end());
            body.push_str(if i + 1 < len { ",\n" } else { "]\n\n" });
        }
        lines += n + 2;
        bytes += nb;
        arrays.push(arr);
    }
    if !body.is_empty() {
        flush(&mut body, &mut modk, &mut mods);
    }
    (mods, arrays)
}

fn concat(arrays: &[String]) -> String {
    if arrays.is_empty() {
        "#[]".into()
    } else {
        arrays.join(" ++ ")
    }
}

/// Text with `;` comments removed: generated inputs carry comments naming the absolute path of
/// the `cranelift-codegen-meta` sources, which must not make the manifest machine dependent.
fn strip_comments(s: &str) -> String {
    s.lines()
        .map(|l| l.split(';').next().unwrap_or(""))
        .collect::<Vec<_>>()
        .join("\n")
}

/// FNV-1a 64-bit hash (staleness check of the inputs; not cryptographic).
fn fnv1a(s: &str) -> u64 {
    let mut h: u64 = 0xcbf29ce484222325;
    for b in s.bytes() {
        h ^= b as u64;
        h = h.wrapping_mul(0x100000001b3);
    }
    h
}

fn main() -> Result<()> {
    let args = parse_args()?;
    let u = load::load(&args.codegen_dir, &args.gen_dir)?;
    let rule_names = lean::rule_names(&u);
    let type_names = lean::type_names(&u);

    let mut modules: Vec<Module> = Vec::new();

    // Types.
    let type_blocks: Vec<String> = u
        .tyenv
        .types
        .iter()
        .zip(&type_names)
        .map(|(t, n)| format!("def {n} : TypeDef :=\n  {}\n", lean::type_def(&u, t)))
        .collect();
    let (m, type_arrays) =
        named_def_modules("Types", "types", "TypeDef", &type_names, &type_blocks, MAX_ITEMS);
    modules.extend(m);

    // Terms.
    let extractors = lean::extractor_forms(&u);
    let term_items: Vec<String> = u
        .termenv
        .terms
        .iter()
        .map(|t| lean::term(&u, &extractors, t))
        .collect();
    let (m, term_arrays) = inline_modules("Terms", "terms", "Term", &term_items);
    modules.extend(m);

    // Rules: one def each.
    let named = lean::explicitly_named_rules(&u);
    let rule_blocks: Vec<String> = u
        .termenv
        .rules
        .iter()
        .zip(&rule_names)
        .map(|(r, n)| lean::rule_def(&u, r, n, named.contains(&r.pos)))
        .collect();
    let (m, rule_arrays) =
        named_def_modules("Rules", "rules", "Rule", &rule_names, &rule_blocks, MAX_ITEMS);
    modules.extend(m);

    // Specs.
    let specs = lean::spec_items(&u);
    let spec_items: Vec<String> = specs.iter().map(|s| lean::spec_item(&u, s)).collect();
    let (m, spec_arrays) = inline_modules("Specs", "specs", "SpecDef", &spec_items);
    modules.extend(m);

    // Program.
    let data_imports: Vec<String> = modules
        .iter()
        .map(|m| format!("FV.Isle.Generated.{}", m.name))
        .collect();
    {
        let imports: Vec<&str> = data_imports.iter().map(|s| s.as_str()).collect();
        let mut body = module_header(&imports);
        body.push_str("/-- Input files of the aarch64 compilation unit, in load order. -/\n");
        body.push_str("def files : Array String := #[\n");
        let n = u.files.file_names.len();
        for (i, f) in u.files.file_names.iter().enumerate() {
            let _ = writeln!(body, "  {}{}", lean::lstr(f), if i + 1 < n { "," } else { "]" });
        }
        body.push_str("\n/-- `(extern const $NAME Type)` declarations. -/\n");
        body.push_str("def consts : Array Const := #[");
        let mut first = true;
        for d in &u.defs {
            if let cranelift_isle::ast::Def::Extern(cranelift_isle::ast::Extern::Const {
                name, ty, ..
            }) = d
            {
                let tid = u
                    .tyenv
                    .get_type_by_name(ty)
                    .with_context(|| format!("const type {}", ty.0))?;
                let _ = write!(
                    body,
                    "{}\n  ⟨{}, {}⟩",
                    if first { "" } else { "," },
                    lean::lstr(&name.0),
                    tid.index()
                );
                first = false;
            }
        }
        body.push_str("]\n\n/-- `(convert Inner Outer term)` declarations. -/\n");
        body.push_str("def converters : Array Converter := #[");
        let mut first = true;
        for d in &u.defs {
            if let cranelift_isle::ast::Def::Converter(c) = d {
                let t = u
                    .termenv
                    .get_term_by_name(&u.tyenv, &c.term)
                    .with_context(|| format!("converter term {}", c.term.0))?;
                let i = u.tyenv.get_type_by_name(&c.inner_ty).context("converter type")?;
                let o = u.tyenv.get_type_by_name(&c.outer_ty).context("converter type")?;
                let _ = write!(
                    body,
                    "{}\n  ⟨{}, {}, {}⟩",
                    if first { "" } else { "," },
                    i.index(),
                    o.index(),
                    t.index()
                );
                first = false;
            }
        }
        body.push_str("]\n\n");
        let _ = writeln!(body, "def types : Array TypeDef := {}\n", concat(&type_arrays));
        let _ = writeln!(body, "def terms : Array Term := {}\n", concat(&term_arrays));
        let _ = writeln!(body, "def rules : Array Rule := {}\n", concat(&rule_arrays));
        let _ = writeln!(body, "def specs : Array SpecDef := {}\n", concat(&spec_arrays));
        body.push_str(
            "/-- The aarch64 lowering unit, with the per-term rule index built. -/\n\
             def program : Program :=\n  Program.build \"aarch64\" files types terms rules consts converters specs\n\n\
             end Isle.Aarch64\n",
        );
        modules.push(Module {
            name: "Program".into(),
            body,
        });
    }

    // Manifest: input hashes and per-file rule counts from the *AST* (the
    // parser's `Def::Rule`s, independent of the exported sema rules).
    {
        let mut body = module_header(&["FV.Isle.Syntax"]);
        body.push_str(
            "/-- `(file, bytes, FNV-1a 64)` of every input with `;` comments removed, in load order. -/\n\
             def inputHashes : List (String × Nat × Nat) := [\n",
        );
        let n = u.files.file_names.len();
        for i in 0..n {
            let text = &strip_comments(&u.files.file_texts[i]);
            let _ = writeln!(
                body,
                "  ({}, {}, {}){}",
                lean::lstr(&u.files.file_names[i]),
                text.len(),
                fnv1a(text),
                if i + 1 < n { "," } else { "]" }
            );
        }
        body.push_str(
            "\n/-- Number of `(rule ...)` forms per input file, counted on the parser's AST. -/\n\
             def astRuleCounts : List (String × Nat) := [\n",
        );
        let mut counts = vec![0usize; n];
        for d in &u.defs {
            if let cranelift_isle::ast::Def::Rule(r) = d {
                counts[r.pos.file] += 1;
            }
        }
        let with_rules: Vec<usize> = (0..n).filter(|&i| counts[i] > 0).collect();
        for (k, &i) in with_rules.iter().enumerate() {
            let _ = writeln!(
                body,
                "  ({}, {}){}",
                lean::lstr(&u.files.file_names[i]),
                counts[i],
                if k + 1 < with_rules.len() { "," } else { "]" }
            );
        }
        let _ = writeln!(
            body,
            "\n/-- Sizes of the analysed program (Rust side). -/\n\
             def sizes : List (String × Nat) :=\n  [(\"types\", {}), (\"terms\", {}), (\"rules\", {}), (\"specs\", {})]\n",
            u.tyenv.types.len(),
            u.termenv.terms.len(),
            u.termenv.rules.len(),
            specs.len()
        );
        body.push_str("end Isle.Aarch64\n");
        modules.push(Module {
            name: "Manifest".into(),
            body,
        });
        for &i in &with_rules {
            println!("rules {:>5}  {}", counts[i], u.files.file_names[i]);
        }
    }

    // Closure of `lower`/`lower_branch` for the emitter subset.
    modules.push(Module {
        name: "Closure".into(),
        body: closure::render(&u, &rule_names)?,
    });

    // Write, replacing every previously generated module.
    std::fs::create_dir_all(&args.out)?;
    for e in std::fs::read_dir(&args.out)? {
        let p = e?.path();
        if p.extension().is_some_and(|e| e == "lean") {
            std::fs::remove_file(&p)?;
        }
    }
    for m in &modules {
        let lines = m.body.lines().count();
        if lines > 5000 {
            bail!("module {} has {lines} lines", m.name);
        }
        std::fs::write(args.out.join(format!("{}.lean", m.name)), &m.body)?;
    }
    println!(
        "types {} terms {} rules {} specs {} -> {} modules in {}",
        u.tyenv.types.len(),
        u.termenv.terms.len(),
        u.termenv.rules.len(),
        specs.len(),
        modules.len(),
        args.out.display()
    );
    Ok(())
}
