//! `isle2lean`: export Cranelift's aarch64 ISLE lowering unit (rules, terms,
//! types, VeriISLE specs) as Lean data under `FV/Isle/Generated/`.
//!
//! Usage: `isle2lean [--codegen-dir DIR] [--gen-dir DIR] [--out DIR]`
//! (defaults: the pinned `third_party/wasmtime/cranelift/codegen`, a scratch
//! directory under the Cargo target dir, and `FV/Isle/Generated`, all
//! relative to the repository root). See `docs/contracts/isle.md`.

mod closure;
mod lean;
mod load;

use anyhow::{Context, Result, bail};
use std::fmt::Write;
use std::path::{Path, PathBuf};

/// Maximum lines per generated Lean file.
const MAX_LINES: usize = 4000;
/// Maximum inline items per array chunk.
const MAX_ITEMS: usize = 400;
/// Maximum bytes per generated Lean file (keeps elaboration memory bounded).
const MAX_BYTES: usize = 250_000;

const HEADER: &str = "-- Generated by `rust/crates/isle2lean` from the Cranelift 0.136.1 aarch64 ISLE unit.\n\
-- Do not edit. Regenerate: `cargo run --manifest-path rust/Cargo.toml -p isle2lean --release`.\n";

struct Args {
    codegen_dir: PathBuf,
    gen_dir: PathBuf,
    out: PathBuf,
}

fn repo_root() -> PathBuf {
    // rust/crates/isle2lean -> repo root
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../..")
        .canonicalize()
        .expect("repository root")
}

fn parse_args() -> Result<Args> {
    let root = repo_root();
    let mut a = Args {
        codegen_dir: root.join("third_party/wasmtime/cranelift/codegen"),
        gen_dir: root.join("rust/target/isle2lean-gen"),
        out: root.join("FV/Isle/Generated"),
    };
    let mut it = std::env::args().skip(1);
    while let Some(flag) = it.next() {
        let val = |it: &mut dyn Iterator<Item = String>| {
            it.next()
                .map(PathBuf::from)
                .with_context(|| format!("{flag} needs a value"))
        };
        match flag.as_str() {
            "--codegen-dir" => a.codegen_dir = val(&mut it)?,
            "--gen-dir" => a.gen_dir = val(&mut it)?,
            "--out" => a.out = val(&mut it)?,
            "-h" | "--help" => {
                println!("isle2lean [--codegen-dir DIR] [--gen-dir DIR] [--out DIR]");
                std::process::exit(0);
            }
            _ => bail!("unknown argument {flag}"),
        }
    }
    a.codegen_dir = a
        .codegen_dir
        .canonicalize()
        .with_context(|| format!("codegen dir {}", a.codegen_dir.display()))?;
    std::fs::create_dir_all(&a.gen_dir)?;
    a.gen_dir = a.gen_dir.canonicalize()?;
    Ok(a)
}

/// One generated Lean module: `FV.Isle.Generated.<name>`.
struct Module {
    name: String,
    body: String,
}

/// Split blocks (each ending in a newline) into modules of at most
/// `MAX_LINES` lines and `max_items` blocks. Returns the block ranges.
fn chunk(blocks: &[String], max_items: usize) -> Vec<std::ops::Range<usize>> {
    let mut out = Vec::new();
    let mut start = 0;
    let mut lines = 0;
    let mut bytes = 0;
    for (i, b) in blocks.iter().enumerate() {
        let n = b.lines().count();
        if i > start
            && (lines + n > MAX_LINES || bytes + b.len() > MAX_BYTES || i - start >= max_items)
        {
            out.push(start..i);
            start = i;
            lines = 0;
            bytes = 0;
        }
        lines += n;
        bytes += b.len();
    }
    if start < blocks.len() {
        out.push(start..blocks.len());
    }
    out
}

fn module_header(imports: &[&str]) -> String {
    let mut s = String::from(HEADER);
    for i in imports {
        let _ = writeln!(s, "import {i}");
    }
    s.push_str("\nset_option maxRecDepth 100000\n\nnamespace Isle.Aarch64\nopen Isle\n\n");
    s
}

/// Modules of `def` blocks (each ending in a newline), chunked by `chunk`.
fn def_modules(prefix: &str, imports: &[&str], blocks: &[String]) -> Vec<Module> {
    chunk(blocks, usize::MAX)
        .into_iter()
        .enumerate()
        .map(|(k, r)| {
            let mut body = module_header(imports);
            for b in &blocks[r] {
                body.push_str(b);
                body.push('\n');
            }
            body.push_str("end Isle.Aarch64\n");
            Module {
                name: format!("{prefix}{k:02}"),
                body,
            }
        })
        .collect()
}

/// A module holding one flat array literal `def <name> : Array <ty> := #[...]`, one item per
/// line with its index. Flat (not an append of chunks) so that the kernel can index it: the
/// isel proofs' data facts (`program.terms[t]? = some T.x`) are `rfl`.
fn table_module(module: &str, imports: &[&str], doc: &str, name: &str, ty: &str, items: &[String]) -> Module {
    let mut body = module_header(imports);
    let _ = writeln!(body, "/-- {doc} -/\ndef {name} : Array {ty} := #[");
    for (i, it) in items.iter().enumerate() {
        let _ = writeln!(body, "  {it}{} -- {i}", if i + 1 < items.len() { "," } else { "]" });
    }
    body.push_str("\nend Isle.Aarch64\n");
    Module {
        name: module.into(),
        body,
    }
}

fn module_names(mods: &[Module]) -> Vec<String> {
    mods.iter().map(|m| format!("FV.Isle.Generated.{}", m.name)).collect()
}

/// Modules holding inline array literals `def <array>_<k> : Array <ty> := #[...]`.
fn inline_modules(
    prefix: &str,
    array: &str,
    ty: &str,
    items: &[String],
) -> (Vec<Module>, Vec<String>) {
    let blocks: Vec<String> = items.iter().map(|s| format!("{s}\n")).collect();
    let chunks = chunk(&blocks, MAX_ITEMS);
    // Group array chunks into modules by line count.
    let mut mods = Vec::new();
    let mut arrays = Vec::new();
    let mut body = String::new();
    let mut lines = 0;
    let mut bytes = 0;
    let mut modk = 0;
    let flush = |body: &mut String, modk: &mut usize, mods: &mut Vec<Module>| {
        let mut full = module_header(&["FV.Isle.Syntax"]);
        full.push_str(body);
        full.push_str("end Isle.Aarch64\n");
        mods.push(Module {
            name: format!("{prefix}{:02}", *modk),
            body: full,
        });
        body.clear();
        *modk += 1;
    };
    for (k, r) in chunks.into_iter().enumerate() {
        let n: usize = blocks[r.clone()].iter().map(|b| b.lines().count()).sum();
        let nb: usize = blocks[r.clone()].iter().map(|b| b.len()).sum();
        if lines > 0 && (lines + n > MAX_LINES || bytes + nb > MAX_BYTES) {
            flush(&mut body, &mut modk, &mut mods);
            lines = 0;
            bytes = 0;
        }
        let arr = format!("{array}_{k}");
        let _ = writeln!(body, "def {arr} : Array {ty} := #[");
        let len = r.len();
        for (i, b) in blocks[r].iter().enumerate() {
            let _ = write!(body, "  {}", b.trim_end());
            body.push_str(if i + 1 < len { ",\n" } else { "]\n\n" });
        }
        lines += n + 2;
        bytes += nb;
        arrays.push(arr);
    }
    if !body.is_empty() {
        flush(&mut body, &mut modk, &mut mods);
    }
    (mods, arrays)
}

fn concat(arrays: &[String]) -> String {
    if arrays.is_empty() {
        "#[]".into()
    } else {
        arrays.join(" ++ ")
    }
}

/// Text with `;` comments removed: generated inputs carry comments naming the absolute path of
/// the `cranelift-codegen-meta` sources, which must not make the manifest machine dependent.
fn strip_comments(s: &str) -> String {
    s.lines()
        .map(|l| l.split(';').next().unwrap_or(""))
        .collect::<Vec<_>>()
        .join("\n")
}

/// FNV-1a 64-bit hash (staleness check of the inputs; not cryptographic).
fn fnv1a(s: &str) -> u64 {
    let mut h: u64 = 0xcbf29ce484222325;
    for b in s.bytes() {
        h ^= b as u64;
        h = h.wrapping_mul(0x100000001b3);
    }
    h
}

fn main() -> Result<()> {
    let args = parse_args()?;
    let u = load::load(&args.codegen_dir, &args.gen_dir)?;
    let rule_names = lean::rule_names(&u);
    let type_names = lean::type_names(&u);

    let mut modules: Vec<Module> = Vec::new();

    // Types: one `def ty_<name>` each.
    let type_blocks: Vec<String> = u
        .tyenv
        .types
        .iter()
        .zip(&type_names)
        .map(|(t, n)| format!("def {n} : TypeDef :=\n  {}\n", lean::type_def(&u, t)))
        .collect();
    let type_mods = def_modules("Types", &["FV.Isle.Syntax"], &type_blocks);

    // Ids: `TyId.«T»`, `VIdx.«T».«V»`, `TId.«t»` (match patterns for the backend's dispatch).
    let ids = Module {
        name: "Ids".into(),
        body: lean::ids_module(&u, &module_header(&["FV.Isle.Syntax"])),
    };

    // Terms: one `def T.«name»` each.
    let extractors = lean::extractor_forms(&u);
    let term_consts: Vec<String> = u
        .termenv
        .terms
        .iter()
        .map(|t| format!("T.{}", lean::lname(u.sym(t.name))))
        .collect();
    let term_blocks: Vec<String> = u
        .termenv
        .terms
        .iter()
        .zip(&term_consts)
        .map(|(t, n)| {
            format!(
                "/-- term {} -/\ndef {n} : Term :=\n  {}\n",
                t.id.index(),
                lean::term(&u, &extractors, t)
            )
        })
        .collect();
    let term_mods = def_modules("Terms", &["FV.Isle.Syntax"], &term_blocks);

    // Rules: one def each.
    let named = lean::explicitly_named_rules(&u);
    let rule_blocks: Vec<String> = u
        .termenv
        .rules
        .iter()
        .zip(&rule_names)
        .map(|(r, n)| lean::rule_def(&u, r, n, named.contains(&r.pos)))
        .collect();
    let rule_mods = def_modules("Rules", &["FV.Isle.Syntax"], &rule_blocks);

    // Per-term rule lists `R.«term»`, in matching order (`ruleBefore`: priority descending,
    // then rule id ascending), for every term that has rules.
    let mut by_term: Vec<Vec<usize>> = vec![Vec::new(); u.termenv.terms.len()];
    for r in &u.termenv.rules {
        by_term[r.root_term.index()].push(r.id.index());
    }
    for rs in &mut by_term {
        rs.sort_by_key(|&i| (std::cmp::Reverse(u.termenv.rules[i].prio), i));
    }
    let mut rl_blocks = Vec::new();
    let mut rule_lists = Vec::new();
    for (t, rs) in by_term.iter().enumerate() {
        if rs.is_empty() {
            rule_lists.push("[]".to_string());
            continue;
        }
        let name = format!("R.{}", lean::lname(u.sym(u.termenv.terms[t].name)));
        let mut b = format!("/-- Rules of term {t}, in matching order. -/\ndef {name} : List Rule := [");
        for (i, &r) in rs.iter().enumerate() {
            let _ = write!(b, "{}\n  {}", if i > 0 { "," } else { "" }, rule_names[r]);
        }
        b.push_str("]\n");
        rl_blocks.push(b);
        rule_lists.push(name);
    }
    let rule_mod_names = module_names(&rule_mods);
    let rl_mods = def_modules(
        "RuleLists",
        &rule_mod_names.iter().map(|s| s.as_str()).collect::<Vec<_>>(),
        &rl_blocks,
    );

    // Specs.
    let specs = lean::spec_items(&u);
    let spec_items: Vec<String> = specs.iter().map(|s| lean::spec_item(&u, s)).collect();
    let (spec_mods, spec_arrays) = inline_modules("Specs", "specs", "SpecDef", &spec_items);

    // Flat tables.
    let term_mod_names = module_names(&term_mods);
    let term_table = table_module(
        "TermTable",
        &term_mod_names.iter().map(|s| s.as_str()).collect::<Vec<_>>(),
        "All terms, indexed by `TermId`.",
        "terms",
        "Term",
        &term_consts,
    );
    let rl_mod_names = module_names(&rl_mods);
    let rule_table = table_module(
        "RuleTable",
        &rl_mod_names.iter().map(|s| s.as_str()).collect::<Vec<_>>(),
        "The rules of each term (indexed by `TermId`) in matching order.",
        "ruleLists",
        "(List Rule)",
        &rule_lists,
    );
    let type_mod_names = module_names(&type_mods);
    let rule_array = table_module(
        "RuleArray",
        &rule_mod_names.iter().map(|s| s.as_str()).collect::<Vec<_>>(),
        "All rules, indexed by `RuleId`.",
        "rules",
        "Rule",
        &rule_names,
    );
    let type_array = table_module(
        "TypeArray",
        &type_mod_names.iter().map(|s| s.as_str()).collect::<Vec<_>>(),
        "All types, indexed by `TypeId`.",
        "types",
        "TypeDef",
        &type_names,
    );
    modules.extend(type_mods);
    modules.push(ids);
    modules.extend(term_mods);
    modules.extend(rule_mods);
    modules.extend(rl_mods);
    modules.extend(spec_mods);
    let spec_mod_names: Vec<String> = modules
        .iter()
        .filter(|m| m.name.starts_with("Specs"))
        .map(|m| format!("FV.Isle.Generated.{}", m.name))
        .collect();
    let table_names: Vec<String> = [&type_array, &term_table, &rule_array, &rule_table]
        .iter()
        .map(|m| format!("FV.Isle.Generated.{}", m.name))
        .collect();
    modules.push(type_array);
    modules.push(term_table);
    modules.push(rule_array);
    modules.push(rule_table);

    // Program.
    {
        let mut imports: Vec<&str> = vec!["FV.Isle.Generated.Ids"];
        imports.extend(table_names.iter().map(|s| s.as_str()));
        imports.extend(spec_mod_names.iter().map(|s| s.as_str()));
        let mut body = module_header(&imports);
        body.push_str("/-- Input files of the aarch64 compilation unit, in load order. -/\n");
        body.push_str("def files : Array String := #[\n");
        let n = u.files.file_names.len();
        for (i, f) in u.files.file_names.iter().enumerate() {
            let _ = writeln!(body, "  {}{}", lean::lstr(f), if i + 1 < n { "," } else { "]" });
        }
        body.push_str("\n/-- `(extern const $NAME Type)` declarations. -/\n");
        body.push_str("def consts : Array Const := #[");
        let mut first = true;
        for d in &u.defs {
            if let cranelift_isle::ast::Def::Extern(cranelift_isle::ast::Extern::Const {
                name, ty, ..
            }) = d
            {
                let tid = u
                    .tyenv
                    .get_type_by_name(ty)
                    .with_context(|| format!("const type {}", ty.0))?;
                let _ = write!(
                    body,
                    "{}\n  ⟨{}, {}⟩",
                    if first { "" } else { "," },
                    lean::lstr(&name.0),
                    tid.index()
                );
                first = false;
            }
        }
        body.push_str("]\n\n/-- `(convert Inner Outer term)` declarations. -/\n");
        body.push_str("def converters : Array Converter := #[");
        let mut first = true;
        for d in &u.defs {
            if let cranelift_isle::ast::Def::Converter(c) = d {
                let t = u
                    .termenv
                    .get_term_by_name(&u.tyenv, &c.term)
                    .with_context(|| format!("converter term {}", c.term.0))?;
                let i = u.tyenv.get_type_by_name(&c.inner_ty).context("converter type")?;
                let o = u.tyenv.get_type_by_name(&c.outer_ty).context("converter type")?;
                let _ = write!(
                    body,
                    "{}\n  ⟨{}, {}, {}⟩",
                    if first { "" } else { "," },
                    i.index(),
                    o.index(),
                    t.index()
                );
                first = false;
            }
        }
        body.push_str("]\n\n");
        let _ = writeln!(body, "def specs : Array SpecDef := {}\n", concat(&spec_arrays));
        body.push_str(
            "/-- The aarch64 lowering unit. A structure literal over flat tables (no computation), so\n\
             that the kernel evaluates `program.term? t`, `program.rulesOf t` by `rfl`;\n\
             `FVTest/Isle/Data.lean` checks `ruleLists` against `Program.build`'s bucket sort. -/\n\
             def program : Program where\n  name := \"aarch64\"\n  files := files\n  types := types\n  \
             terms := terms\n  rules := rules\n  consts := consts\n  converters := converters\n  \
             specs := specs\n  ruleLists := ruleLists\n\n\
             end Isle.Aarch64\n",
        );
        modules.push(Module {
            name: "Program".into(),
            body,
        });
    }

    // Manifest: input hashes and per-file rule counts from the *AST* (the
    // parser's `Def::Rule`s, independent of the exported sema rules).
    {
        let mut body = module_header(&["FV.Isle.Syntax"]);
        body.push_str(
            "/-- `(file, bytes, FNV-1a 64)` of every input with `;` comments removed, in load order. -/\n\
             def inputHashes : List (String × Nat × Nat) := [\n",
        );
        let n = u.files.file_names.len();
        for i in 0..n {
            let text = &strip_comments(&u.files.file_texts[i]);
            let _ = writeln!(
                body,
                "  ({}, {}, {}){}",
                lean::lstr(&u.files.file_names[i]),
                text.len(),
                fnv1a(text),
                if i + 1 < n { "," } else { "]" }
            );
        }
        body.push_str(
            "\n/-- Number of `(rule ...)` forms per input file, counted on the parser's AST. -/\n\
             def astRuleCounts : List (String × Nat) := [\n",
        );
        let mut counts = vec![0usize; n];
        for d in &u.defs {
            if let cranelift_isle::ast::Def::Rule(r) = d {
                counts[r.pos.file] += 1;
            }
        }
        let with_rules: Vec<usize> = (0..n).filter(|&i| counts[i] > 0).collect();
        for (k, &i) in with_rules.iter().enumerate() {
            let _ = writeln!(
                body,
                "  ({}, {}){}",
                lean::lstr(&u.files.file_names[i]),
                counts[i],
                if k + 1 < with_rules.len() { "," } else { "]" }
            );
        }
        let _ = writeln!(
            body,
            "\n/-- Sizes of the analysed program (Rust side). -/\n\
             def sizes : List (String × Nat) :=\n  [(\"types\", {}), (\"terms\", {}), (\"rules\", {}), (\"specs\", {})]\n",
            u.tyenv.types.len(),
            u.termenv.terms.len(),
            u.termenv.rules.len(),
            specs.len()
        );
        body.push_str("end Isle.Aarch64\n");
        modules.push(Module {
            name: "Manifest".into(),
            body,
        });
        for &i in &with_rules {
            println!("rules {:>5}  {}", counts[i], u.files.file_names[i]);
        }
    }

    // Closure of `lower`/`lower_branch` for the emitter subset.
    modules.push(Module {
        name: "Closure".into(),
        body: closure::render(&u, &rule_names)?,
    });

    // Write, replacing every previously generated module.
    std::fs::create_dir_all(&args.out)?;
    for e in std::fs::read_dir(&args.out)? {
        let p = e?.path();
        if p.extension().is_some_and(|e| e == "lean") {
            std::fs::remove_file(&p)?;
        }
    }
    for m in &modules {
        let lines = m.body.lines().count();
        if lines > 5000 {
            bail!("module {} has {lines} lines", m.name);
        }
        std::fs::write(args.out.join(format!("{}.lean", m.name)), &m.body)?;
    }
    println!(
        "types {} terms {} rules {} specs {} -> {} modules in {}",
        u.tyenv.types.len(),
        u.termenv.terms.len(),
        u.termenv.rules.len(),
        specs.len(),
        modules.len(),
        args.out.display()
    );
    Ok(())
}
